/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Lupira Geo API
 * Gazetteer, geocoding, and saved-places backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */
import type { AdminLevel } from './adminLevel';

export interface AdminAreaDto {
  id: string;
  level: AdminLevel;
  name: string;
  /** @nullable */
  isoCode?: string | null;
  /** @nullable */
  withinAreaId?: string | null;
  /** @nullable */
  latitude?: number | null;
  /** @nullable */
  longitude?: number | null;
}
