/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lupira Geo API
 * Gazetteer, geocoding, and saved-places backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */

export interface CreateSavedPlaceRequest {
  label: string;
  /** @nullable */
  placeId?: string | null;
  /** @nullable */
  latitude?: number | null;
  /** @nullable */
  longitude?: number | null;
  /** @nullable */
  icon?: string | null;
  /** @nullable */
  notes?: string | null;
  isFavorite?: boolean;
}
