/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Lupira Geo API
 * Gazetteer, geocoding, and saved-places backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */
import type { PlaceCategory } from './placeCategory';

export interface GeocodeResultDto {
  displayName: string;
  latitude: number;
  longitude: number;
  category: PlaceCategory;
  /** @nullable */
  countryCode?: string | null;
  /** @nullable */
  country?: string | null;
  /** @nullable */
  region?: string | null;
  /** @nullable */
  locality?: string | null;
  /** @nullable */
  osmType?: string | null;
  /** @nullable */
  osmId?: number | null;
}
