/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lupira Geo API
 * Gazetteer, geocoding, and saved-places backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */
import type { PlaceCategory } from './placeCategory';
import type { PlaceKind } from './placeKind';
import type { PlaceSource } from './placeSource';

export interface OrphanCandidateDto {
  placeId: string;
  name: string;
  kind: PlaceKind;
  category: PlaceCategory;
  source: PlaceSource;
  verified: boolean;
  hasCoordinates: boolean;
  createdAt: string;
  contactRefs: number;
  calendarLiveRefs: number;
  calendarDeletedRefs: number;
  savedPlaceRefs: number;
  prunable: boolean;
}
