/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Lupira Geo API
 * Gazetteer, geocoding, and saved-places backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */
import type { ExternalScheme } from './externalScheme';

export interface PlaceExternalIdDto {
  scheme: ExternalScheme;
  value: string;
}
