/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Lupira Geo API
 * Gazetteer, geocoding, and saved-places backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */
import type { PlaceCategory } from './placeCategory';
import type { SuggestionType } from './suggestionType';

export interface PlaceSuggestionDto {
  id: string;
  type: SuggestionType;
  name: string;
  category?: null | PlaceCategory;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
     */
  latitude?: number | string | null;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
     */
  longitude?: number | string | null;
  /** @nullable */
  context?: string | null;
}
