/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Lupira Geo API
 * Gazetteer, geocoding, and saved-places backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */
import type { PlaceCategory } from './placeCategory';
import type { PlaceKind } from './placeKind';

export type SearchPlacesParams = {
q?: string;
category?: PlaceCategory;
kind?: PlaceKind;
withinAreaId?: string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
 */
nearLat?: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
 */
nearLon?: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
 */
radiusM?: number | string;
/**
 * @items.pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
 */
bbox?: (number | string)[];
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
limit?: number | string;
};
