/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lupira Geo API
 * Gazetteer, geocoding, and saved-places backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */

/**
 * What a typeahead suggestion points at: a gazetteer SuggestionType.Place or an AdminArea locality.
 */
export type SuggestionType = typeof SuggestionType[keyof typeof SuggestionType];


export const SuggestionType = {
  Place: 'Place',
  Locality: 'Locality',
} as const;
