/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Lupira Geo API
 * Gazetteer, geocoding, and saved-places backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */

export type SuggestionType = typeof SuggestionType[keyof typeof SuggestionType];


export const SuggestionType = {
  Place: 'Place',
  Locality: 'Locality',
} as const;
