/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Lupira Geo API
 * Gazetteer, geocoding, and saved-places backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */

export interface UpdateSavedPlaceRequest {
  /** @nullable */
  label?: string | null;
  /** @nullable */
  placeId?: string | null;
  /** @nullable */
  latitude?: number | null;
  /** @nullable */
  longitude?: number | null;
  /** @nullable */
  icon?: string | null;
  /** @nullable */
  notes?: string | null;
  /** @nullable */
  isFavorite?: boolean | null;
}
