/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Lupira Geo API
 * Gazetteer, geocoding, and saved-places backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */
import type { PlaceCategory } from './placeCategory';

export interface UpdatePlaceRequest {
  /** @nullable */
  name?: string | null;
  category?: null | PlaceCategory;
  /** @nullable */
  verified?: boolean | null;
}
