/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lupira Location API
 * Location and presence backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */
import type { MotionActivity } from './motionActivity';

export interface CurrentFixDto {
  deviceId: string;
  ts: string;
  lat: number;
  lon: number;
  /** @nullable */
  accuracyM?: number | null;
  /** @nullable */
  speedMps?: number | null;
  activity?: null | MotionActivity;
  /** @nullable */
  batteryPct?: number | null;
}
