/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Lupira Location API
 * Location and presence backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */
import type { VisitedPlaceDto } from './visitedPlaceDto';

export interface DailyLocationSummaryDto {
  date: string;
  distanceM: number;
  timeInMotionS: number;
  timeStationaryS: number;
  visitCount: number;
  places: VisitedPlaceDto[];
}
