/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lupira Location API
 * Location and presence backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */

/**
 * A per-row rejection within an otherwise-accepted batch (permanent — the uploader should drop + log it).
 */
export interface IngestReject {
  /** @nullable */
  seq?: number | null;
  reason: string;
}
