/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lupira Location API
 * Location and presence backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */

export interface PlaceLabelAtDto {
  ts: string;
  /** @nullable */
  label?: string | null;
  lat: number;
  lon: number;
  source: string;
}
