/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lupira Location API
 * Location and presence backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */
import type { DeviceDto } from './deviceDto';

export interface RegisterDeviceResponse {
  device: DeviceDto;
  keyId: string;
  apiKey: string;
}
