/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * LupiraCalApi | v1
 * OpenAPI spec version: 1.0.0
 */

export type Access = typeof Access[keyof typeof Access];


export const Access = {
  Owner: 'Owner',
  ReadWrite: 'ReadWrite',
  Read: 'Read',
} as const;
