/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * LupiraCalApi | v1
 * OpenAPI spec version: 1.0.0
 */

export type ActionKind = typeof ActionKind[keyof typeof ActionKind];


export const ActionKind = {
  SendCheckIn: 'SendCheckIn',
  Notify: 'Notify',
  CreateLinkedTask: 'CreateLinkedTask',
  ExpireTarget: 'ExpireTarget',
  RescheduleSelf: 'RescheduleSelf',
  RunJob: 'RunJob',
  Rescore: 'Rescore',
} as const;
