/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * LupiraCalApi | v1
 * OpenAPI spec version: 1.0.0
 */

export interface AppointmentDetail {
  /** @nullable */
  providerContactId: string | null;
  /** @nullable */
  appointmentType: string | null;
  /** @nullable */
  referenceNumber: string | null;
  /** @nullable */
  preparationNotes: string | null;
}
