/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Lupira Cal API
 * Calendar, contacts, and CalDAV backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */

export interface AppointmentDetailRequest {
  /** @nullable */
  providerContactId?: string | null;
  /** @nullable */
  appointmentType?: string | null;
  /** @nullable */
  referenceNumber?: string | null;
  /** @nullable */
  preparationNotes?: string | null;
}
