/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lupira Cal API
 * Calendar backend for Lupira (contacts live in LupiraContactApi; the DAV protocol surface in LupiraDavApi). Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */

/**
 * A presence/availability segment's status. A day may hold several segments (whole-day or timed).
 */
export type AvailabilityStatus = typeof AvailabilityStatus[keyof typeof AvailabilityStatus];


export const AvailabilityStatus = {
  Office: 'Office',
  Home: 'Home',
  Vacation: 'Vacation',
  Sick: 'Sick',
  Leave: 'Leave',
} as const;
