/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * LupiraCalApi | v1
 * OpenAPI spec version: 1.0.0
 */

export type AvailabilityStatus = typeof AvailabilityStatus[keyof typeof AvailabilityStatus];


export const AvailabilityStatus = {
  Office: 'Office',
  Home: 'Home',
  Vacation: 'Vacation',
  Sick: 'Sick',
  Leave: 'Leave',
} as const;
