/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Lupira Cal API
 * Calendar, contacts, and CalDAV backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */

export interface BillDetail {
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$
     */
  amount: number | string | null;
  /** @nullable */
  currency: string | null;
  /** @nullable */
  payee: string | null;
  /** @nullable */
  invoiceNumber: string | null;
  /** @nullable */
  paidAt: string | null;
}
