/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Lupira Cal API
 * Calendar backend for Lupira (contacts live in LupiraContactApi; the DAV protocol surface in LupiraDavApi). Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */

export interface BookingDetail {
  /** @nullable */
  providerContactId: string | null;
  /** @nullable */
  confirmationNumber: string | null;
  /** @nullable */
  reference: string | null;
  /** @nullable */
  url: string | null;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$
     */
  amount: number | string | null;
  /** @nullable */
  currency: string | null;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  partySize: number | string | null;
}
