/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * LupiraCalApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { CalendarMembershipDto } from './calendarMembershipDto';
import type { CompletenessScore } from './completenessScore';
import type { ItemAction } from './itemAction';
import type { ItemAttendee } from './itemAttendee';
import type { ItemKind } from './itemKind';
import type { ItemKindDetails } from './itemKindDetails';
import type { ItemPrompt } from './itemPrompt';
import type { ItemStatus } from './itemStatus';
import type { JsonNode } from './jsonNode';

export interface CalendarItemDto {
  id: string;
  icalUid: string;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  description?: string | null;
  status?: null | ItemStatus;
  isAllDay: boolean;
  /** @nullable */
  startsAt?: string | null;
  /** @nullable */
  endsAt?: string | null;
  /** @nullable */
  startDate?: string | null;
  /** @nullable */
  endDate?: string | null;
  /** @nullable */
  recurrenceRule?: string | null;
  kind?: null | ItemKind;
  kindDetails?: null | ItemKindDetails;
  /** @nullable */
  placeId?: string | null;
  /** @nullable */
  parentItemId?: string | null;
  /** @nullable */
  tags?: string[] | null;
  metadata?: null | JsonNode;
  prompt?: null | ItemPrompt;
  action?: null | ItemAction;
  completeness?: null | CompletenessScore;
  attendees: ItemAttendee[];
  calendars: CalendarMembershipDto[];
  etag: string;
}
