/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Lupira Cal API
 * Calendar, contacts, and CalDAV backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */

export type CalendarKind = typeof CalendarKind[keyof typeof CalendarKind];


export const CalendarKind = {
  Personal: 'Personal',
  Group: 'Group',
  Birthdays: 'Birthdays',
  Availability: 'Availability',
  Inbox: 'Inbox',
  LlmPrompts: 'LlmPrompts',
  UserCheckIn: 'UserCheckIn',
  DevOps: 'DevOps',
  FoodPlan: 'FoodPlan',
  Generic: 'Generic',
} as const;
