/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Lupira Cal API
 * Calendar backend for Lupira (contacts live in LupiraContactApi; the DAV protocol surface in LupiraDavApi). Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */
import type { CalendarEntryStatus } from './calendarEntryStatus';

export interface CalendarMembershipDto {
  calendarId: string;
  status: CalendarEntryStatus;
}
