/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * LupiraCalApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { CalendarEntryStatus } from './calendarEntryStatus';

export interface CalendarMembershipDto {
  calendarId: string;
  status: CalendarEntryStatus;
}
