/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Lupira Cal API
 * Calendar, contacts, and CalDAV backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */
import type { CompletenessScore } from './completenessScore';

export interface CalendarItemOccurrenceDto {
  id: string;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  placeId?: string | null;
  /** @nullable */
  locationLabel?: string | null;
  isAllDay: boolean;
  start: string;
  /** @nullable */
  end?: string | null;
  completeness?: null | CompletenessScore;
  etag: string;
}
