/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * LupiraCalApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { CompletenessScore } from './completenessScore';

export interface CalendarItemOccurrenceDto {
  id: string;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  placeId?: string | null;
  isAllDay: boolean;
  start: string;
  /** @nullable */
  end?: string | null;
  completeness?: null | CompletenessScore;
  etag: string;
}
