/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * LupiraCalApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { GapSeverity } from './gapSeverity';

export interface CompletenessGap {
  field: string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  weight: number | string;
  severity: GapSeverity;
}
