/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Lupira Cal API
 * Calendar, contacts, and CalDAV backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */
import type { Access } from './access';
import type { CalendarClass } from './calendarClass';
import type { CalendarKind } from './calendarKind';

export interface ContainerDto {
  id: string;
  type: string;
  slug: string;
  /** @nullable */
  displayName?: string | null;
  /** @nullable */
  color?: string | null;
  /** @nullable */
  defaultTimezone?: string | null;
  class?: null | CalendarClass;
  kind?: null | CalendarKind;
  access: Access;
}
