/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Lupira Cal API
 * Calendar, contacts, and CalDAV backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */
import type { CompletenessScore } from './completenessScore';
import type { ContactPostalAddress } from './contactPostalAddress';
import type { ContactRelation } from './contactRelation';
import type { ContactSocialProfile } from './contactSocialProfile';
import type { JsonNode } from './jsonNode';

export interface ContactDto {
  id: string;
  addressBookId: string;
  externalId: string;
  displayName: string;
  /** @nullable */
  givenName?: string | null;
  /** @nullable */
  familyName?: string | null;
  /** @nullable */
  nickname?: string | null;
  /** @nullable */
  emails?: string[] | null;
  /** @nullable */
  phones?: string[] | null;
  /** @nullable */
  birthday?: string | null;
  /** @nullable */
  tags?: string[] | null;
  addresses: ContactPostalAddress[];
  profiles: ContactSocialProfile[];
  relations: ContactRelation[];
  metadata?: null | JsonNode;
  completeness?: null | CompletenessScore;
  etag: string;
}
