/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * LupiraCalApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { CompletenessScore } from './completenessScore';
import type { ContactPostalAddress } from './contactPostalAddress';
import type { ContactSocialProfile } from './contactSocialProfile';
import type { JsonNode } from './jsonNode';

export interface ContactDto {
  id: string;
  addressBookId: string;
  vcardUid: string;
  displayName: string;
  /** @nullable */
  givenName?: string | null;
  /** @nullable */
  familyName?: string | null;
  /** @nullable */
  nickname?: string | null;
  /** @nullable */
  emails?: string[] | null;
  /** @nullable */
  phones?: string[] | null;
  /** @nullable */
  birthday?: string | null;
  /** @nullable */
  tags?: string[] | null;
  addresses: ContactPostalAddress[];
  profiles: ContactSocialProfile[];
  metadata?: null | JsonNode;
  completeness?: null | CompletenessScore;
  etag: string;
}
