/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * LupiraCalApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { AvailabilityStatus } from './availabilityStatus';

export interface CreateCalendarItemRequest {
  /** @nullable */
  calendarId?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  location?: string | null;
  /** @nullable */
  status?: string | null;
  isAllDay?: boolean;
  /** @nullable */
  startsAt?: string | null;
  /** @nullable */
  endsAt?: string | null;
  /** @nullable */
  startTimezone?: string | null;
  /** @nullable */
  startDate?: string | null;
  /** @nullable */
  endDate?: string | null;
  /** @nullable */
  recurrenceRule?: string | null;
  /** @nullable */
  kind?: string | null;
  /** @nullable */
  tags?: string[] | null;
  availability?: null | AvailabilityStatus;
}
