/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Lupira Cal API
 * Calendar backend for Lupira (contacts live in LupiraContactApi; the DAV protocol surface in LupiraDavApi). Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */

export type FallbackMode = typeof FallbackMode[keyof typeof FallbackMode];


export const FallbackMode = {
  Retry: 'Retry',
  Ask: 'Ask',
  Drop: 'Drop',
} as const;
