/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * LupiraCalApi | v1
 * OpenAPI spec version: 1.0.0
 */

export interface FlightDetail {
  /** @nullable */
  flightNumber: string | null;
  /** @nullable */
  terminal: string | null;
  /** @nullable */
  gate: string | null;
  /** @nullable */
  gateClosesAt: string | null;
  /** @nullable */
  seatAssignment: string | null;
  /** @nullable */
  baggageAllowance: string | null;
}
