/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Lupira Cal API
 * Calendar, contacts, and CalDAV backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */

export interface FlightDetail {
  /** @nullable */
  flightNumber: string | null;
  /** @nullable */
  terminal: string | null;
  /** @nullable */
  gate: string | null;
  /** @nullable */
  gateClosesAt: string | null;
  /** @nullable */
  seatAssignment: string | null;
  /** @nullable */
  baggageAllowance: string | null;
}
