/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lupira Cal API
 * Calendar backend for Lupira (contacts live in LupiraContactApi; the DAV protocol surface in LupiraDavApi). Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */

/**
 * A field is fully present, weak/partial (0.5), or absent.
 */
export type GapSeverity = typeof GapSeverity[keyof typeof GapSeverity];


export const GapSeverity = {
  Weak: 'Weak',
  Absent: 'Absent',
} as const;
