/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Lupira Cal API
 * Calendar, contacts, and CalDAV backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */
import type { PlaceKind } from './placeKind';

export type GetPlacesParams = {
ids?: string[];
search?: string;
kind?: PlaceKind;
parentPlaceId?: string;
};
