/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lupira Cal API
 * Calendar backend for Lupira (contacts live in LupiraContactApi; the DAV protocol surface in LupiraDavApi). Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */

/**
 * Grant a member access to a container, identified by their login `Email` (provisioned if they have
 *             not logged in yet). `Access` is `owner` (default), `read-write`, or `read` — case-insensitive.
 */
export interface GrantOwnerRequest {
  email: string;
  /** @nullable */
  access?: string | null;
}
