/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * LupiraCalApi | v1
 * OpenAPI spec version: 1.0.0
 */

export type ItemStatus = typeof ItemStatus[keyof typeof ItemStatus];


export const ItemStatus = {
  Tentative: 'Tentative',
  Confirmed: 'Confirmed',
  Cancelled: 'Cancelled',
} as const;
