/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Lupira Cal API
 * Calendar, contacts, and CalDAV backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */
import type { BookingDetail } from './bookingDetail';
import type { PresenceDetail } from './presenceDetail';
import type { TravelLeg } from './travelLeg';

export interface ItemDetails {
  booking?: null | BookingDetail;
  travel?: null | TravelLeg;
  presence?: null | PresenceDetail;
}
