/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Lupira Cal API
 * Calendar, contacts, and CalDAV backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */
import type { ParticipationRole } from './participationRole';
import type { ParticipationStatus } from './participationStatus';

export interface ItemAttendee {
  participationId?: string;
  contactId?: string;
  role?: ParticipationRole;
  status?: ParticipationStatus;
  /** @nullable */
  invitedAt?: string | null;
  /** @nullable */
  respondedAt?: string | null;
  /** @nullable */
  attendedAt?: string | null;
  /** @nullable */
  leftAt?: string | null;
}
