/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * LupiraCalApi | v1
 * OpenAPI spec version: 1.0.0
 */

export interface MeDto {
  id: string;
  email: string;
  /** @nullable */
  displayName?: string | null;
}
