/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * LupiraCalApi | v1
 * OpenAPI spec version: 1.0.0
 */

export type ModelTier = typeof ModelTier[keyof typeof ModelTier];


export const ModelTier = {
  Small: 'Small',
  Medium: 'Medium',
  Large: 'Large',
} as const;
