/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * LupiraCalApi | v1
 * OpenAPI spec version: 1.0.0
 */

export type OutputKind = typeof OutputKind[keyof typeof OutputKind];


export const OutputKind = {
  RecordEdit: 'RecordEdit',
  Event: 'Event',
  Task: 'Task',
  Message: 'Message',
  Summary: 'Summary',
  Question: 'Question',
  Relation: 'Relation',
  None: 'None',
} as const;
