/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lupira Cal API
 * Calendar backend for Lupira (contacts live in LupiraContactApi; the DAV protocol surface in LupiraDavApi). Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */

/**
 * The ProposedAction kind a run is contracted to yield (assistant-api validates against it; cal-api only stores it).
 */
export type OutputKind = typeof OutputKind[keyof typeof OutputKind];


export const OutputKind = {
  RecordEdit: 'RecordEdit',
  Event: 'Event',
  Task: 'Task',
  Message: 'Message',
  Summary: 'Summary',
  Question: 'Question',
  Relation: 'Relation',
  None: 'None',
} as const;
