/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Lupira Cal API
 * Calendar, contacts, and CalDAV backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */

export type OutputKind = typeof OutputKind[keyof typeof OutputKind];


export const OutputKind = {
  RecordEdit: 'RecordEdit',
  Event: 'Event',
  Task: 'Task',
  Message: 'Message',
  Summary: 'Summary',
  Question: 'Question',
  Relation: 'Relation',
  None: 'None',
} as const;
