/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Lupira Cal API
 * Calendar, contacts, and CalDAV backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */

export type ParticipationStatus = typeof ParticipationStatus[keyof typeof ParticipationStatus];


export const ParticipationStatus = {
  NeedsAction: 'NeedsAction',
  Accepted: 'Accepted',
  Declined: 'Declined',
  Tentative: 'Tentative',
  Delegated: 'Delegated',
} as const;
