/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Lupira Cal API
 * Calendar backend for Lupira (contacts live in LupiraContactApi; the DAV protocol surface in LupiraDavApi). Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */

export type ParticipationRole = typeof ParticipationRole[keyof typeof ParticipationRole];


export const ParticipationRole = {
  Chair: 'Chair',
  RequiredParticipant: 'RequiredParticipant',
  OptionalParticipant: 'OptionalParticipant',
  NonParticipant: 'NonParticipant',
} as const;
