/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * LupiraCalApi | v1
 * OpenAPI spec version: 1.0.0
 */

export type PlaceKind = typeof PlaceKind[keyof typeof PlaceKind];


export const PlaceKind = {
  Country: 'Country',
  City: 'City',
  Address: 'Address',
  Venue: 'Venue',
} as const;
