/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lupira Cal API
 * Calendar backend for Lupira (contacts live in LupiraContactApi; the DAV protocol surface in LupiraDavApi). Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */

/**
 * When a payload fires relative to its item's occurrence.
 */
export type PromptFireKind = typeof PromptFireKind[keyof typeof PromptFireKind];


export const PromptFireKind = {
  OnStart: 'OnStart',
  OnEnd: 'OnEnd',
  Offset: 'Offset',
  AllDayAt: 'AllDayAt',
} as const;
