/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Lupira Cal API
 * Calendar, contacts, and CalDAV backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */
import type { PromptFireKind } from './promptFireKind';

export interface PromptFire {
  kind: PromptFireKind;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  offsetMinutes: number | string | null;
  /** @nullable */
  allDayAt: string | null;
}
