/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * LupiraCalApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { PromptFireKind } from './promptFireKind';

export interface PromptFire {
  kind: PromptFireKind;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  offsetMinutes: number | string | null;
  /** @nullable */
  allDayAt: string | null;
}
