/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * LupiraCalApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { RefKind } from './refKind';

export interface Ref {
  kind: RefKind;
  /** @nullable */
  id: string | null;
  /** @nullable */
  url: string | null;
}
