/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Lupira Cal API
 * Calendar, contacts, and CalDAV backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */

export type RefKind = typeof RefKind[keyof typeof RefKind];


export const RefKind = {
  Event: 'Event',
  Contact: 'Contact',
  Task: 'Task',
  External: 'External',
} as const;
