/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Lupira Cal API
 * Calendar backend for Lupira (contacts live in LupiraContactApi; the DAV protocol surface in LupiraDavApi). Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */
import type { JsonNode } from './jsonNode';

export interface RelationDto {
  id: string;
  fromKind: string;
  fromId: string;
  toKind: string;
  toRef: string;
  relationType: string;
  metadata?: null | JsonNode;
}
