/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * LupiraCalApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { JsonNode } from './jsonNode';

export interface RelationDto {
  id: string;
  fromKind: string;
  fromId: string;
  toKind: string;
  toRef: string;
  relationType: string;
  metadata?: null | JsonNode;
}
