/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lupira Cal API
 * Calendar backend for Lupira (contacts live in LupiraContactApi; the DAV protocol surface in LupiraDavApi). Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */
import type { ParticipationRef } from './participationRef';

export interface SetParticipantsResult {
  itemId: string;
  added: ParticipationRef[];
  alreadyPresent: number;
}
