/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Lupira Cal API
 * Calendar, contacts, and CalDAV backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */

export interface TravelDetail {
  toPlaceId: string;
  /** @nullable */
  fromPlaceId: string | null;
  /** @nullable */
  departAt: string | null;
  /** @nullable */
  arriveAt: string | null;
  /** @nullable */
  carrier: string | null;
  /** @nullable */
  bookingReference: string | null;
}
