/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Lupira Cal API
 * Calendar, contacts, and CalDAV backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */
import type { TransportMode } from './transportMode';

export interface TravelLeg {
  mode: TransportMode;
  /** @nullable */
  toPlaceId: string | null;
  /** @nullable */
  fromPlaceId: string | null;
  /** @nullable */
  departAt: string | null;
  /** @nullable */
  arriveAt: string | null;
  /** @nullable */
  carrier: string | null;
  /** @nullable */
  serviceNumber: string | null;
  /** @nullable */
  departurePoint: string | null;
  /** @nullable */
  arrivalPoint: string | null;
  /** @nullable */
  seat: string | null;
  /** @nullable */
  driverContactId: string | null;
  /** @nullable */
  toLabel?: string | null;
  /** @nullable */
  fromLabel?: string | null;
}
