/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Lupira Cal API
 * Calendar backend for Lupira (contacts live in LupiraContactApi; the DAV protocol surface in LupiraDavApi). Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */
import type { AvailabilityStatus } from './availabilityStatus';
import type { DatePrecision } from './datePrecision';
import type { ItemDetailsRequest } from './itemDetailsRequest';

export interface UpdateCalendarItemRequest {
  /** @nullable */
  title?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  location?: string | null;
  /** @nullable */
  status?: string | null;
  /** @nullable */
  startsAt?: string | null;
  startsAtProvided?: boolean;
  /** @nullable */
  endsAt?: string | null;
  endsAtProvided?: boolean;
  /** @nullable */
  isAllDay?: boolean | null;
  /** @nullable */
  startDate?: string | null;
  startDateProvided?: boolean;
  /** @nullable */
  endDate?: string | null;
  endDateProvided?: boolean;
  /** @nullable */
  startTimezone?: string | null;
  startTimezoneProvided?: boolean;
  /** @nullable */
  endTimezone?: string | null;
  endTimezoneProvided?: boolean;
  /** @nullable */
  recurrenceRule?: string | null;
  recurrenceRuleProvided?: boolean;
  startPrecision?: null | DatePrecision;
  endPrecision?: null | DatePrecision;
  /** @nullable */
  parentItemId?: string | null;
  /** @nullable */
  category?: string | null;
  /** @nullable */
  tags?: string[] | null;
  availability?: null | AvailabilityStatus;
  details?: null | ItemDetailsRequest;
  /** @nullable */
  occurredAt?: string | null;
}
