/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Lupira Cal API
 * Calendar, contacts, and CalDAV backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */
import type { AvailabilityStatus } from './availabilityStatus';
import type { ItemDetailsRequest } from './itemDetailsRequest';

export interface UpdateCalendarItemRequest {
  /** @nullable */
  title?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  location?: string | null;
  /** @nullable */
  status?: string | null;
  /** @nullable */
  startsAt?: string | null;
  /** @nullable */
  endsAt?: string | null;
  /** @nullable */
  recurrenceRule?: string | null;
  /** @nullable */
  category?: string | null;
  /** @nullable */
  tags?: string[] | null;
  availability?: null | AvailabilityStatus;
  details?: null | ItemDetailsRequest;
}
