// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace LupiraCalBff.Upstream.Contact.Models
{
    /// <summary>
    /// How well-documented this contact is. Drives contact-enrichment ranking (completeness × relevance).
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CompletenessScore : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The gaps property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::LupiraCalBff.Upstream.Contact.Models.CompletenessGap>? Gaps { get; set; }
#nullable restore
#else
        public List<global::LupiraCalBff.Upstream.Contact.Models.CompletenessGap> Gaps { get; set; }
#endif
        /// <summary>The rubricVersion property</summary>
        public int? RubricVersion { get; set; }
        /// <summary>The score property</summary>
        public double? Score { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::LupiraCalBff.Upstream.Contact.Models.CompletenessScore"/> and sets the default values.
        /// </summary>
        public CompletenessScore()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::LupiraCalBff.Upstream.Contact.Models.CompletenessScore"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::LupiraCalBff.Upstream.Contact.Models.CompletenessScore CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::LupiraCalBff.Upstream.Contact.Models.CompletenessScore();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "gaps", n => { Gaps = n.GetCollectionOfObjectValues<global::LupiraCalBff.Upstream.Contact.Models.CompletenessGap>(global::LupiraCalBff.Upstream.Contact.Models.CompletenessGap.CreateFromDiscriminatorValue)?.AsList(); } },
                { "rubricVersion", n => { RubricVersion = n.GetIntValue(); } },
                { "score", n => { Score = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::LupiraCalBff.Upstream.Contact.Models.CompletenessGap>("gaps", Gaps);
            writer.WriteIntValue("rubricVersion", RubricVersion);
            writer.WriteDoubleValue("score", Score);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
