// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace LupiraCalBff.Upstream.Contact.Models
{
    /// <summary>A personal grouping (Friends/Family/Colleagues) vs a company/institution. An employer is membership in an `Organization`-kind group.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ContactGroupKind
    {
        [EnumMember(Value = "Group")]
        #pragma warning disable CS1591
        Group,
        #pragma warning restore CS1591
        [EnumMember(Value = "Organization")]
        #pragma warning disable CS1591
        Organization,
        #pragma warning restore CS1591
    }
}
