// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace LupiraCalBff.Upstream.Contact.Models
{
    /// <summary>
    /// One outgoing relation edge as published: &quot;the `ToContactId` contact is my `Kind`&quot;.            `Ended`/`Until` mark a relationship that ran its course, distinct from removal.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ContactRelationDto : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The ended property</summary>
        public bool? Ended { get; set; }
        /// <summary>Kind of a contact-to-contact edge: the related (To) contact&apos;s role relative to the owning contact (&quot;To is my Kind&quot;).            The extended-family kinds are storable for when the linking relative isn&apos;t a contact (a deceased parent, say); the same            kinds are also produced by KinshipInference from the parent/child graph, distinguished on read by RelationProvenance.</summary>
        public global::LupiraCalBff.Upstream.Contact.Models.ContactRelationKind? Kind { get; set; }
        /// <summary>The label property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Label { get; set; }
#nullable restore
#else
        public string Label { get; set; }
#endif
        /// <summary>The note property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Note { get; set; }
#nullable restore
#else
        public string Note { get; set; }
#endif
        /// <summary>The since property</summary>
        public Date? Since { get; set; }
        /// <summary>The toContactId property</summary>
        public Guid? ToContactId { get; set; }
        /// <summary>The until property</summary>
        public Date? Until { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::LupiraCalBff.Upstream.Contact.Models.ContactRelationDto"/> and sets the default values.
        /// </summary>
        public ContactRelationDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::LupiraCalBff.Upstream.Contact.Models.ContactRelationDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::LupiraCalBff.Upstream.Contact.Models.ContactRelationDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::LupiraCalBff.Upstream.Contact.Models.ContactRelationDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "ended", n => { Ended = n.GetBoolValue(); } },
                { "kind", n => { Kind = n.GetEnumValue<global::LupiraCalBff.Upstream.Contact.Models.ContactRelationKind>(); } },
                { "label", n => { Label = n.GetStringValue(); } },
                { "note", n => { Note = n.GetStringValue(); } },
                { "since", n => { Since = n.GetDateValue(); } },
                { "toContactId", n => { ToContactId = n.GetGuidValue(); } },
                { "until", n => { Until = n.GetDateValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("ended", Ended);
            writer.WriteEnumValue<global::LupiraCalBff.Upstream.Contact.Models.ContactRelationKind>("kind", Kind);
            writer.WriteStringValue("label", Label);
            writer.WriteStringValue("note", Note);
            writer.WriteDateValue("since", Since);
            writer.WriteGuidValue("toContactId", ToContactId);
            writer.WriteDateValue("until", Until);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
