/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lupira Location API
 * Location and presence backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CurrentFixDto,
  DailyLocationSummaryDto,
  DeviceDto,
  GetBoundingBoxParams,
  GetCurrentLocationParams,
  GetDailySummaryParams,
  GetLocationAtParams,
  GetMovementStatsParams,
  GetThinnedTrackParams,
  GetTrackParams,
  ListTripsParams,
  ListVisitsParams,
  LocationCursor,
  LocationIngestReceipt,
  LocationTripDto,
  LocationVisitDto,
  MeDto,
  PauseTrackingRequest,
  PlaceLabelAtDto,
  ProblemDetails,
  PurgeLocationHistoryParams,
  RegisterDeviceRequest,
  RegisterDeviceResponse,
  RenameDeviceRequest,
  TrackPointDto,
  TrackStatsDto,
  TrackingStateDto
} from './models';

import { customFetchLocation } from '../fetcher';
type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getWhoAmIUrl = () => {




  return `/me`
}

/**
 * @summary The caller's resolved local identity (JIT-provisioned on first login).
 */
export const whoAmI = async ( options?: Parameters<typeof customFetchLocation>[1]): Promise<MeDto> => {

  return customFetchLocation<MeDto>(getWhoAmIUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getWhoAmIQueryKey = () => {
    return [
    `/me`
    ] as const;
    }


export const getWhoAmIQueryOptions = <TData = Awaited<ReturnType<typeof whoAmI>>, TError = ProblemDetails>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof whoAmI>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWhoAmIQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof whoAmI>>> = ({ signal }) => whoAmI({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof whoAmI>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type WhoAmIQueryResult = NonNullable<Awaited<ReturnType<typeof whoAmI>>>
export type WhoAmIQueryError = ProblemDetails


export function useWhoAmI<TData = Awaited<ReturnType<typeof whoAmI>>, TError = ProblemDetails>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof whoAmI>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof whoAmI>>,
          TError,
          Awaited<ReturnType<typeof whoAmI>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWhoAmI<TData = Awaited<ReturnType<typeof whoAmI>>, TError = ProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof whoAmI>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof whoAmI>>,
          TError,
          Awaited<ReturnType<typeof whoAmI>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWhoAmI<TData = Awaited<ReturnType<typeof whoAmI>>, TError = ProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof whoAmI>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary The caller's resolved local identity (JIT-provisioned on first login).
 */

export function useWhoAmI<TData = Awaited<ReturnType<typeof whoAmI>>, TError = ProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof whoAmI>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getWhoAmIQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getListDevicesUrl = () => {




  return `/devices`
}

/**
 * @summary List the caller's registered location-tracking devices.
 */
export const listDevices = async ( options?: Parameters<typeof customFetchLocation>[1]): Promise<DeviceDto[]> => {

  return customFetchLocation<DeviceDto[]>(getListDevicesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListDevicesQueryKey = () => {
    return [
    `/devices`
    ] as const;
    }


export const getListDevicesQueryOptions = <TData = Awaited<ReturnType<typeof listDevices>>, TError = ProblemDetails>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDevices>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListDevicesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listDevices>>> = ({ signal }) => listDevices({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listDevices>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListDevicesQueryResult = NonNullable<Awaited<ReturnType<typeof listDevices>>>
export type ListDevicesQueryError = ProblemDetails


export function useListDevices<TData = Awaited<ReturnType<typeof listDevices>>, TError = ProblemDetails>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDevices>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDevices>>,
          TError,
          Awaited<ReturnType<typeof listDevices>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListDevices<TData = Awaited<ReturnType<typeof listDevices>>, TError = ProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDevices>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDevices>>,
          TError,
          Awaited<ReturnType<typeof listDevices>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListDevices<TData = Awaited<ReturnType<typeof listDevices>>, TError = ProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDevices>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List the caller's registered location-tracking devices.
 */

export function useListDevices<TData = Awaited<ReturnType<typeof listDevices>>, TError = ProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDevices>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListDevicesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getRegisterDeviceUrl = () => {




  return `/devices`
}

/**
 * @summary Register a device; returns the one-time ingest API key.
 */
export const registerDevice = async (registerDeviceRequest: RegisterDeviceRequest, options?: Parameters<typeof customFetchLocation>[1]): Promise<RegisterDeviceResponse> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetchLocation<RegisterDeviceResponse>(getRegisterDeviceUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(registerDeviceRequest)
  }
);}





export const getRegisterDeviceMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerDevice>>, TError,{data: RegisterDeviceRequest}, TContext>, request?: SecondParameter<typeof customFetchLocation>}
): UseMutationOptions<Awaited<ReturnType<typeof registerDevice>>, TError,{data: RegisterDeviceRequest}, TContext> => {

const mutationKey = ['registerDevice'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof registerDevice>>, {data: RegisterDeviceRequest}> = (props) => {
          const {data} = props ?? {};

          return  registerDevice(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RegisterDeviceMutationResult = NonNullable<Awaited<ReturnType<typeof registerDevice>>>
    export type RegisterDeviceMutationBody = RegisterDeviceRequest
    export type RegisterDeviceMutationError = ProblemDetails

    /**
 * @summary Register a device; returns the one-time ingest API key.
 */
export const useRegisterDevice = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerDevice>>, TError,{data: RegisterDeviceRequest}, TContext>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof registerDevice>>,
        TError,
        {data: RegisterDeviceRequest},
        TContext
      > => {
      return useMutation(getRegisterDeviceMutationOptions(options), queryClient);
    }

export const getRenameDeviceUrl = (id: string,) => {




  return `/devices/${id}`
}

/**
 * @summary Rename a device.
 */
export const renameDevice = async (id: string,
    renameDeviceRequest: RenameDeviceRequest, options?: Parameters<typeof customFetchLocation>[1]): Promise<DeviceDto> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetchLocation<DeviceDto>(getRenameDeviceUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(renameDeviceRequest)
  }
);}





export const getRenameDeviceMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof renameDevice>>, TError,{id: string;data: RenameDeviceRequest}, TContext>, request?: SecondParameter<typeof customFetchLocation>}
): UseMutationOptions<Awaited<ReturnType<typeof renameDevice>>, TError,{id: string;data: RenameDeviceRequest}, TContext> => {

const mutationKey = ['renameDevice'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof renameDevice>>, {id: string;data: RenameDeviceRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  renameDevice(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RenameDeviceMutationResult = NonNullable<Awaited<ReturnType<typeof renameDevice>>>
    export type RenameDeviceMutationBody = RenameDeviceRequest
    export type RenameDeviceMutationError = ProblemDetails

    /**
 * @summary Rename a device.
 */
export const useRenameDevice = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof renameDevice>>, TError,{id: string;data: RenameDeviceRequest}, TContext>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof renameDevice>>,
        TError,
        {id: string;data: RenameDeviceRequest},
        TContext
      > => {
      return useMutation(getRenameDeviceMutationOptions(options), queryClient);
    }

export const getRetireDeviceUrl = (id: string,) => {




  return `/devices/${id}`
}

/**
 * @summary Retire a device (revokes its ingest keys).
 */
export const retireDevice = async (id: string, options?: Parameters<typeof customFetchLocation>[1]): Promise<void> => {

  return customFetchLocation<void>(getRetireDeviceUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getRetireDeviceMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof retireDevice>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetchLocation>}
): UseMutationOptions<Awaited<ReturnType<typeof retireDevice>>, TError,{id: string}, TContext> => {

const mutationKey = ['retireDevice'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof retireDevice>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  retireDevice(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RetireDeviceMutationResult = NonNullable<Awaited<ReturnType<typeof retireDevice>>>

    export type RetireDeviceMutationError = ProblemDetails

    /**
 * @summary Retire a device (revokes its ingest keys).
 */
export const useRetireDevice = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof retireDevice>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof retireDevice>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getRetireDeviceMutationOptions(options), queryClient);
    }

export const getIngestLocationUrl = () => {




  return `/ingest/location`
}

/**
 * @summary Ingest a batch of GPS fixes (NDJSON, one fix per line).
 */
export const ingestLocation = async (ingestLocationBody: string, options?: Parameters<typeof customFetchLocation>[1]): Promise<LocationIngestReceipt> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetchLocation<LocationIngestReceipt>(getIngestLocationUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/x-ndjson', ...getHeaders(options?.headers) },
    body: JSON.stringify(ingestLocationBody)
  }
);}





export const getIngestLocationMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof ingestLocation>>, TError,{data: string}, TContext>, request?: SecondParameter<typeof customFetchLocation>}
): UseMutationOptions<Awaited<ReturnType<typeof ingestLocation>>, TError,{data: string}, TContext> => {

const mutationKey = ['ingestLocation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof ingestLocation>>, {data: string}> = (props) => {
          const {data} = props ?? {};

          return  ingestLocation(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type IngestLocationMutationResult = NonNullable<Awaited<ReturnType<typeof ingestLocation>>>
    export type IngestLocationMutationBody = string
    export type IngestLocationMutationError = ProblemDetails

    /**
 * @summary Ingest a batch of GPS fixes (NDJSON, one fix per line).
 */
export const useIngestLocation = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof ingestLocation>>, TError,{data: string}, TContext>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof ingestLocation>>,
        TError,
        {data: string},
        TContext
      > => {
      return useMutation(getIngestLocationMutationOptions(options), queryClient);
    }

export const getGetIngestCursorUrl = () => {




  return `/ingest/location/cursor`
}

/**
 * @summary The device's resume cursor (last accepted seq + ts).
 */
export const getIngestCursor = async ( options?: Parameters<typeof customFetchLocation>[1]): Promise<LocationCursor> => {

  return customFetchLocation<LocationCursor>(getGetIngestCursorUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetIngestCursorQueryKey = () => {
    return [
    `/ingest/location/cursor`
    ] as const;
    }


export const getGetIngestCursorQueryOptions = <TData = Awaited<ReturnType<typeof getIngestCursor>>, TError = ProblemDetails>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIngestCursor>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetIngestCursorQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getIngestCursor>>> = ({ signal }) => getIngestCursor({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getIngestCursor>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetIngestCursorQueryResult = NonNullable<Awaited<ReturnType<typeof getIngestCursor>>>
export type GetIngestCursorQueryError = ProblemDetails


export function useGetIngestCursor<TData = Awaited<ReturnType<typeof getIngestCursor>>, TError = ProblemDetails>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIngestCursor>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIngestCursor>>,
          TError,
          Awaited<ReturnType<typeof getIngestCursor>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetIngestCursor<TData = Awaited<ReturnType<typeof getIngestCursor>>, TError = ProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIngestCursor>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIngestCursor>>,
          TError,
          Awaited<ReturnType<typeof getIngestCursor>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetIngestCursor<TData = Awaited<ReturnType<typeof getIngestCursor>>, TError = ProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIngestCursor>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary The device's resume cursor (last accepted seq + ts).
 */

export function useGetIngestCursor<TData = Awaited<ReturnType<typeof getIngestCursor>>, TError = ProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIngestCursor>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetIngestCursorQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getGetIngestStateUrl = () => {




  return `/ingest/location/state`
}

/**
 * @summary Whether tracking is paused for this device (the uploader should stop collecting if so).
 */
export const getIngestState = async ( options?: Parameters<typeof customFetchLocation>[1]): Promise<TrackingStateDto> => {

  return customFetchLocation<TrackingStateDto>(getGetIngestStateUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetIngestStateQueryKey = () => {
    return [
    `/ingest/location/state`
    ] as const;
    }


export const getGetIngestStateQueryOptions = <TData = Awaited<ReturnType<typeof getIngestState>>, TError = ProblemDetails>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIngestState>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetIngestStateQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getIngestState>>> = ({ signal }) => getIngestState({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getIngestState>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetIngestStateQueryResult = NonNullable<Awaited<ReturnType<typeof getIngestState>>>
export type GetIngestStateQueryError = ProblemDetails


export function useGetIngestState<TData = Awaited<ReturnType<typeof getIngestState>>, TError = ProblemDetails>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIngestState>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIngestState>>,
          TError,
          Awaited<ReturnType<typeof getIngestState>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetIngestState<TData = Awaited<ReturnType<typeof getIngestState>>, TError = ProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIngestState>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIngestState>>,
          TError,
          Awaited<ReturnType<typeof getIngestState>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetIngestState<TData = Awaited<ReturnType<typeof getIngestState>>, TError = ProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIngestState>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Whether tracking is paused for this device (the uploader should stop collecting if so).
 */

export function useGetIngestState<TData = Awaited<ReturnType<typeof getIngestState>>, TError = ProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIngestState>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetIngestStateQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getGetCurrentLocationUrl = (params?: GetCurrentLocationParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/location/current?${stringifiedParams}` : `/location/current`
}

/**
 * @summary Latest known location per device.
 */
export const getCurrentLocation = async (params?: GetCurrentLocationParams, options?: Parameters<typeof customFetchLocation>[1]): Promise<CurrentFixDto[]> => {

  return customFetchLocation<CurrentFixDto[]>(getGetCurrentLocationUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCurrentLocationQueryKey = (params?: GetCurrentLocationParams,) => {
    return [
    `/location/current`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetCurrentLocationQueryOptions = <TData = Awaited<ReturnType<typeof getCurrentLocation>>, TError = ProblemDetails>(params?: GetCurrentLocationParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentLocation>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCurrentLocationQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCurrentLocation>>> = ({ signal }) => getCurrentLocation(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCurrentLocation>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCurrentLocationQueryResult = NonNullable<Awaited<ReturnType<typeof getCurrentLocation>>>
export type GetCurrentLocationQueryError = ProblemDetails


export function useGetCurrentLocation<TData = Awaited<ReturnType<typeof getCurrentLocation>>, TError = ProblemDetails>(
 params: undefined |  GetCurrentLocationParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentLocation>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentLocation>>,
          TError,
          Awaited<ReturnType<typeof getCurrentLocation>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCurrentLocation<TData = Awaited<ReturnType<typeof getCurrentLocation>>, TError = ProblemDetails>(
 params?: GetCurrentLocationParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentLocation>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentLocation>>,
          TError,
          Awaited<ReturnType<typeof getCurrentLocation>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCurrentLocation<TData = Awaited<ReturnType<typeof getCurrentLocation>>, TError = ProblemDetails>(
 params?: GetCurrentLocationParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentLocation>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Latest known location per device.
 */

export function useGetCurrentLocation<TData = Awaited<ReturnType<typeof getCurrentLocation>>, TError = ProblemDetails>(
 params?: GetCurrentLocationParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentLocation>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCurrentLocationQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getGetTrackUrl = (params?: GetTrackParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/location/track?${stringifiedParams}` : `/location/track`
}

/**
 * @summary Raw track over a time range (capped).
 */
export const getTrack = async (params?: GetTrackParams, options?: Parameters<typeof customFetchLocation>[1]): Promise<TrackPointDto[]> => {

  return customFetchLocation<TrackPointDto[]>(getGetTrackUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetTrackQueryKey = (params?: GetTrackParams,) => {
    return [
    `/location/track`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetTrackQueryOptions = <TData = Awaited<ReturnType<typeof getTrack>>, TError = ProblemDetails>(params?: GetTrackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTrack>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTrackQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTrack>>> = ({ signal }) => getTrack(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTrack>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTrackQueryResult = NonNullable<Awaited<ReturnType<typeof getTrack>>>
export type GetTrackQueryError = ProblemDetails


export function useGetTrack<TData = Awaited<ReturnType<typeof getTrack>>, TError = ProblemDetails>(
 params: undefined |  GetTrackParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTrack>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTrack>>,
          TError,
          Awaited<ReturnType<typeof getTrack>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTrack<TData = Awaited<ReturnType<typeof getTrack>>, TError = ProblemDetails>(
 params?: GetTrackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTrack>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTrack>>,
          TError,
          Awaited<ReturnType<typeof getTrack>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTrack<TData = Awaited<ReturnType<typeof getTrack>>, TError = ProblemDetails>(
 params?: GetTrackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTrack>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Raw track over a time range (capped).
 */

export function useGetTrack<TData = Awaited<ReturnType<typeof getTrack>>, TError = ProblemDetails>(
 params?: GetTrackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTrack>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTrackQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getGetThinnedTrackUrl = (params?: GetThinnedTrackParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/location/track/thinned?${stringifiedParams}` : `/location/track/thinned`
}

/**
 * @summary Server-downsampled track (one best-accuracy fix per time bucket).
 */
export const getThinnedTrack = async (params?: GetThinnedTrackParams, options?: Parameters<typeof customFetchLocation>[1]): Promise<TrackPointDto[]> => {

  return customFetchLocation<TrackPointDto[]>(getGetThinnedTrackUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetThinnedTrackQueryKey = (params?: GetThinnedTrackParams,) => {
    return [
    `/location/track/thinned`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetThinnedTrackQueryOptions = <TData = Awaited<ReturnType<typeof getThinnedTrack>>, TError = ProblemDetails>(params?: GetThinnedTrackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getThinnedTrack>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetThinnedTrackQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getThinnedTrack>>> = ({ signal }) => getThinnedTrack(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getThinnedTrack>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetThinnedTrackQueryResult = NonNullable<Awaited<ReturnType<typeof getThinnedTrack>>>
export type GetThinnedTrackQueryError = ProblemDetails


export function useGetThinnedTrack<TData = Awaited<ReturnType<typeof getThinnedTrack>>, TError = ProblemDetails>(
 params: undefined |  GetThinnedTrackParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getThinnedTrack>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getThinnedTrack>>,
          TError,
          Awaited<ReturnType<typeof getThinnedTrack>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetThinnedTrack<TData = Awaited<ReturnType<typeof getThinnedTrack>>, TError = ProblemDetails>(
 params?: GetThinnedTrackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getThinnedTrack>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getThinnedTrack>>,
          TError,
          Awaited<ReturnType<typeof getThinnedTrack>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetThinnedTrack<TData = Awaited<ReturnType<typeof getThinnedTrack>>, TError = ProblemDetails>(
 params?: GetThinnedTrackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getThinnedTrack>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Server-downsampled track (one best-accuracy fix per time bucket).
 */

export function useGetThinnedTrack<TData = Awaited<ReturnType<typeof getThinnedTrack>>, TError = ProblemDetails>(
 params?: GetThinnedTrackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getThinnedTrack>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetThinnedTrackQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getGetMovementStatsUrl = (params?: GetMovementStatsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/location/stats?${stringifiedParams}` : `/location/stats`
}

/**
 * @summary Distance + speed stats over a time range.
 */
export const getMovementStats = async (params?: GetMovementStatsParams, options?: Parameters<typeof customFetchLocation>[1]): Promise<TrackStatsDto> => {

  return customFetchLocation<TrackStatsDto>(getGetMovementStatsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetMovementStatsQueryKey = (params?: GetMovementStatsParams,) => {
    return [
    `/location/stats`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetMovementStatsQueryOptions = <TData = Awaited<ReturnType<typeof getMovementStats>>, TError = ProblemDetails>(params?: GetMovementStatsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMovementStats>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMovementStatsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMovementStats>>> = ({ signal }) => getMovementStats(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMovementStats>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMovementStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getMovementStats>>>
export type GetMovementStatsQueryError = ProblemDetails


export function useGetMovementStats<TData = Awaited<ReturnType<typeof getMovementStats>>, TError = ProblemDetails>(
 params: undefined |  GetMovementStatsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMovementStats>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMovementStats>>,
          TError,
          Awaited<ReturnType<typeof getMovementStats>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMovementStats<TData = Awaited<ReturnType<typeof getMovementStats>>, TError = ProblemDetails>(
 params?: GetMovementStatsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMovementStats>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMovementStats>>,
          TError,
          Awaited<ReturnType<typeof getMovementStats>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMovementStats<TData = Awaited<ReturnType<typeof getMovementStats>>, TError = ProblemDetails>(
 params?: GetMovementStatsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMovementStats>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Distance + speed stats over a time range.
 */

export function useGetMovementStats<TData = Awaited<ReturnType<typeof getMovementStats>>, TError = ProblemDetails>(
 params?: GetMovementStatsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMovementStats>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMovementStatsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getGetBoundingBoxUrl = (params: GetBoundingBoxParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/location/bbox?${stringifiedParams}` : `/location/bbox`
}

/**
 * @summary Fixes within a lat/lon rectangle over a time range.
 */
export const getBoundingBox = async (params: GetBoundingBoxParams, options?: Parameters<typeof customFetchLocation>[1]): Promise<TrackPointDto[]> => {

  return customFetchLocation<TrackPointDto[]>(getGetBoundingBoxUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetBoundingBoxQueryKey = (params?: GetBoundingBoxParams,) => {
    return [
    `/location/bbox`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetBoundingBoxQueryOptions = <TData = Awaited<ReturnType<typeof getBoundingBox>>, TError = ProblemDetails>(params: GetBoundingBoxParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBoundingBox>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetBoundingBoxQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getBoundingBox>>> = ({ signal }) => getBoundingBox(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getBoundingBox>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetBoundingBoxQueryResult = NonNullable<Awaited<ReturnType<typeof getBoundingBox>>>
export type GetBoundingBoxQueryError = ProblemDetails


export function useGetBoundingBox<TData = Awaited<ReturnType<typeof getBoundingBox>>, TError = ProblemDetails>(
 params: GetBoundingBoxParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBoundingBox>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBoundingBox>>,
          TError,
          Awaited<ReturnType<typeof getBoundingBox>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBoundingBox<TData = Awaited<ReturnType<typeof getBoundingBox>>, TError = ProblemDetails>(
 params: GetBoundingBoxParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBoundingBox>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBoundingBox>>,
          TError,
          Awaited<ReturnType<typeof getBoundingBox>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBoundingBox<TData = Awaited<ReturnType<typeof getBoundingBox>>, TError = ProblemDetails>(
 params: GetBoundingBoxParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBoundingBox>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Fixes within a lat/lon rectangle over a time range.
 */

export function useGetBoundingBox<TData = Awaited<ReturnType<typeof getBoundingBox>>, TError = ProblemDetails>(
 params: GetBoundingBoxParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBoundingBox>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetBoundingBoxQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getGetLocationAtUrl = (params: GetLocationAtParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/location/at?${stringifiedParams}` : `/location/at`
}

/**
 * @summary Coarse place label at a time (synergy-safe — never the raw fix).
 */
export const getLocationAt = async (params: GetLocationAtParams, options?: Parameters<typeof customFetchLocation>[1]): Promise<PlaceLabelAtDto> => {

  return customFetchLocation<PlaceLabelAtDto>(getGetLocationAtUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetLocationAtQueryKey = (params?: GetLocationAtParams,) => {
    return [
    `/location/at`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetLocationAtQueryOptions = <TData = Awaited<ReturnType<typeof getLocationAt>>, TError = ProblemDetails>(params: GetLocationAtParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationAt>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLocationAtQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLocationAt>>> = ({ signal }) => getLocationAt(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLocationAt>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLocationAtQueryResult = NonNullable<Awaited<ReturnType<typeof getLocationAt>>>
export type GetLocationAtQueryError = ProblemDetails


export function useGetLocationAt<TData = Awaited<ReturnType<typeof getLocationAt>>, TError = ProblemDetails>(
 params: GetLocationAtParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationAt>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLocationAt>>,
          TError,
          Awaited<ReturnType<typeof getLocationAt>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLocationAt<TData = Awaited<ReturnType<typeof getLocationAt>>, TError = ProblemDetails>(
 params: GetLocationAtParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationAt>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLocationAt>>,
          TError,
          Awaited<ReturnType<typeof getLocationAt>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLocationAt<TData = Awaited<ReturnType<typeof getLocationAt>>, TError = ProblemDetails>(
 params: GetLocationAtParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationAt>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Coarse place label at a time (synergy-safe — never the raw fix).
 */

export function useGetLocationAt<TData = Awaited<ReturnType<typeof getLocationAt>>, TError = ProblemDetails>(
 params: GetLocationAtParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationAt>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLocationAtQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getListVisitsUrl = (params?: ListVisitsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/location/visits?${stringifiedParams}` : `/location/visits`
}

/**
 * @summary Materialized stay-points over a time range.
 */
export const listVisits = async (params?: ListVisitsParams, options?: Parameters<typeof customFetchLocation>[1]): Promise<LocationVisitDto[]> => {

  return customFetchLocation<LocationVisitDto[]>(getListVisitsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListVisitsQueryKey = (params?: ListVisitsParams,) => {
    return [
    `/location/visits`, ...(params ? [params] : [])
    ] as const;
    }


export const getListVisitsQueryOptions = <TData = Awaited<ReturnType<typeof listVisits>>, TError = ProblemDetails>(params?: ListVisitsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVisits>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListVisitsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listVisits>>> = ({ signal }) => listVisits(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listVisits>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListVisitsQueryResult = NonNullable<Awaited<ReturnType<typeof listVisits>>>
export type ListVisitsQueryError = ProblemDetails


export function useListVisits<TData = Awaited<ReturnType<typeof listVisits>>, TError = ProblemDetails>(
 params: undefined |  ListVisitsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVisits>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listVisits>>,
          TError,
          Awaited<ReturnType<typeof listVisits>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListVisits<TData = Awaited<ReturnType<typeof listVisits>>, TError = ProblemDetails>(
 params?: ListVisitsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVisits>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listVisits>>,
          TError,
          Awaited<ReturnType<typeof listVisits>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListVisits<TData = Awaited<ReturnType<typeof listVisits>>, TError = ProblemDetails>(
 params?: ListVisitsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVisits>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Materialized stay-points over a time range.
 */

export function useListVisits<TData = Awaited<ReturnType<typeof listVisits>>, TError = ProblemDetails>(
 params?: ListVisitsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVisits>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListVisitsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getListTripsUrl = (params?: ListTripsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/location/trips?${stringifiedParams}` : `/location/trips`
}

/**
 * @summary Materialized trips over a time range.
 */
export const listTrips = async (params?: ListTripsParams, options?: Parameters<typeof customFetchLocation>[1]): Promise<LocationTripDto[]> => {

  return customFetchLocation<LocationTripDto[]>(getListTripsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListTripsQueryKey = (params?: ListTripsParams,) => {
    return [
    `/location/trips`, ...(params ? [params] : [])
    ] as const;
    }


export const getListTripsQueryOptions = <TData = Awaited<ReturnType<typeof listTrips>>, TError = ProblemDetails>(params?: ListTripsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTrips>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListTripsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listTrips>>> = ({ signal }) => listTrips(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listTrips>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListTripsQueryResult = NonNullable<Awaited<ReturnType<typeof listTrips>>>
export type ListTripsQueryError = ProblemDetails


export function useListTrips<TData = Awaited<ReturnType<typeof listTrips>>, TError = ProblemDetails>(
 params: undefined |  ListTripsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTrips>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTrips>>,
          TError,
          Awaited<ReturnType<typeof listTrips>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTrips<TData = Awaited<ReturnType<typeof listTrips>>, TError = ProblemDetails>(
 params?: ListTripsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTrips>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTrips>>,
          TError,
          Awaited<ReturnType<typeof listTrips>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTrips<TData = Awaited<ReturnType<typeof listTrips>>, TError = ProblemDetails>(
 params?: ListTripsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTrips>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Materialized trips over a time range.
 */

export function useListTrips<TData = Awaited<ReturnType<typeof listTrips>>, TError = ProblemDetails>(
 params?: ListTripsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTrips>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListTripsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getGetDailySummaryUrl = (params: GetDailySummaryParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/location/summary?${stringifiedParams}` : `/location/summary`
}

/**
 * @summary Per-day location rollup.
 */
export const getDailySummary = async (params: GetDailySummaryParams, options?: Parameters<typeof customFetchLocation>[1]): Promise<DailyLocationSummaryDto> => {

  return customFetchLocation<DailyLocationSummaryDto>(getGetDailySummaryUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetDailySummaryQueryKey = (params?: GetDailySummaryParams,) => {
    return [
    `/location/summary`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetDailySummaryQueryOptions = <TData = Awaited<ReturnType<typeof getDailySummary>>, TError = ProblemDetails>(params: GetDailySummaryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDailySummary>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDailySummaryQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDailySummary>>> = ({ signal }) => getDailySummary(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDailySummary>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDailySummaryQueryResult = NonNullable<Awaited<ReturnType<typeof getDailySummary>>>
export type GetDailySummaryQueryError = ProblemDetails


export function useGetDailySummary<TData = Awaited<ReturnType<typeof getDailySummary>>, TError = ProblemDetails>(
 params: GetDailySummaryParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDailySummary>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDailySummary>>,
          TError,
          Awaited<ReturnType<typeof getDailySummary>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDailySummary<TData = Awaited<ReturnType<typeof getDailySummary>>, TError = ProblemDetails>(
 params: GetDailySummaryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDailySummary>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDailySummary>>,
          TError,
          Awaited<ReturnType<typeof getDailySummary>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDailySummary<TData = Awaited<ReturnType<typeof getDailySummary>>, TError = ProblemDetails>(
 params: GetDailySummaryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDailySummary>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Per-day location rollup.
 */

export function useGetDailySummary<TData = Awaited<ReturnType<typeof getDailySummary>>, TError = ProblemDetails>(
 params: GetDailySummaryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDailySummary>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDailySummaryQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getPurgeLocationHistoryUrl = (params?: PurgeLocationHistoryParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/location?${stringifiedParams}` : `/location`
}

/**
 * @summary Purge raw fixes + derived docs in a time range (owner erase).
 */
export const purgeLocationHistory = async (params?: PurgeLocationHistoryParams, options?: Parameters<typeof customFetchLocation>[1]): Promise<void> => {

  return customFetchLocation<void>(getPurgeLocationHistoryUrl(params),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getPurgeLocationHistoryMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof purgeLocationHistory>>, TError,{params?: PurgeLocationHistoryParams}, TContext>, request?: SecondParameter<typeof customFetchLocation>}
): UseMutationOptions<Awaited<ReturnType<typeof purgeLocationHistory>>, TError,{params?: PurgeLocationHistoryParams}, TContext> => {

const mutationKey = ['purgeLocationHistory'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof purgeLocationHistory>>, {params?: PurgeLocationHistoryParams}> = (props) => {
          const {params} = props ?? {};

          return  purgeLocationHistory(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PurgeLocationHistoryMutationResult = NonNullable<Awaited<ReturnType<typeof purgeLocationHistory>>>

    export type PurgeLocationHistoryMutationError = ProblemDetails

    /**
 * @summary Purge raw fixes + derived docs in a time range (owner erase).
 */
export const usePurgeLocationHistory = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof purgeLocationHistory>>, TError,{params?: PurgeLocationHistoryParams}, TContext>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof purgeLocationHistory>>,
        TError,
        {params?: PurgeLocationHistoryParams},
        TContext
      > => {
      return useMutation(getPurgeLocationHistoryMutationOptions(options), queryClient);
    }

export const getPauseTrackingUrl = (deviceId: string,) => {




  return `/location/tracking/${deviceId}/pause`
}

/**
 * @summary Pause tracking for a device (ingest is discarded while paused).
 */
export const pauseTracking = async (deviceId: string,
    nullPauseTrackingRequest?: null | PauseTrackingRequest, options?: Parameters<typeof customFetchLocation>[1]): Promise<void> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetchLocation<void>(getPauseTrackingUrl(deviceId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(nullPauseTrackingRequest)
  }
);}





export const getPauseTrackingMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof pauseTracking>>, TError,{deviceId: string;data?: null | PauseTrackingRequest}, TContext>, request?: SecondParameter<typeof customFetchLocation>}
): UseMutationOptions<Awaited<ReturnType<typeof pauseTracking>>, TError,{deviceId: string;data?: null | PauseTrackingRequest}, TContext> => {

const mutationKey = ['pauseTracking'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof pauseTracking>>, {deviceId: string;data?: null | PauseTrackingRequest}> = (props) => {
          const {deviceId,data} = props ?? {};

          return  pauseTracking(deviceId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PauseTrackingMutationResult = NonNullable<Awaited<ReturnType<typeof pauseTracking>>>
    export type PauseTrackingMutationBody = null | PauseTrackingRequest | undefined
    export type PauseTrackingMutationError = ProblemDetails

    /**
 * @summary Pause tracking for a device (ingest is discarded while paused).
 */
export const usePauseTracking = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof pauseTracking>>, TError,{deviceId: string;data?: null | PauseTrackingRequest}, TContext>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof pauseTracking>>,
        TError,
        {deviceId: string;data?: null | PauseTrackingRequest},
        TContext
      > => {
      return useMutation(getPauseTrackingMutationOptions(options), queryClient);
    }

export const getResumeTrackingUrl = (deviceId: string,) => {




  return `/location/tracking/${deviceId}/resume`
}

/**
 * @summary Resume tracking for a device.
 */
export const resumeTracking = async (deviceId: string, options?: Parameters<typeof customFetchLocation>[1]): Promise<void> => {

  return customFetchLocation<void>(getResumeTrackingUrl(deviceId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getResumeTrackingMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resumeTracking>>, TError,{deviceId: string}, TContext>, request?: SecondParameter<typeof customFetchLocation>}
): UseMutationOptions<Awaited<ReturnType<typeof resumeTracking>>, TError,{deviceId: string}, TContext> => {

const mutationKey = ['resumeTracking'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof resumeTracking>>, {deviceId: string}> = (props) => {
          const {deviceId} = props ?? {};

          return  resumeTracking(deviceId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ResumeTrackingMutationResult = NonNullable<Awaited<ReturnType<typeof resumeTracking>>>

    export type ResumeTrackingMutationError = ProblemDetails

    /**
 * @summary Resume tracking for a device.
 */
export const useResumeTracking = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resumeTracking>>, TError,{deviceId: string}, TContext>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof resumeTracking>>,
        TError,
        {deviceId: string},
        TContext
      > => {
      return useMutation(getResumeTrackingMutationOptions(options), queryClient);
    }

export const getGetTrackingStateUrl = (deviceId: string,) => {




  return `/location/tracking/${deviceId}/state`
}

/**
 * @summary Tracking state for a device.
 */
export const getTrackingState = async (deviceId: string, options?: Parameters<typeof customFetchLocation>[1]): Promise<TrackingStateDto> => {

  return customFetchLocation<TrackingStateDto>(getGetTrackingStateUrl(deviceId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetTrackingStateQueryKey = (deviceId: string,) => {
    return [
    `/location/tracking/${deviceId}/state`
    ] as const;
    }


export const getGetTrackingStateQueryOptions = <TData = Awaited<ReturnType<typeof getTrackingState>>, TError = ProblemDetails>(deviceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTrackingState>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTrackingStateQueryKey(deviceId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTrackingState>>> = ({ signal }) => getTrackingState(deviceId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: deviceId !== null && deviceId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTrackingState>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTrackingStateQueryResult = NonNullable<Awaited<ReturnType<typeof getTrackingState>>>
export type GetTrackingStateQueryError = ProblemDetails


export function useGetTrackingState<TData = Awaited<ReturnType<typeof getTrackingState>>, TError = ProblemDetails>(
 deviceId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTrackingState>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTrackingState>>,
          TError,
          Awaited<ReturnType<typeof getTrackingState>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTrackingState<TData = Awaited<ReturnType<typeof getTrackingState>>, TError = ProblemDetails>(
 deviceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTrackingState>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTrackingState>>,
          TError,
          Awaited<ReturnType<typeof getTrackingState>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTrackingState<TData = Awaited<ReturnType<typeof getTrackingState>>, TError = ProblemDetails>(
 deviceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTrackingState>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Tracking state for a device.
 */

export function useGetTrackingState<TData = Awaited<ReturnType<typeof getTrackingState>>, TError = ProblemDetails>(
 deviceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTrackingState>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTrackingStateQueryOptions(deviceId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
