/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lupira Location API
 * Location and presence backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CurrentFixDto,
  DailyLocationSummaryDto,
  DeleteLocationParams,
  DeviceDto,
  GetLocationAtParams,
  GetLocationBboxParams,
  GetLocationCurrentParams,
  GetLocationStatsParams,
  GetLocationSummaryParams,
  GetLocationTrackParams,
  GetLocationTrackThinnedParams,
  GetLocationTripsParams,
  GetLocationVisitsParams,
  LocationCursor,
  LocationIngestReceipt,
  LocationTripDto,
  LocationVisitDto,
  MeDto,
  PauseTrackingRequest,
  PlaceLabelAtDto,
  ProblemDetails,
  RegisterDeviceRequest,
  RegisterDeviceResponse,
  RenameDeviceRequest,
  TrackPointDto,
  TrackStatsDto,
  TrackingStateDto
} from './models';

import { customFetchLocation } from '../fetcher';
type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetMeUrl = () => {




  return `/me`
}

/**
 * @summary The caller's resolved local identity (JIT-provisioned on first login).
 */
export const getMe = async ( options?: Parameters<typeof customFetchLocation>[1]): Promise<MeDto> => {

  return customFetchLocation<MeDto>(getGetMeUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetMeQueryKey = () => {
    return [
    `/me`
    ] as const;
    }


export const getGetMeQueryOptions = <TData = Awaited<ReturnType<typeof getMe>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMe>>> = ({ signal }) => getMe({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMeQueryResult = NonNullable<Awaited<ReturnType<typeof getMe>>>
export type GetMeQueryError = void


export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMe>>,
          TError,
          Awaited<ReturnType<typeof getMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMe>>,
          TError,
          Awaited<ReturnType<typeof getMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary The caller's resolved local identity (JIT-provisioned on first login).
 */

export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getGetDevicesUrl = () => {




  return `/devices`
}

/**
 * @summary List the caller's registered location-tracking devices.
 */
export const getDevices = async ( options?: Parameters<typeof customFetchLocation>[1]): Promise<DeviceDto[]> => {

  return customFetchLocation<DeviceDto[]>(getGetDevicesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetDevicesQueryKey = () => {
    return [
    `/devices`
    ] as const;
    }


export const getGetDevicesQueryOptions = <TData = Awaited<ReturnType<typeof getDevices>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDevices>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDevicesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDevices>>> = ({ signal }) => getDevices({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDevices>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDevicesQueryResult = NonNullable<Awaited<ReturnType<typeof getDevices>>>
export type GetDevicesQueryError = void


export function useGetDevices<TData = Awaited<ReturnType<typeof getDevices>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDevices>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDevices>>,
          TError,
          Awaited<ReturnType<typeof getDevices>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDevices<TData = Awaited<ReturnType<typeof getDevices>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDevices>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDevices>>,
          TError,
          Awaited<ReturnType<typeof getDevices>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDevices<TData = Awaited<ReturnType<typeof getDevices>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDevices>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List the caller's registered location-tracking devices.
 */

export function useGetDevices<TData = Awaited<ReturnType<typeof getDevices>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDevices>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDevicesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getPostDevicesUrl = () => {




  return `/devices`
}

/**
 * @summary Register a device; returns the one-time ingest API key.
 */
export const postDevices = async (registerDeviceRequest: RegisterDeviceRequest, options?: Parameters<typeof customFetchLocation>[1]): Promise<RegisterDeviceResponse> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetchLocation<RegisterDeviceResponse>(getPostDevicesUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(registerDeviceRequest)
  }
);}





export const getPostDevicesMutationOptions = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postDevices>>, TError,{data: RegisterDeviceRequest}, TContext>, request?: SecondParameter<typeof customFetchLocation>}
): UseMutationOptions<Awaited<ReturnType<typeof postDevices>>, TError,{data: RegisterDeviceRequest}, TContext> => {

const mutationKey = ['postDevices'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postDevices>>, {data: RegisterDeviceRequest}> = (props) => {
          const {data} = props ?? {};

          return  postDevices(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostDevicesMutationResult = NonNullable<Awaited<ReturnType<typeof postDevices>>>
    export type PostDevicesMutationBody = RegisterDeviceRequest
    export type PostDevicesMutationError = ProblemDetails | void

    /**
 * @summary Register a device; returns the one-time ingest API key.
 */
export const usePostDevices = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postDevices>>, TError,{data: RegisterDeviceRequest}, TContext>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postDevices>>,
        TError,
        {data: RegisterDeviceRequest},
        TContext
      > => {
      return useMutation(getPostDevicesMutationOptions(options), queryClient);
    }

export const getPutDevicesIdUrl = (id: string,) => {




  return `/devices/${id}`
}

/**
 * @summary Rename a device.
 */
export const putDevicesId = async (id: string,
    renameDeviceRequest: RenameDeviceRequest, options?: Parameters<typeof customFetchLocation>[1]): Promise<DeviceDto> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetchLocation<DeviceDto>(getPutDevicesIdUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(renameDeviceRequest)
  }
);}





export const getPutDevicesIdMutationOptions = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putDevicesId>>, TError,{id: string;data: RenameDeviceRequest}, TContext>, request?: SecondParameter<typeof customFetchLocation>}
): UseMutationOptions<Awaited<ReturnType<typeof putDevicesId>>, TError,{id: string;data: RenameDeviceRequest}, TContext> => {

const mutationKey = ['putDevicesId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putDevicesId>>, {id: string;data: RenameDeviceRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  putDevicesId(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutDevicesIdMutationResult = NonNullable<Awaited<ReturnType<typeof putDevicesId>>>
    export type PutDevicesIdMutationBody = RenameDeviceRequest
    export type PutDevicesIdMutationError = ProblemDetails | void

    /**
 * @summary Rename a device.
 */
export const usePutDevicesId = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putDevicesId>>, TError,{id: string;data: RenameDeviceRequest}, TContext>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putDevicesId>>,
        TError,
        {id: string;data: RenameDeviceRequest},
        TContext
      > => {
      return useMutation(getPutDevicesIdMutationOptions(options), queryClient);
    }

export const getDeleteDevicesIdUrl = (id: string,) => {




  return `/devices/${id}`
}

/**
 * @summary Retire a device (revokes its ingest keys).
 */
export const deleteDevicesId = async (id: string, options?: Parameters<typeof customFetchLocation>[1]): Promise<void> => {

  return customFetchLocation<void>(getDeleteDevicesIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteDevicesIdMutationOptions = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDevicesId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetchLocation>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteDevicesId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteDevicesId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteDevicesId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteDevicesId(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteDevicesIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteDevicesId>>>

    export type DeleteDevicesIdMutationError = ProblemDetails | void

    /**
 * @summary Retire a device (revokes its ingest keys).
 */
export const useDeleteDevicesId = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDevicesId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteDevicesId>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteDevicesIdMutationOptions(options), queryClient);
    }

export const getPostIngestLocationUrl = () => {




  return `/ingest/location`
}

/**
 * @summary Ingest a batch of GPS fixes (NDJSON, one fix per line).
 */
export const postIngestLocation = async (postIngestLocationBody: string, options?: Parameters<typeof customFetchLocation>[1]): Promise<LocationIngestReceipt> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetchLocation<LocationIngestReceipt>(getPostIngestLocationUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/x-ndjson', ...getHeaders(options?.headers) },
    body: JSON.stringify(postIngestLocationBody)
  }
);}





export const getPostIngestLocationMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postIngestLocation>>, TError,{data: string}, TContext>, request?: SecondParameter<typeof customFetchLocation>}
): UseMutationOptions<Awaited<ReturnType<typeof postIngestLocation>>, TError,{data: string}, TContext> => {

const mutationKey = ['postIngestLocation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postIngestLocation>>, {data: string}> = (props) => {
          const {data} = props ?? {};

          return  postIngestLocation(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostIngestLocationMutationResult = NonNullable<Awaited<ReturnType<typeof postIngestLocation>>>
    export type PostIngestLocationMutationBody = string
    export type PostIngestLocationMutationError = unknown

    /**
 * @summary Ingest a batch of GPS fixes (NDJSON, one fix per line).
 */
export const usePostIngestLocation = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postIngestLocation>>, TError,{data: string}, TContext>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postIngestLocation>>,
        TError,
        {data: string},
        TContext
      > => {
      return useMutation(getPostIngestLocationMutationOptions(options), queryClient);
    }

export const getGetIngestLocationCursorUrl = () => {




  return `/ingest/location/cursor`
}

/**
 * @summary The device's resume cursor (last accepted seq + ts).
 */
export const getIngestLocationCursor = async ( options?: Parameters<typeof customFetchLocation>[1]): Promise<LocationCursor> => {

  return customFetchLocation<LocationCursor>(getGetIngestLocationCursorUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetIngestLocationCursorQueryKey = () => {
    return [
    `/ingest/location/cursor`
    ] as const;
    }


export const getGetIngestLocationCursorQueryOptions = <TData = Awaited<ReturnType<typeof getIngestLocationCursor>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIngestLocationCursor>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetIngestLocationCursorQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getIngestLocationCursor>>> = ({ signal }) => getIngestLocationCursor({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getIngestLocationCursor>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetIngestLocationCursorQueryResult = NonNullable<Awaited<ReturnType<typeof getIngestLocationCursor>>>
export type GetIngestLocationCursorQueryError = unknown


export function useGetIngestLocationCursor<TData = Awaited<ReturnType<typeof getIngestLocationCursor>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIngestLocationCursor>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIngestLocationCursor>>,
          TError,
          Awaited<ReturnType<typeof getIngestLocationCursor>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetIngestLocationCursor<TData = Awaited<ReturnType<typeof getIngestLocationCursor>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIngestLocationCursor>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIngestLocationCursor>>,
          TError,
          Awaited<ReturnType<typeof getIngestLocationCursor>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetIngestLocationCursor<TData = Awaited<ReturnType<typeof getIngestLocationCursor>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIngestLocationCursor>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary The device's resume cursor (last accepted seq + ts).
 */

export function useGetIngestLocationCursor<TData = Awaited<ReturnType<typeof getIngestLocationCursor>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIngestLocationCursor>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetIngestLocationCursorQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getGetIngestLocationStateUrl = () => {




  return `/ingest/location/state`
}

/**
 * @summary Whether tracking is paused for this device (the uploader should stop collecting if so).
 */
export const getIngestLocationState = async ( options?: Parameters<typeof customFetchLocation>[1]): Promise<TrackingStateDto> => {

  return customFetchLocation<TrackingStateDto>(getGetIngestLocationStateUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetIngestLocationStateQueryKey = () => {
    return [
    `/ingest/location/state`
    ] as const;
    }


export const getGetIngestLocationStateQueryOptions = <TData = Awaited<ReturnType<typeof getIngestLocationState>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIngestLocationState>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetIngestLocationStateQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getIngestLocationState>>> = ({ signal }) => getIngestLocationState({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getIngestLocationState>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetIngestLocationStateQueryResult = NonNullable<Awaited<ReturnType<typeof getIngestLocationState>>>
export type GetIngestLocationStateQueryError = unknown


export function useGetIngestLocationState<TData = Awaited<ReturnType<typeof getIngestLocationState>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIngestLocationState>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIngestLocationState>>,
          TError,
          Awaited<ReturnType<typeof getIngestLocationState>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetIngestLocationState<TData = Awaited<ReturnType<typeof getIngestLocationState>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIngestLocationState>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIngestLocationState>>,
          TError,
          Awaited<ReturnType<typeof getIngestLocationState>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetIngestLocationState<TData = Awaited<ReturnType<typeof getIngestLocationState>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIngestLocationState>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Whether tracking is paused for this device (the uploader should stop collecting if so).
 */

export function useGetIngestLocationState<TData = Awaited<ReturnType<typeof getIngestLocationState>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIngestLocationState>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetIngestLocationStateQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getGetLocationCurrentUrl = (params?: GetLocationCurrentParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/location/current?${stringifiedParams}` : `/location/current`
}

/**
 * @summary Latest known location per device.
 */
export const getLocationCurrent = async (params?: GetLocationCurrentParams, options?: Parameters<typeof customFetchLocation>[1]): Promise<CurrentFixDto[]> => {

  return customFetchLocation<CurrentFixDto[]>(getGetLocationCurrentUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetLocationCurrentQueryKey = (params?: GetLocationCurrentParams,) => {
    return [
    `/location/current`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetLocationCurrentQueryOptions = <TData = Awaited<ReturnType<typeof getLocationCurrent>>, TError = unknown>(params?: GetLocationCurrentParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationCurrent>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLocationCurrentQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLocationCurrent>>> = ({ signal }) => getLocationCurrent(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLocationCurrent>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLocationCurrentQueryResult = NonNullable<Awaited<ReturnType<typeof getLocationCurrent>>>
export type GetLocationCurrentQueryError = unknown


export function useGetLocationCurrent<TData = Awaited<ReturnType<typeof getLocationCurrent>>, TError = unknown>(
 params: undefined |  GetLocationCurrentParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationCurrent>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLocationCurrent>>,
          TError,
          Awaited<ReturnType<typeof getLocationCurrent>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLocationCurrent<TData = Awaited<ReturnType<typeof getLocationCurrent>>, TError = unknown>(
 params?: GetLocationCurrentParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationCurrent>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLocationCurrent>>,
          TError,
          Awaited<ReturnType<typeof getLocationCurrent>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLocationCurrent<TData = Awaited<ReturnType<typeof getLocationCurrent>>, TError = unknown>(
 params?: GetLocationCurrentParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationCurrent>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Latest known location per device.
 */

export function useGetLocationCurrent<TData = Awaited<ReturnType<typeof getLocationCurrent>>, TError = unknown>(
 params?: GetLocationCurrentParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationCurrent>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLocationCurrentQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getGetLocationTrackUrl = (params?: GetLocationTrackParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/location/track?${stringifiedParams}` : `/location/track`
}

/**
 * @summary Raw track over a time range (capped).
 */
export const getLocationTrack = async (params?: GetLocationTrackParams, options?: Parameters<typeof customFetchLocation>[1]): Promise<TrackPointDto[]> => {

  return customFetchLocation<TrackPointDto[]>(getGetLocationTrackUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetLocationTrackQueryKey = (params?: GetLocationTrackParams,) => {
    return [
    `/location/track`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetLocationTrackQueryOptions = <TData = Awaited<ReturnType<typeof getLocationTrack>>, TError = unknown>(params?: GetLocationTrackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationTrack>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLocationTrackQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLocationTrack>>> = ({ signal }) => getLocationTrack(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLocationTrack>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLocationTrackQueryResult = NonNullable<Awaited<ReturnType<typeof getLocationTrack>>>
export type GetLocationTrackQueryError = unknown


export function useGetLocationTrack<TData = Awaited<ReturnType<typeof getLocationTrack>>, TError = unknown>(
 params: undefined |  GetLocationTrackParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationTrack>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLocationTrack>>,
          TError,
          Awaited<ReturnType<typeof getLocationTrack>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLocationTrack<TData = Awaited<ReturnType<typeof getLocationTrack>>, TError = unknown>(
 params?: GetLocationTrackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationTrack>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLocationTrack>>,
          TError,
          Awaited<ReturnType<typeof getLocationTrack>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLocationTrack<TData = Awaited<ReturnType<typeof getLocationTrack>>, TError = unknown>(
 params?: GetLocationTrackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationTrack>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Raw track over a time range (capped).
 */

export function useGetLocationTrack<TData = Awaited<ReturnType<typeof getLocationTrack>>, TError = unknown>(
 params?: GetLocationTrackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationTrack>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLocationTrackQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getGetLocationTrackThinnedUrl = (params?: GetLocationTrackThinnedParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/location/track/thinned?${stringifiedParams}` : `/location/track/thinned`
}

/**
 * @summary Server-downsampled track (one best-accuracy fix per time bucket).
 */
export const getLocationTrackThinned = async (params?: GetLocationTrackThinnedParams, options?: Parameters<typeof customFetchLocation>[1]): Promise<TrackPointDto[]> => {

  return customFetchLocation<TrackPointDto[]>(getGetLocationTrackThinnedUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetLocationTrackThinnedQueryKey = (params?: GetLocationTrackThinnedParams,) => {
    return [
    `/location/track/thinned`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetLocationTrackThinnedQueryOptions = <TData = Awaited<ReturnType<typeof getLocationTrackThinned>>, TError = unknown>(params?: GetLocationTrackThinnedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationTrackThinned>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLocationTrackThinnedQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLocationTrackThinned>>> = ({ signal }) => getLocationTrackThinned(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLocationTrackThinned>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLocationTrackThinnedQueryResult = NonNullable<Awaited<ReturnType<typeof getLocationTrackThinned>>>
export type GetLocationTrackThinnedQueryError = unknown


export function useGetLocationTrackThinned<TData = Awaited<ReturnType<typeof getLocationTrackThinned>>, TError = unknown>(
 params: undefined |  GetLocationTrackThinnedParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationTrackThinned>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLocationTrackThinned>>,
          TError,
          Awaited<ReturnType<typeof getLocationTrackThinned>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLocationTrackThinned<TData = Awaited<ReturnType<typeof getLocationTrackThinned>>, TError = unknown>(
 params?: GetLocationTrackThinnedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationTrackThinned>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLocationTrackThinned>>,
          TError,
          Awaited<ReturnType<typeof getLocationTrackThinned>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLocationTrackThinned<TData = Awaited<ReturnType<typeof getLocationTrackThinned>>, TError = unknown>(
 params?: GetLocationTrackThinnedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationTrackThinned>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Server-downsampled track (one best-accuracy fix per time bucket).
 */

export function useGetLocationTrackThinned<TData = Awaited<ReturnType<typeof getLocationTrackThinned>>, TError = unknown>(
 params?: GetLocationTrackThinnedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationTrackThinned>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLocationTrackThinnedQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getGetLocationStatsUrl = (params?: GetLocationStatsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/location/stats?${stringifiedParams}` : `/location/stats`
}

/**
 * @summary Distance + speed stats over a time range.
 */
export const getLocationStats = async (params?: GetLocationStatsParams, options?: Parameters<typeof customFetchLocation>[1]): Promise<TrackStatsDto> => {

  return customFetchLocation<TrackStatsDto>(getGetLocationStatsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetLocationStatsQueryKey = (params?: GetLocationStatsParams,) => {
    return [
    `/location/stats`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetLocationStatsQueryOptions = <TData = Awaited<ReturnType<typeof getLocationStats>>, TError = unknown>(params?: GetLocationStatsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationStats>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLocationStatsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLocationStats>>> = ({ signal }) => getLocationStats(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLocationStats>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLocationStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getLocationStats>>>
export type GetLocationStatsQueryError = unknown


export function useGetLocationStats<TData = Awaited<ReturnType<typeof getLocationStats>>, TError = unknown>(
 params: undefined |  GetLocationStatsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationStats>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLocationStats>>,
          TError,
          Awaited<ReturnType<typeof getLocationStats>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLocationStats<TData = Awaited<ReturnType<typeof getLocationStats>>, TError = unknown>(
 params?: GetLocationStatsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationStats>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLocationStats>>,
          TError,
          Awaited<ReturnType<typeof getLocationStats>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLocationStats<TData = Awaited<ReturnType<typeof getLocationStats>>, TError = unknown>(
 params?: GetLocationStatsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationStats>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Distance + speed stats over a time range.
 */

export function useGetLocationStats<TData = Awaited<ReturnType<typeof getLocationStats>>, TError = unknown>(
 params?: GetLocationStatsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationStats>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLocationStatsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getGetLocationBboxUrl = (params: GetLocationBboxParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/location/bbox?${stringifiedParams}` : `/location/bbox`
}

/**
 * @summary Fixes within a lat/lon rectangle over a time range.
 */
export const getLocationBbox = async (params: GetLocationBboxParams, options?: Parameters<typeof customFetchLocation>[1]): Promise<TrackPointDto[]> => {

  return customFetchLocation<TrackPointDto[]>(getGetLocationBboxUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetLocationBboxQueryKey = (params?: GetLocationBboxParams,) => {
    return [
    `/location/bbox`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetLocationBboxQueryOptions = <TData = Awaited<ReturnType<typeof getLocationBbox>>, TError = unknown>(params: GetLocationBboxParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationBbox>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLocationBboxQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLocationBbox>>> = ({ signal }) => getLocationBbox(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLocationBbox>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLocationBboxQueryResult = NonNullable<Awaited<ReturnType<typeof getLocationBbox>>>
export type GetLocationBboxQueryError = unknown


export function useGetLocationBbox<TData = Awaited<ReturnType<typeof getLocationBbox>>, TError = unknown>(
 params: GetLocationBboxParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationBbox>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLocationBbox>>,
          TError,
          Awaited<ReturnType<typeof getLocationBbox>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLocationBbox<TData = Awaited<ReturnType<typeof getLocationBbox>>, TError = unknown>(
 params: GetLocationBboxParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationBbox>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLocationBbox>>,
          TError,
          Awaited<ReturnType<typeof getLocationBbox>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLocationBbox<TData = Awaited<ReturnType<typeof getLocationBbox>>, TError = unknown>(
 params: GetLocationBboxParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationBbox>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Fixes within a lat/lon rectangle over a time range.
 */

export function useGetLocationBbox<TData = Awaited<ReturnType<typeof getLocationBbox>>, TError = unknown>(
 params: GetLocationBboxParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationBbox>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLocationBboxQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getGetLocationAtUrl = (params: GetLocationAtParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/location/at?${stringifiedParams}` : `/location/at`
}

/**
 * @summary Coarse place label at a time (synergy-safe — never the raw fix).
 */
export const getLocationAt = async (params: GetLocationAtParams, options?: Parameters<typeof customFetchLocation>[1]): Promise<PlaceLabelAtDto> => {

  return customFetchLocation<PlaceLabelAtDto>(getGetLocationAtUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetLocationAtQueryKey = (params?: GetLocationAtParams,) => {
    return [
    `/location/at`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetLocationAtQueryOptions = <TData = Awaited<ReturnType<typeof getLocationAt>>, TError = unknown>(params: GetLocationAtParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationAt>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLocationAtQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLocationAt>>> = ({ signal }) => getLocationAt(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLocationAt>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLocationAtQueryResult = NonNullable<Awaited<ReturnType<typeof getLocationAt>>>
export type GetLocationAtQueryError = unknown


export function useGetLocationAt<TData = Awaited<ReturnType<typeof getLocationAt>>, TError = unknown>(
 params: GetLocationAtParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationAt>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLocationAt>>,
          TError,
          Awaited<ReturnType<typeof getLocationAt>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLocationAt<TData = Awaited<ReturnType<typeof getLocationAt>>, TError = unknown>(
 params: GetLocationAtParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationAt>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLocationAt>>,
          TError,
          Awaited<ReturnType<typeof getLocationAt>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLocationAt<TData = Awaited<ReturnType<typeof getLocationAt>>, TError = unknown>(
 params: GetLocationAtParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationAt>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Coarse place label at a time (synergy-safe — never the raw fix).
 */

export function useGetLocationAt<TData = Awaited<ReturnType<typeof getLocationAt>>, TError = unknown>(
 params: GetLocationAtParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationAt>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLocationAtQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getGetLocationVisitsUrl = (params?: GetLocationVisitsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/location/visits?${stringifiedParams}` : `/location/visits`
}

/**
 * @summary Materialized stay-points over a time range.
 */
export const getLocationVisits = async (params?: GetLocationVisitsParams, options?: Parameters<typeof customFetchLocation>[1]): Promise<LocationVisitDto[]> => {

  return customFetchLocation<LocationVisitDto[]>(getGetLocationVisitsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetLocationVisitsQueryKey = (params?: GetLocationVisitsParams,) => {
    return [
    `/location/visits`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetLocationVisitsQueryOptions = <TData = Awaited<ReturnType<typeof getLocationVisits>>, TError = unknown>(params?: GetLocationVisitsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationVisits>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLocationVisitsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLocationVisits>>> = ({ signal }) => getLocationVisits(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLocationVisits>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLocationVisitsQueryResult = NonNullable<Awaited<ReturnType<typeof getLocationVisits>>>
export type GetLocationVisitsQueryError = unknown


export function useGetLocationVisits<TData = Awaited<ReturnType<typeof getLocationVisits>>, TError = unknown>(
 params: undefined |  GetLocationVisitsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationVisits>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLocationVisits>>,
          TError,
          Awaited<ReturnType<typeof getLocationVisits>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLocationVisits<TData = Awaited<ReturnType<typeof getLocationVisits>>, TError = unknown>(
 params?: GetLocationVisitsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationVisits>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLocationVisits>>,
          TError,
          Awaited<ReturnType<typeof getLocationVisits>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLocationVisits<TData = Awaited<ReturnType<typeof getLocationVisits>>, TError = unknown>(
 params?: GetLocationVisitsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationVisits>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Materialized stay-points over a time range.
 */

export function useGetLocationVisits<TData = Awaited<ReturnType<typeof getLocationVisits>>, TError = unknown>(
 params?: GetLocationVisitsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationVisits>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLocationVisitsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getGetLocationTripsUrl = (params?: GetLocationTripsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/location/trips?${stringifiedParams}` : `/location/trips`
}

/**
 * @summary Materialized trips over a time range.
 */
export const getLocationTrips = async (params?: GetLocationTripsParams, options?: Parameters<typeof customFetchLocation>[1]): Promise<LocationTripDto[]> => {

  return customFetchLocation<LocationTripDto[]>(getGetLocationTripsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetLocationTripsQueryKey = (params?: GetLocationTripsParams,) => {
    return [
    `/location/trips`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetLocationTripsQueryOptions = <TData = Awaited<ReturnType<typeof getLocationTrips>>, TError = unknown>(params?: GetLocationTripsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationTrips>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLocationTripsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLocationTrips>>> = ({ signal }) => getLocationTrips(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLocationTrips>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLocationTripsQueryResult = NonNullable<Awaited<ReturnType<typeof getLocationTrips>>>
export type GetLocationTripsQueryError = unknown


export function useGetLocationTrips<TData = Awaited<ReturnType<typeof getLocationTrips>>, TError = unknown>(
 params: undefined |  GetLocationTripsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationTrips>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLocationTrips>>,
          TError,
          Awaited<ReturnType<typeof getLocationTrips>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLocationTrips<TData = Awaited<ReturnType<typeof getLocationTrips>>, TError = unknown>(
 params?: GetLocationTripsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationTrips>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLocationTrips>>,
          TError,
          Awaited<ReturnType<typeof getLocationTrips>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLocationTrips<TData = Awaited<ReturnType<typeof getLocationTrips>>, TError = unknown>(
 params?: GetLocationTripsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationTrips>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Materialized trips over a time range.
 */

export function useGetLocationTrips<TData = Awaited<ReturnType<typeof getLocationTrips>>, TError = unknown>(
 params?: GetLocationTripsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationTrips>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLocationTripsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getGetLocationSummaryUrl = (params: GetLocationSummaryParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/location/summary?${stringifiedParams}` : `/location/summary`
}

/**
 * @summary Per-day location rollup.
 */
export const getLocationSummary = async (params: GetLocationSummaryParams, options?: Parameters<typeof customFetchLocation>[1]): Promise<DailyLocationSummaryDto> => {

  return customFetchLocation<DailyLocationSummaryDto>(getGetLocationSummaryUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetLocationSummaryQueryKey = (params?: GetLocationSummaryParams,) => {
    return [
    `/location/summary`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetLocationSummaryQueryOptions = <TData = Awaited<ReturnType<typeof getLocationSummary>>, TError = unknown>(params: GetLocationSummaryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationSummary>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLocationSummaryQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLocationSummary>>> = ({ signal }) => getLocationSummary(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLocationSummary>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLocationSummaryQueryResult = NonNullable<Awaited<ReturnType<typeof getLocationSummary>>>
export type GetLocationSummaryQueryError = unknown


export function useGetLocationSummary<TData = Awaited<ReturnType<typeof getLocationSummary>>, TError = unknown>(
 params: GetLocationSummaryParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationSummary>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLocationSummary>>,
          TError,
          Awaited<ReturnType<typeof getLocationSummary>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLocationSummary<TData = Awaited<ReturnType<typeof getLocationSummary>>, TError = unknown>(
 params: GetLocationSummaryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationSummary>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLocationSummary>>,
          TError,
          Awaited<ReturnType<typeof getLocationSummary>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLocationSummary<TData = Awaited<ReturnType<typeof getLocationSummary>>, TError = unknown>(
 params: GetLocationSummaryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationSummary>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Per-day location rollup.
 */

export function useGetLocationSummary<TData = Awaited<ReturnType<typeof getLocationSummary>>, TError = unknown>(
 params: GetLocationSummaryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationSummary>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLocationSummaryQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getDeleteLocationUrl = (params?: DeleteLocationParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/location?${stringifiedParams}` : `/location`
}

/**
 * @summary Purge raw fixes + derived docs in a time range (owner erase).
 */
export const deleteLocation = async (params?: DeleteLocationParams, options?: Parameters<typeof customFetchLocation>[1]): Promise<void> => {

  return customFetchLocation<void>(getDeleteLocationUrl(params),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteLocationMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteLocation>>, TError,{params?: DeleteLocationParams}, TContext>, request?: SecondParameter<typeof customFetchLocation>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteLocation>>, TError,{params?: DeleteLocationParams}, TContext> => {

const mutationKey = ['deleteLocation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteLocation>>, {params?: DeleteLocationParams}> = (props) => {
          const {params} = props ?? {};

          return  deleteLocation(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteLocationMutationResult = NonNullable<Awaited<ReturnType<typeof deleteLocation>>>

    export type DeleteLocationMutationError = unknown

    /**
 * @summary Purge raw fixes + derived docs in a time range (owner erase).
 */
export const useDeleteLocation = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteLocation>>, TError,{params?: DeleteLocationParams}, TContext>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteLocation>>,
        TError,
        {params?: DeleteLocationParams},
        TContext
      > => {
      return useMutation(getDeleteLocationMutationOptions(options), queryClient);
    }

export const getPostLocationTrackingDeviceIdPauseUrl = (deviceId: string,) => {




  return `/location/tracking/${deviceId}/pause`
}

/**
 * @summary Pause tracking for a device (ingest is discarded while paused).
 */
export const postLocationTrackingDeviceIdPause = async (deviceId: string,
    nullPauseTrackingRequest?: null | PauseTrackingRequest, options?: Parameters<typeof customFetchLocation>[1]): Promise<void> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetchLocation<void>(getPostLocationTrackingDeviceIdPauseUrl(deviceId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(nullPauseTrackingRequest)
  }
);}





export const getPostLocationTrackingDeviceIdPauseMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLocationTrackingDeviceIdPause>>, TError,{deviceId: string;data?: null | PauseTrackingRequest}, TContext>, request?: SecondParameter<typeof customFetchLocation>}
): UseMutationOptions<Awaited<ReturnType<typeof postLocationTrackingDeviceIdPause>>, TError,{deviceId: string;data?: null | PauseTrackingRequest}, TContext> => {

const mutationKey = ['postLocationTrackingDeviceIdPause'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postLocationTrackingDeviceIdPause>>, {deviceId: string;data?: null | PauseTrackingRequest}> = (props) => {
          const {deviceId,data} = props ?? {};

          return  postLocationTrackingDeviceIdPause(deviceId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostLocationTrackingDeviceIdPauseMutationResult = NonNullable<Awaited<ReturnType<typeof postLocationTrackingDeviceIdPause>>>
    export type PostLocationTrackingDeviceIdPauseMutationBody = null | PauseTrackingRequest | undefined
    export type PostLocationTrackingDeviceIdPauseMutationError = unknown

    /**
 * @summary Pause tracking for a device (ingest is discarded while paused).
 */
export const usePostLocationTrackingDeviceIdPause = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLocationTrackingDeviceIdPause>>, TError,{deviceId: string;data?: null | PauseTrackingRequest}, TContext>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postLocationTrackingDeviceIdPause>>,
        TError,
        {deviceId: string;data?: null | PauseTrackingRequest},
        TContext
      > => {
      return useMutation(getPostLocationTrackingDeviceIdPauseMutationOptions(options), queryClient);
    }

export const getPostLocationTrackingDeviceIdResumeUrl = (deviceId: string,) => {




  return `/location/tracking/${deviceId}/resume`
}

/**
 * @summary Resume tracking for a device.
 */
export const postLocationTrackingDeviceIdResume = async (deviceId: string, options?: Parameters<typeof customFetchLocation>[1]): Promise<void> => {

  return customFetchLocation<void>(getPostLocationTrackingDeviceIdResumeUrl(deviceId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getPostLocationTrackingDeviceIdResumeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLocationTrackingDeviceIdResume>>, TError,{deviceId: string}, TContext>, request?: SecondParameter<typeof customFetchLocation>}
): UseMutationOptions<Awaited<ReturnType<typeof postLocationTrackingDeviceIdResume>>, TError,{deviceId: string}, TContext> => {

const mutationKey = ['postLocationTrackingDeviceIdResume'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postLocationTrackingDeviceIdResume>>, {deviceId: string}> = (props) => {
          const {deviceId} = props ?? {};

          return  postLocationTrackingDeviceIdResume(deviceId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostLocationTrackingDeviceIdResumeMutationResult = NonNullable<Awaited<ReturnType<typeof postLocationTrackingDeviceIdResume>>>

    export type PostLocationTrackingDeviceIdResumeMutationError = unknown

    /**
 * @summary Resume tracking for a device.
 */
export const usePostLocationTrackingDeviceIdResume = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLocationTrackingDeviceIdResume>>, TError,{deviceId: string}, TContext>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postLocationTrackingDeviceIdResume>>,
        TError,
        {deviceId: string},
        TContext
      > => {
      return useMutation(getPostLocationTrackingDeviceIdResumeMutationOptions(options), queryClient);
    }

export const getGetLocationTrackingDeviceIdStateUrl = (deviceId: string,) => {




  return `/location/tracking/${deviceId}/state`
}

/**
 * @summary Tracking state for a device.
 */
export const getLocationTrackingDeviceIdState = async (deviceId: string, options?: Parameters<typeof customFetchLocation>[1]): Promise<TrackingStateDto> => {

  return customFetchLocation<TrackingStateDto>(getGetLocationTrackingDeviceIdStateUrl(deviceId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetLocationTrackingDeviceIdStateQueryKey = (deviceId: string,) => {
    return [
    `/location/tracking/${deviceId}/state`
    ] as const;
    }


export const getGetLocationTrackingDeviceIdStateQueryOptions = <TData = Awaited<ReturnType<typeof getLocationTrackingDeviceIdState>>, TError = unknown>(deviceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationTrackingDeviceIdState>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLocationTrackingDeviceIdStateQueryKey(deviceId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLocationTrackingDeviceIdState>>> = ({ signal }) => getLocationTrackingDeviceIdState(deviceId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: deviceId !== null && deviceId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLocationTrackingDeviceIdState>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLocationTrackingDeviceIdStateQueryResult = NonNullable<Awaited<ReturnType<typeof getLocationTrackingDeviceIdState>>>
export type GetLocationTrackingDeviceIdStateQueryError = unknown


export function useGetLocationTrackingDeviceIdState<TData = Awaited<ReturnType<typeof getLocationTrackingDeviceIdState>>, TError = unknown>(
 deviceId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationTrackingDeviceIdState>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLocationTrackingDeviceIdState>>,
          TError,
          Awaited<ReturnType<typeof getLocationTrackingDeviceIdState>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLocationTrackingDeviceIdState<TData = Awaited<ReturnType<typeof getLocationTrackingDeviceIdState>>, TError = unknown>(
 deviceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationTrackingDeviceIdState>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLocationTrackingDeviceIdState>>,
          TError,
          Awaited<ReturnType<typeof getLocationTrackingDeviceIdState>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLocationTrackingDeviceIdState<TData = Awaited<ReturnType<typeof getLocationTrackingDeviceIdState>>, TError = unknown>(
 deviceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationTrackingDeviceIdState>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Tracking state for a device.
 */

export function useGetLocationTrackingDeviceIdState<TData = Awaited<ReturnType<typeof getLocationTrackingDeviceIdState>>, TError = unknown>(
 deviceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationTrackingDeviceIdState>>, TError, TData>>, request?: SecondParameter<typeof customFetchLocation>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLocationTrackingDeviceIdStateQueryOptions(deviceId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
