/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lupira Photo API
 * Family photo/video library backend for Lupira: presigned uploads, geotagging, map queries. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */
import type { AssetStatus } from './assetStatus';
import type { DeclaredPhotoResponseRequiredHeaders } from './declaredPhotoResponseRequiredHeaders';

export interface DeclaredPhotoResponse {
  assetId: string;
  status: AssetStatus;
  /** @nullable */
  uploadUrl?: string | null;
  /** @nullable */
  uploadExpiresAt?: string | null;
  requiredHeaders: DeclaredPhotoResponseRequiredHeaders;
}
