/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lupira Photo API
 * Family photo/video library backend for Lupira: presigned uploads, geotagging, map queries. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */
import type { PhotoMapPointDto } from './photoMapPointDto';
import type { PhotoMapPropertiesDto } from './photoMapPropertiesDto';

export interface PhotoMapFeatureDto {
  /** @nullable */
  type?: string | null;
  geometry: PhotoMapPointDto;
  properties: PhotoMapPropertiesDto;
}
