/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lupira Photo API
 * Family photo/video library backend for Lupira: presigned uploads, geotagging, map queries. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */

export type PhotoStatsByGeotagSource = {[key: string]: number};
