/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lupira Photo API
 * Family photo/video library backend for Lupira: presigned uploads, geotagging, map queries. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */
import type { AssetKind } from './assetKind';
import type { AssetStatus } from './assetStatus';
import type { GeotagSource } from './geotagSource';

export interface PhotoListItemDto {
  id: string;
  kind: AssetKind;
  status: AssetStatus;
  takenAt: string;
  /** @nullable */
  latitude?: number | null;
  /** @nullable */
  longitude?: number | null;
  /** @nullable */
  placeLabel?: string | null;
  /** @nullable */
  width?: number | null;
  /** @nullable */
  height?: number | null;
  /** @nullable */
  durationSeconds?: number | null;
  geotagSource: GeotagSource;
  contentType: string;
  sizeBytes: number;
  /**
     * Only set on a Failed asset — lets the health view explain itself without a per-item fetch.
     * @nullable
     */
  lastError?: string | null;
  /** @nullable */
  thumbUrl?: string | null;
}
