/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Lupira Geo API
 * Gazetteer, geocoding, and saved-places backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AdminAreaDto,
  CreatePlaceRequest,
  CreateSavedPlaceRequest,
  ForwardGeocodeParams,
  GeocodeResultDto,
  ListAdminAreasParams,
  MeDto,
  PlaceDto,
  ProblemDetails,
  ResolvePlaceRequest,
  ResolvePlaceResponse,
  ReverseGeocodeParams,
  SavedPlaceDto,
  SearchPlacesParams,
  UpdatePlaceRequest,
  UpdateSavedPlaceRequest
} from './models';

import { customFetchGeo } from '../fetcher';
type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetMeUrl = () => {




  return `/me`
}

/**
 * @summary The caller's resolved local identity (JIT-provisioned on first login).
 */
export const getMe = async ( options?: RequestInit): Promise<MeDto> => {

  return customFetchGeo<MeDto>(getGetMeUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetMeQueryKey = () => {
    return [
    `/me`
    ] as const;
    }


export const getGetMeQueryOptions = <TData = Awaited<ReturnType<typeof getMe>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>, request?: SecondParameter<typeof customFetchGeo>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMe>>> = ({ signal }) => getMe({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMeQueryResult = NonNullable<Awaited<ReturnType<typeof getMe>>>
export type GetMeQueryError = void


export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMe>>,
          TError,
          Awaited<ReturnType<typeof getMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchGeo>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMe>>,
          TError,
          Awaited<ReturnType<typeof getMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchGeo>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>, request?: SecondParameter<typeof customFetchGeo>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary The caller's resolved local identity (JIT-provisioned on first login).
 */

export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>, request?: SecondParameter<typeof customFetchGeo>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getSearchPlacesUrl = (params?: SearchPlacesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ["bbox"];

    if (Array.isArray(value) && explodeParameters.includes(key)) {
      value.forEach((v) => {
        normalizedParams.append(key, v === null ? 'null' : String(v));
      });
      return;
    }

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/places?${stringifiedParams}` : `/places`
}

/**
 * @summary Search the gazetteer: text (q, trigram), category/kind, containment (withinAreaId), and spatial — proximity (nearLat+nearLon[+radiusM], returns distanceM) or viewport (bbox=minLon&bbox=minLat&bbox=maxLon&bbox=maxLat).
 */
export const searchPlaces = async (params?: SearchPlacesParams, options?: RequestInit): Promise<PlaceDto[]> => {

  return customFetchGeo<PlaceDto[]>(getSearchPlacesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getSearchPlacesQueryKey = (params?: SearchPlacesParams,) => {
    return [
    `/places`, ...(params ? [params] : [])
    ] as const;
    }


export const getSearchPlacesQueryOptions = <TData = Awaited<ReturnType<typeof searchPlaces>>, TError = ProblemDetails | void>(params?: SearchPlacesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchPlaces>>, TError, TData>>, request?: SecondParameter<typeof customFetchGeo>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchPlacesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchPlaces>>> = ({ signal }) => searchPlaces(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchPlaces>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchPlacesQueryResult = NonNullable<Awaited<ReturnType<typeof searchPlaces>>>
export type SearchPlacesQueryError = ProblemDetails | void


export function useSearchPlaces<TData = Awaited<ReturnType<typeof searchPlaces>>, TError = ProblemDetails | void>(
 params: undefined |  SearchPlacesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchPlaces>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchPlaces>>,
          TError,
          Awaited<ReturnType<typeof searchPlaces>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchGeo>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchPlaces<TData = Awaited<ReturnType<typeof searchPlaces>>, TError = ProblemDetails | void>(
 params?: SearchPlacesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchPlaces>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchPlaces>>,
          TError,
          Awaited<ReturnType<typeof searchPlaces>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchGeo>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchPlaces<TData = Awaited<ReturnType<typeof searchPlaces>>, TError = ProblemDetails | void>(
 params?: SearchPlacesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchPlaces>>, TError, TData>>, request?: SecondParameter<typeof customFetchGeo>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Search the gazetteer: text (q, trigram), category/kind, containment (withinAreaId), and spatial — proximity (nearLat+nearLon[+radiusM], returns distanceM) or viewport (bbox=minLon&bbox=minLat&bbox=maxLon&bbox=maxLat).
 */

export function useSearchPlaces<TData = Awaited<ReturnType<typeof searchPlaces>>, TError = ProblemDetails | void>(
 params?: SearchPlacesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchPlaces>>, TError, TData>>, request?: SecondParameter<typeof customFetchGeo>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchPlacesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getCreatePlaceUrl = () => {




  return `/places`
}

/**
 * @summary Create a user place directly (name + optional coordinates/category).
 */
export const createPlace = async (createPlaceRequest: CreatePlaceRequest, options?: RequestInit): Promise<PlaceDto> => {

  return customFetchGeo<PlaceDto>(getCreatePlaceUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createPlaceRequest)
  }
);}





export const getCreatePlaceMutationOptions = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPlace>>, TError,{data: CreatePlaceRequest}, TContext>, request?: SecondParameter<typeof customFetchGeo>}
): UseMutationOptions<Awaited<ReturnType<typeof createPlace>>, TError,{data: CreatePlaceRequest}, TContext> => {

const mutationKey = ['createPlace'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPlace>>, {data: CreatePlaceRequest}> = (props) => {
          const {data} = props ?? {};

          return  createPlace(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreatePlaceMutationResult = NonNullable<Awaited<ReturnType<typeof createPlace>>>
    export type CreatePlaceMutationBody = CreatePlaceRequest
    export type CreatePlaceMutationError = ProblemDetails | void

    /**
 * @summary Create a user place directly (name + optional coordinates/category).
 */
export const useCreatePlace = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPlace>>, TError,{data: CreatePlaceRequest}, TContext>, request?: SecondParameter<typeof customFetchGeo>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createPlace>>,
        TError,
        {data: CreatePlaceRequest},
        TContext
      > => {
      return useMutation(getCreatePlaceMutationOptions(options), queryClient);
    }

export const getGetPlaceUrl = (id: string,) => {




  return `/places/${id}`
}

/**
 * @summary A single place with its aliases, external ids, and containment chain (outermost→innermost).
 */
export const getPlace = async (id: string, options?: RequestInit): Promise<PlaceDto> => {

  return customFetchGeo<PlaceDto>(getGetPlaceUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPlaceQueryKey = (id: string,) => {
    return [
    `/places/${id}`
    ] as const;
    }


export const getGetPlaceQueryOptions = <TData = Awaited<ReturnType<typeof getPlace>>, TError = void>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlace>>, TError, TData>>, request?: SecondParameter<typeof customFetchGeo>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPlaceQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPlace>>> = ({ signal }) => getPlace(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPlace>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPlaceQueryResult = NonNullable<Awaited<ReturnType<typeof getPlace>>>
export type GetPlaceQueryError = void


export function useGetPlace<TData = Awaited<ReturnType<typeof getPlace>>, TError = void>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlace>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPlace>>,
          TError,
          Awaited<ReturnType<typeof getPlace>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchGeo>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPlace<TData = Awaited<ReturnType<typeof getPlace>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlace>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPlace>>,
          TError,
          Awaited<ReturnType<typeof getPlace>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchGeo>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPlace<TData = Awaited<ReturnType<typeof getPlace>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlace>>, TError, TData>>, request?: SecondParameter<typeof customFetchGeo>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary A single place with its aliases, external ids, and containment chain (outermost→innermost).
 */

export function useGetPlace<TData = Awaited<ReturnType<typeof getPlace>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlace>>, TError, TData>>, request?: SecondParameter<typeof customFetchGeo>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPlaceQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getUpdatePlaceUrl = (id: string,) => {




  return `/places/${id}`
}

/**
 * @summary Curate a place: rename, recategorize, or verify.
 */
export const updatePlace = async (id: string,
    updatePlaceRequest: UpdatePlaceRequest, options?: RequestInit): Promise<PlaceDto> => {

  return customFetchGeo<PlaceDto>(getUpdatePlaceUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updatePlaceRequest)
  }
);}





export const getUpdatePlaceMutationOptions = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePlace>>, TError,{id: string;data: UpdatePlaceRequest}, TContext>, request?: SecondParameter<typeof customFetchGeo>}
): UseMutationOptions<Awaited<ReturnType<typeof updatePlace>>, TError,{id: string;data: UpdatePlaceRequest}, TContext> => {

const mutationKey = ['updatePlace'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePlace>>, {id: string;data: UpdatePlaceRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updatePlace(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdatePlaceMutationResult = NonNullable<Awaited<ReturnType<typeof updatePlace>>>
    export type UpdatePlaceMutationBody = UpdatePlaceRequest
    export type UpdatePlaceMutationError = ProblemDetails | void

    /**
 * @summary Curate a place: rename, recategorize, or verify.
 */
export const useUpdatePlace = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePlace>>, TError,{id: string;data: UpdatePlaceRequest}, TContext>, request?: SecondParameter<typeof customFetchGeo>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updatePlace>>,
        TError,
        {id: string;data: UpdatePlaceRequest},
        TContext
      > => {
      return useMutation(getUpdatePlaceMutationOptions(options), queryClient);
    }

export const getResolvePlaceUrl = () => {




  return `/places/resolve`
}

/**
 * @summary Resolve free-text to a place id — match an existing entry, geocode, or provisionally create. Used by upstream services (e.g. LupiraCalApi) to anchor a location string.
 */
export const resolvePlace = async (resolvePlaceRequest: ResolvePlaceRequest, options?: RequestInit): Promise<ResolvePlaceResponse> => {

  return customFetchGeo<ResolvePlaceResponse>(getResolvePlaceUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(resolvePlaceRequest)
  }
);}





export const getResolvePlaceMutationOptions = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resolvePlace>>, TError,{data: ResolvePlaceRequest}, TContext>, request?: SecondParameter<typeof customFetchGeo>}
): UseMutationOptions<Awaited<ReturnType<typeof resolvePlace>>, TError,{data: ResolvePlaceRequest}, TContext> => {

const mutationKey = ['resolvePlace'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof resolvePlace>>, {data: ResolvePlaceRequest}> = (props) => {
          const {data} = props ?? {};

          return  resolvePlace(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ResolvePlaceMutationResult = NonNullable<Awaited<ReturnType<typeof resolvePlace>>>
    export type ResolvePlaceMutationBody = ResolvePlaceRequest
    export type ResolvePlaceMutationError = ProblemDetails | void

    /**
 * @summary Resolve free-text to a place id — match an existing entry, geocode, or provisionally create. Used by upstream services (e.g. LupiraCalApi) to anchor a location string.
 */
export const useResolvePlace = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resolvePlace>>, TError,{data: ResolvePlaceRequest}, TContext>, request?: SecondParameter<typeof customFetchGeo>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof resolvePlace>>,
        TError,
        {data: ResolvePlaceRequest},
        TContext
      > => {
      return useMutation(getResolvePlaceMutationOptions(options), queryClient);
    }

export const getReverseGeocodeUrl = (params: ReverseGeocodeParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/geocode/reverse?${stringifiedParams}` : `/geocode/reverse`
}

/**
 * @summary Coordinate → coarse label + structured address (cached; coordinates quantized to a ~100 m grid).
 */
export const reverseGeocode = async (params: ReverseGeocodeParams, options?: RequestInit): Promise<GeocodeResultDto> => {

  return customFetchGeo<GeocodeResultDto>(getReverseGeocodeUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getReverseGeocodeQueryKey = (params?: ReverseGeocodeParams,) => {
    return [
    `/geocode/reverse`, ...(params ? [params] : [])
    ] as const;
    }


export const getReverseGeocodeQueryOptions = <TData = Awaited<ReturnType<typeof reverseGeocode>>, TError = void>(params: ReverseGeocodeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reverseGeocode>>, TError, TData>>, request?: SecondParameter<typeof customFetchGeo>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReverseGeocodeQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof reverseGeocode>>> = ({ signal }) => reverseGeocode(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof reverseGeocode>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReverseGeocodeQueryResult = NonNullable<Awaited<ReturnType<typeof reverseGeocode>>>
export type ReverseGeocodeQueryError = void


export function useReverseGeocode<TData = Awaited<ReturnType<typeof reverseGeocode>>, TError = void>(
 params: ReverseGeocodeParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof reverseGeocode>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof reverseGeocode>>,
          TError,
          Awaited<ReturnType<typeof reverseGeocode>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchGeo>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReverseGeocode<TData = Awaited<ReturnType<typeof reverseGeocode>>, TError = void>(
 params: ReverseGeocodeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reverseGeocode>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof reverseGeocode>>,
          TError,
          Awaited<ReturnType<typeof reverseGeocode>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchGeo>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReverseGeocode<TData = Awaited<ReturnType<typeof reverseGeocode>>, TError = void>(
 params: ReverseGeocodeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reverseGeocode>>, TError, TData>>, request?: SecondParameter<typeof customFetchGeo>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Coordinate → coarse label + structured address (cached; coordinates quantized to a ~100 m grid).
 */

export function useReverseGeocode<TData = Awaited<ReturnType<typeof reverseGeocode>>, TError = void>(
 params: ReverseGeocodeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reverseGeocode>>, TError, TData>>, request?: SecondParameter<typeof customFetchGeo>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReverseGeocodeQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getForwardGeocodeUrl = (params: ForwardGeocodeParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/geocode/forward?${stringifiedParams}` : `/geocode/forward`
}

/**
 * @summary Text → candidate coordinates + structured address (cached).
 */
export const forwardGeocode = async (params: ForwardGeocodeParams, options?: RequestInit): Promise<GeocodeResultDto[]> => {

  return customFetchGeo<GeocodeResultDto[]>(getForwardGeocodeUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getForwardGeocodeQueryKey = (params?: ForwardGeocodeParams,) => {
    return [
    `/geocode/forward`, ...(params ? [params] : [])
    ] as const;
    }


export const getForwardGeocodeQueryOptions = <TData = Awaited<ReturnType<typeof forwardGeocode>>, TError = void>(params: ForwardGeocodeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof forwardGeocode>>, TError, TData>>, request?: SecondParameter<typeof customFetchGeo>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getForwardGeocodeQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof forwardGeocode>>> = ({ signal }) => forwardGeocode(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof forwardGeocode>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ForwardGeocodeQueryResult = NonNullable<Awaited<ReturnType<typeof forwardGeocode>>>
export type ForwardGeocodeQueryError = void


export function useForwardGeocode<TData = Awaited<ReturnType<typeof forwardGeocode>>, TError = void>(
 params: ForwardGeocodeParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof forwardGeocode>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof forwardGeocode>>,
          TError,
          Awaited<ReturnType<typeof forwardGeocode>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchGeo>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useForwardGeocode<TData = Awaited<ReturnType<typeof forwardGeocode>>, TError = void>(
 params: ForwardGeocodeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof forwardGeocode>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof forwardGeocode>>,
          TError,
          Awaited<ReturnType<typeof forwardGeocode>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchGeo>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useForwardGeocode<TData = Awaited<ReturnType<typeof forwardGeocode>>, TError = void>(
 params: ForwardGeocodeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof forwardGeocode>>, TError, TData>>, request?: SecondParameter<typeof customFetchGeo>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Text → candidate coordinates + structured address (cached).
 */

export function useForwardGeocode<TData = Awaited<ReturnType<typeof forwardGeocode>>, TError = void>(
 params: ForwardGeocodeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof forwardGeocode>>, TError, TData>>, request?: SecondParameter<typeof customFetchGeo>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getForwardGeocodeQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getListAdminAreasUrl = (params?: ListAdminAreasParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/admin-areas?${stringifiedParams}` : `/admin-areas`
}

/**
 * @summary Browse the administrative containment tree: filter by level (Country/Region/Locality), parent (withinAreaId), or name (q).
 */
export const listAdminAreas = async (params?: ListAdminAreasParams, options?: RequestInit): Promise<AdminAreaDto[]> => {

  return customFetchGeo<AdminAreaDto[]>(getListAdminAreasUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListAdminAreasQueryKey = (params?: ListAdminAreasParams,) => {
    return [
    `/admin-areas`, ...(params ? [params] : [])
    ] as const;
    }


export const getListAdminAreasQueryOptions = <TData = Awaited<ReturnType<typeof listAdminAreas>>, TError = void>(params?: ListAdminAreasParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminAreas>>, TError, TData>>, request?: SecondParameter<typeof customFetchGeo>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAdminAreasQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAdminAreas>>> = ({ signal }) => listAdminAreas(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAdminAreas>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListAdminAreasQueryResult = NonNullable<Awaited<ReturnType<typeof listAdminAreas>>>
export type ListAdminAreasQueryError = void


export function useListAdminAreas<TData = Awaited<ReturnType<typeof listAdminAreas>>, TError = void>(
 params: undefined |  ListAdminAreasParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminAreas>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAdminAreas>>,
          TError,
          Awaited<ReturnType<typeof listAdminAreas>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchGeo>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAdminAreas<TData = Awaited<ReturnType<typeof listAdminAreas>>, TError = void>(
 params?: ListAdminAreasParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminAreas>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAdminAreas>>,
          TError,
          Awaited<ReturnType<typeof listAdminAreas>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchGeo>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAdminAreas<TData = Awaited<ReturnType<typeof listAdminAreas>>, TError = void>(
 params?: ListAdminAreasParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminAreas>>, TError, TData>>, request?: SecondParameter<typeof customFetchGeo>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Browse the administrative containment tree: filter by level (Country/Region/Locality), parent (withinAreaId), or name (q).
 */

export function useListAdminAreas<TData = Awaited<ReturnType<typeof listAdminAreas>>, TError = void>(
 params?: ListAdminAreasParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminAreas>>, TError, TData>>, request?: SecondParameter<typeof customFetchGeo>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListAdminAreasQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getGetAdminAreaUrl = (id: string,) => {




  return `/admin-areas/${id}`
}

/**
 * @summary A single administrative area.
 */
export const getAdminArea = async (id: string, options?: RequestInit): Promise<AdminAreaDto> => {

  return customFetchGeo<AdminAreaDto>(getGetAdminAreaUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAdminAreaQueryKey = (id: string,) => {
    return [
    `/admin-areas/${id}`
    ] as const;
    }


export const getGetAdminAreaQueryOptions = <TData = Awaited<ReturnType<typeof getAdminArea>>, TError = void>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminArea>>, TError, TData>>, request?: SecondParameter<typeof customFetchGeo>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminAreaQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminArea>>> = ({ signal }) => getAdminArea(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminArea>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAdminAreaQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminArea>>>
export type GetAdminAreaQueryError = void


export function useGetAdminArea<TData = Awaited<ReturnType<typeof getAdminArea>>, TError = void>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminArea>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminArea>>,
          TError,
          Awaited<ReturnType<typeof getAdminArea>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchGeo>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminArea<TData = Awaited<ReturnType<typeof getAdminArea>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminArea>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminArea>>,
          TError,
          Awaited<ReturnType<typeof getAdminArea>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchGeo>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminArea<TData = Awaited<ReturnType<typeof getAdminArea>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminArea>>, TError, TData>>, request?: SecondParameter<typeof customFetchGeo>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary A single administrative area.
 */

export function useGetAdminArea<TData = Awaited<ReturnType<typeof getAdminArea>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminArea>>, TError, TData>>, request?: SecondParameter<typeof customFetchGeo>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAdminAreaQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getListSavedPlacesUrl = () => {




  return `/me/places`
}

/**
 * @summary The caller's saved places / personal labels (favorites first).
 */
export const listSavedPlaces = async ( options?: RequestInit): Promise<SavedPlaceDto[]> => {

  return customFetchGeo<SavedPlaceDto[]>(getListSavedPlacesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListSavedPlacesQueryKey = () => {
    return [
    `/me/places`
    ] as const;
    }


export const getListSavedPlacesQueryOptions = <TData = Awaited<ReturnType<typeof listSavedPlaces>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSavedPlaces>>, TError, TData>>, request?: SecondParameter<typeof customFetchGeo>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListSavedPlacesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listSavedPlaces>>> = ({ signal }) => listSavedPlaces({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listSavedPlaces>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListSavedPlacesQueryResult = NonNullable<Awaited<ReturnType<typeof listSavedPlaces>>>
export type ListSavedPlacesQueryError = void


export function useListSavedPlaces<TData = Awaited<ReturnType<typeof listSavedPlaces>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSavedPlaces>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSavedPlaces>>,
          TError,
          Awaited<ReturnType<typeof listSavedPlaces>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchGeo>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSavedPlaces<TData = Awaited<ReturnType<typeof listSavedPlaces>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSavedPlaces>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSavedPlaces>>,
          TError,
          Awaited<ReturnType<typeof listSavedPlaces>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchGeo>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSavedPlaces<TData = Awaited<ReturnType<typeof listSavedPlaces>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSavedPlaces>>, TError, TData>>, request?: SecondParameter<typeof customFetchGeo>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary The caller's saved places / personal labels (favorites first).
 */

export function useListSavedPlaces<TData = Awaited<ReturnType<typeof listSavedPlaces>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSavedPlaces>>, TError, TData>>, request?: SecondParameter<typeof customFetchGeo>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListSavedPlacesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getCreateSavedPlaceUrl = () => {




  return `/me/places`
}

/**
 * @summary Save a place with a personal label (references a gazetteer place, or a raw coordinate).
 */
export const createSavedPlace = async (createSavedPlaceRequest: CreateSavedPlaceRequest, options?: RequestInit): Promise<SavedPlaceDto> => {

  return customFetchGeo<SavedPlaceDto>(getCreateSavedPlaceUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createSavedPlaceRequest)
  }
);}





export const getCreateSavedPlaceMutationOptions = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSavedPlace>>, TError,{data: CreateSavedPlaceRequest}, TContext>, request?: SecondParameter<typeof customFetchGeo>}
): UseMutationOptions<Awaited<ReturnType<typeof createSavedPlace>>, TError,{data: CreateSavedPlaceRequest}, TContext> => {

const mutationKey = ['createSavedPlace'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createSavedPlace>>, {data: CreateSavedPlaceRequest}> = (props) => {
          const {data} = props ?? {};

          return  createSavedPlace(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateSavedPlaceMutationResult = NonNullable<Awaited<ReturnType<typeof createSavedPlace>>>
    export type CreateSavedPlaceMutationBody = CreateSavedPlaceRequest
    export type CreateSavedPlaceMutationError = ProblemDetails | void

    /**
 * @summary Save a place with a personal label (references a gazetteer place, or a raw coordinate).
 */
export const useCreateSavedPlace = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSavedPlace>>, TError,{data: CreateSavedPlaceRequest}, TContext>, request?: SecondParameter<typeof customFetchGeo>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createSavedPlace>>,
        TError,
        {data: CreateSavedPlaceRequest},
        TContext
      > => {
      return useMutation(getCreateSavedPlaceMutationOptions(options), queryClient);
    }

export const getUpdateSavedPlaceUrl = (id: string,) => {




  return `/me/places/${id}`
}

/**
 * @summary Rename, re-icon, or (un)favorite a saved place.
 */
export const updateSavedPlace = async (id: string,
    updateSavedPlaceRequest: UpdateSavedPlaceRequest, options?: RequestInit): Promise<SavedPlaceDto> => {

  return customFetchGeo<SavedPlaceDto>(getUpdateSavedPlaceUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateSavedPlaceRequest)
  }
);}





export const getUpdateSavedPlaceMutationOptions = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSavedPlace>>, TError,{id: string;data: UpdateSavedPlaceRequest}, TContext>, request?: SecondParameter<typeof customFetchGeo>}
): UseMutationOptions<Awaited<ReturnType<typeof updateSavedPlace>>, TError,{id: string;data: UpdateSavedPlaceRequest}, TContext> => {

const mutationKey = ['updateSavedPlace'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateSavedPlace>>, {id: string;data: UpdateSavedPlaceRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateSavedPlace(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateSavedPlaceMutationResult = NonNullable<Awaited<ReturnType<typeof updateSavedPlace>>>
    export type UpdateSavedPlaceMutationBody = UpdateSavedPlaceRequest
    export type UpdateSavedPlaceMutationError = ProblemDetails | void

    /**
 * @summary Rename, re-icon, or (un)favorite a saved place.
 */
export const useUpdateSavedPlace = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSavedPlace>>, TError,{id: string;data: UpdateSavedPlaceRequest}, TContext>, request?: SecondParameter<typeof customFetchGeo>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateSavedPlace>>,
        TError,
        {id: string;data: UpdateSavedPlaceRequest},
        TContext
      > => {
      return useMutation(getUpdateSavedPlaceMutationOptions(options), queryClient);
    }

export const getDeleteSavedPlaceUrl = (id: string,) => {




  return `/me/places/${id}`
}

/**
 * @summary Remove a saved place.
 */
export const deleteSavedPlace = async (id: string, options?: RequestInit): Promise<void> => {

  return customFetchGeo<void>(getDeleteSavedPlaceUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteSavedPlaceMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSavedPlace>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetchGeo>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteSavedPlace>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteSavedPlace'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteSavedPlace>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteSavedPlace(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteSavedPlaceMutationResult = NonNullable<Awaited<ReturnType<typeof deleteSavedPlace>>>

    export type DeleteSavedPlaceMutationError = void

    /**
 * @summary Remove a saved place.
 */
export const useDeleteSavedPlace = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSavedPlace>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetchGeo>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteSavedPlace>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteSavedPlaceMutationOptions(options), queryClient);
    }
