/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Lupira Contact API
 * Contacts, address books, and kinship backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */
import type { Access } from './access';

export interface AddressBookDto {
  id: string;
  slug: string;
  /** @nullable */
  displayName?: string | null;
  access: Access;
}
