/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lupira Contact API
 * Contacts, address books, and kinship backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */

/**
 * A social/IM handle as submitted. `Url` is derived from the handle for well-known services when
 *             omitted; `Preferred` defaults to false.
 */
export interface ContactSocialProfileInput {
  service: string;
  handle: string;
  /** @nullable */
  url?: string | null;
  preferred?: boolean;
}
