/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lupira Contact API
 * Contacts, address books, and kinship backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */

/**
 * What the contact card represents — vCard `KIND`. A business/venue (a provider referenced from
 *             bookings, say) is an `Organization`: no birthday, employer, or kinship applies. `Individual` is ordinal 0
 *             so pre-existing events replay as persons.
 */
export type ContactKind = typeof ContactKind[keyof typeof ContactKind];


export const ContactKind = {
  Individual: 'Individual',
  Organization: 'Organization',
} as const;
