/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lupira Contact API
 * Contacts, address books, and kinship backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */
import type { ContactRelationKind } from './contactRelationKind';

/**
 * One outgoing relation edge as published: "the `ToContactId` contact is my `Kind`".
 *             `Ended`/`Until` mark a relationship that ran its course, distinct from removal.
 */
export interface ContactRelationDto {
  toContactId: string;
  kind: ContactRelationKind;
  /** @nullable */
  label: string | null;
  /** @nullable */
  since: string | null;
  /** @nullable */
  note: string | null;
  ended: boolean;
  /** @nullable */
  until: string | null;
}
