/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Lupira Contact API
 * Contacts, address books, and kinship backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */
import type { ContactGroupKind } from './contactGroupKind';
import type { GroupMemberDto } from './groupMemberDto';

export interface ContactGroupDto {
  id: string;
  addressBookId: string;
  kind: ContactGroupKind;
  name: string;
  members: GroupMemberDto[];
  createdAt?: string;
  /** @nullable */
  createdBy?: string | null;
  updatedAt?: string;
  /** @nullable */
  updatedBy?: string | null;
}
