/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lupira Contact API
 * Contacts, address books, and kinship backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */

export type ContactKind = typeof ContactKind[keyof typeof ContactKind];


export const ContactKind = {
  Individual: 'Individual',
  Organization: 'Organization',
} as const;
