/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lupira Contact API
 * Contacts, address books, and kinship backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */

/**
 * A lightweight contact reference (id + display name) — a resolve candidate.
 */
export interface ContactRef {
  contactId: string;
  displayName: string;
}
