/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Lupira Contact API
 * Contacts, address books, and kinship backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */
import type { ContactRef } from './contactRef';
import type { NameMatchOutcome } from './nameMatchOutcome';

export interface ContactNameMatch {
  name: string;
  /** @nullable */
  contactId?: string | null;
  outcome: NameMatchOutcome;
  candidates: ContactRef[];
}
