/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lupira Contact API
 * Contacts, address books, and kinship backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */
import type { CreateContactRequest } from './createContactRequest';

export interface CreateContactsBatchRequest {
  contacts: CreateContactRequest[];
}
