/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Lupira Contact API
 * Contacts, address books, and kinship backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */

export interface GroupMemberDto {
  contactId: string;
  /** @nullable */
  role?: string | null;
  /** @nullable */
  since?: string | null;
  /** @nullable */
  until?: string | null;
}
