/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Lupira Contact API
 * Contacts, address books, and kinship backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */

export type KinshipKind = typeof KinshipKind[keyof typeof KinshipKind];


export const KinshipKind = {
  Parent: 'Parent',
  Child: 'Child',
  Sibling: 'Sibling',
  Spouse: 'Spouse',
  Partner: 'Partner',
  Friend: 'Friend',
  Colleague: 'Colleague',
  Neighbor: 'Neighbor',
  Emergency: 'Emergency',
  Other: 'Other',
  Grandparent: 'Grandparent',
  Grandchild: 'Grandchild',
  AuntUncle: 'AuntUncle',
  NieceNephew: 'NieceNephew',
  Cousin: 'Cousin',
} as const;
