/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lupira Contact API
 * Contacts, address books, and kinship backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */

/**
 * The resolved local identity of the caller: the stable Guid MeDto.PrincipalId plus current
 *             email/display name — the same identity shape (`principalId`/`email`/`displayName`) the
 *             platform uses everywhere it returns a person.
 */
export interface MeDto {
  principalId: string;
  email: string;
  /** @nullable */
  displayName?: string | null;
  /**
     * The caller's own contact ("this card is me"), when linked — the default circles focus.
     * @nullable
     */
  contactId?: string | null;
}
