/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Lupira Contact API
 * Contacts, address books, and kinship backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */

export type NameMatchOutcome = typeof NameMatchOutcome[keyof typeof NameMatchOutcome];


export const NameMatchOutcome = {
  Matched: 'Matched',
  Ambiguous: 'Ambiguous',
  NotFound: 'NotFound',
} as const;
