/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Lupira Contact API
 * Contacts, address books, and kinship backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */

export type RelationProvenance = typeof RelationProvenance[keyof typeof RelationProvenance];


export const RelationProvenance = {
  Explicit: 'Explicit',
  Inferred: 'Inferred',
} as const;
