/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lupira Contact API
 * Contacts, address books, and kinship backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */
import type { SectionGuardDto } from './sectionGuardDto';

export interface SectionGuardsDto {
  core: SectionGuardDto;
  addresses: SectionGuardDto;
  profiles: SectionGuardDto;
  avatar: SectionGuardDto;
  metadata: SectionGuardDto;
  deceased: SectionGuardDto;
}
