/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lupira Contact API
 * Contacts, address books, and kinship backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */

/**
 * Marks a contact as deceased; the date may be unknown.
 */
export interface SetDeceasedRequest {
  /** @nullable */
  deathDate?: string | null;
  /**
     * Client wall-clock of the edit, for last-writer-wins conflict resolution. Omitted ⇒ server receive time.
     * @nullable
     */
  occurredAt?: string | null;
}
