/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Lupira Contact API
 * Contacts, address books, and kinship backend for Lupira. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */
import type { ContactDto } from './contactDto';
import type { SectionGuardsDto } from './sectionGuardsDto';

export interface SyncChangeDto {
  contact: ContactDto;
  guards: SectionGuardsDto;
}
