/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lupira Photo API
 * Family photo/video library backend for Lupira: presigned uploads, geotagging, map queries. Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DeclarePhotoRequest,
  DeclaredPhotoResponse,
  GetPhotoMapParams,
  ListPhotosParams,
  LookupPhotosRequest,
  MeDto,
  PhotoAssetDto,
  PhotoListResponse,
  PhotoMapResponse,
  PhotoStats,
  ProblemDetails
} from './models';

import { customFetchPhoto } from '../fetcher';
type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetMeUrl = () => {




  return `/me`
}

/**
 * @summary The caller's resolved local identity (JIT-provisioned on first login).
 */
export const getMe = async ( options?: Parameters<typeof customFetchPhoto>[1]): Promise<MeDto> => {

  return customFetchPhoto<MeDto>(getGetMeUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetMeQueryKey = () => {
    return [
    `/me`
    ] as const;
    }


export const getGetMeQueryOptions = <TData = Awaited<ReturnType<typeof getMe>>, TError = ProblemDetails>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>, request?: SecondParameter<typeof customFetchPhoto>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMe>>> = ({ signal }) => getMe({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMeQueryResult = NonNullable<Awaited<ReturnType<typeof getMe>>>
export type GetMeQueryError = ProblemDetails


export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = ProblemDetails>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMe>>,
          TError,
          Awaited<ReturnType<typeof getMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchPhoto>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = ProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMe>>,
          TError,
          Awaited<ReturnType<typeof getMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchPhoto>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = ProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>, request?: SecondParameter<typeof customFetchPhoto>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary The caller's resolved local identity (JIT-provisioned on first login).
 */

export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = ProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>, request?: SecondParameter<typeof customFetchPhoto>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getDeclarePhotoUrl = () => {




  return `/photos`
}

/**
 * @summary Declare an asset (idempotent) and receive a presigned upload URL while bytes are pending.
 */
export const declarePhoto = async (declarePhotoRequest: DeclarePhotoRequest, options?: Parameters<typeof customFetchPhoto>[1]): Promise<DeclaredPhotoResponse> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetchPhoto<DeclaredPhotoResponse>(getDeclarePhotoUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(declarePhotoRequest)
  }
);}





export const getDeclarePhotoMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof declarePhoto>>, TError,{data: DeclarePhotoRequest}, TContext>, request?: SecondParameter<typeof customFetchPhoto>}
): UseMutationOptions<Awaited<ReturnType<typeof declarePhoto>>, TError,{data: DeclarePhotoRequest}, TContext> => {

const mutationKey = ['declarePhoto'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof declarePhoto>>, {data: DeclarePhotoRequest}> = (props) => {
          const {data} = props ?? {};

          return  declarePhoto(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeclarePhotoMutationResult = NonNullable<Awaited<ReturnType<typeof declarePhoto>>>
    export type DeclarePhotoMutationBody = DeclarePhotoRequest
    export type DeclarePhotoMutationError = ProblemDetails

    /**
 * @summary Declare an asset (idempotent) and receive a presigned upload URL while bytes are pending.
 */
export const useDeclarePhoto = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof declarePhoto>>, TError,{data: DeclarePhotoRequest}, TContext>, request?: SecondParameter<typeof customFetchPhoto>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof declarePhoto>>,
        TError,
        {data: DeclarePhotoRequest},
        TContext
      > => {
      return useMutation(getDeclarePhotoMutationOptions(options), queryClient);
    }

export const getListPhotosUrl = (params?: ListPhotosParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/photos?${stringifiedParams}` : `/photos`
}

/**
 * @summary List assets (keyset-paged, newest taken first by default) with presigned thumbnail URLs.
 */
export const listPhotos = async (params?: ListPhotosParams, options?: Parameters<typeof customFetchPhoto>[1]): Promise<PhotoListResponse> => {

  return customFetchPhoto<PhotoListResponse>(getListPhotosUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListPhotosQueryKey = (params?: ListPhotosParams,) => {
    return [
    `/photos`, ...(params ? [params] : [])
    ] as const;
    }


export const getListPhotosQueryOptions = <TData = Awaited<ReturnType<typeof listPhotos>>, TError = ProblemDetails>(params?: ListPhotosParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPhotos>>, TError, TData>>, request?: SecondParameter<typeof customFetchPhoto>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPhotosQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPhotos>>> = ({ signal }) => listPhotos(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listPhotos>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListPhotosQueryResult = NonNullable<Awaited<ReturnType<typeof listPhotos>>>
export type ListPhotosQueryError = ProblemDetails


export function useListPhotos<TData = Awaited<ReturnType<typeof listPhotos>>, TError = ProblemDetails>(
 params: undefined |  ListPhotosParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPhotos>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPhotos>>,
          TError,
          Awaited<ReturnType<typeof listPhotos>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchPhoto>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPhotos<TData = Awaited<ReturnType<typeof listPhotos>>, TError = ProblemDetails>(
 params?: ListPhotosParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPhotos>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPhotos>>,
          TError,
          Awaited<ReturnType<typeof listPhotos>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchPhoto>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPhotos<TData = Awaited<ReturnType<typeof listPhotos>>, TError = ProblemDetails>(
 params?: ListPhotosParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPhotos>>, TError, TData>>, request?: SecondParameter<typeof customFetchPhoto>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List assets (keyset-paged, newest taken first by default) with presigned thumbnail URLs.
 */

export function useListPhotos<TData = Awaited<ReturnType<typeof listPhotos>>, TError = ProblemDetails>(
 params?: ListPhotosParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPhotos>>, TError, TData>>, request?: SecondParameter<typeof customFetchPhoto>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListPhotosQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getCompletePhotoUploadUrl = (id: string,) => {




  return `/photos/${id}/complete`
}

/**
 * @summary Verify the uploaded bytes and queue processing (idempotent).
 */
export const completePhotoUpload = async (id: string, options?: Parameters<typeof customFetchPhoto>[1]): Promise<PhotoAssetDto> => {

  return customFetchPhoto<PhotoAssetDto>(getCompletePhotoUploadUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}





export const getCompletePhotoUploadMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completePhotoUpload>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetchPhoto>}
): UseMutationOptions<Awaited<ReturnType<typeof completePhotoUpload>>, TError,{id: string}, TContext> => {

const mutationKey = ['completePhotoUpload'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof completePhotoUpload>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  completePhotoUpload(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CompletePhotoUploadMutationResult = NonNullable<Awaited<ReturnType<typeof completePhotoUpload>>>

    export type CompletePhotoUploadMutationError = ProblemDetails

    /**
 * @summary Verify the uploaded bytes and queue processing (idempotent).
 */
export const useCompletePhotoUpload = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completePhotoUpload>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetchPhoto>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof completePhotoUpload>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getCompletePhotoUploadMutationOptions(options), queryClient);
    }

export const getReprocessPhotoUrl = (id: string,) => {




  return `/photos/${id}/reprocess`
}

/**
 * @summary Re-queue a Ready or Failed asset through the processing pipeline.
 */
export const reprocessPhoto = async (id: string, options?: Parameters<typeof customFetchPhoto>[1]): Promise<PhotoAssetDto> => {

  return customFetchPhoto<PhotoAssetDto>(getReprocessPhotoUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}





export const getReprocessPhotoMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reprocessPhoto>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetchPhoto>}
): UseMutationOptions<Awaited<ReturnType<typeof reprocessPhoto>>, TError,{id: string}, TContext> => {

const mutationKey = ['reprocessPhoto'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof reprocessPhoto>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  reprocessPhoto(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ReprocessPhotoMutationResult = NonNullable<Awaited<ReturnType<typeof reprocessPhoto>>>

    export type ReprocessPhotoMutationError = ProblemDetails

    /**
 * @summary Re-queue a Ready or Failed asset through the processing pipeline.
 */
export const useReprocessPhoto = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reprocessPhoto>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetchPhoto>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof reprocessPhoto>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getReprocessPhotoMutationOptions(options), queryClient);
    }

export const getLookupPhotosUrl = () => {




  return `/photos/lookup`
}

/**
 * @summary Hydrate up to 200 assets by id — turns relation references into renderable items.
 */
export const lookupPhotos = async (lookupPhotosRequest: LookupPhotosRequest, options?: Parameters<typeof customFetchPhoto>[1]): Promise<PhotoListResponse> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetchPhoto<PhotoListResponse>(getLookupPhotosUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(lookupPhotosRequest)
  }
);}





export const getLookupPhotosMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof lookupPhotos>>, TError,{data: LookupPhotosRequest}, TContext>, request?: SecondParameter<typeof customFetchPhoto>}
): UseMutationOptions<Awaited<ReturnType<typeof lookupPhotos>>, TError,{data: LookupPhotosRequest}, TContext> => {

const mutationKey = ['lookupPhotos'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof lookupPhotos>>, {data: LookupPhotosRequest}> = (props) => {
          const {data} = props ?? {};

          return  lookupPhotos(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LookupPhotosMutationResult = NonNullable<Awaited<ReturnType<typeof lookupPhotos>>>
    export type LookupPhotosMutationBody = LookupPhotosRequest
    export type LookupPhotosMutationError = ProblemDetails

    /**
 * @summary Hydrate up to 200 assets by id — turns relation references into renderable items.
 */
export const useLookupPhotos = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof lookupPhotos>>, TError,{data: LookupPhotosRequest}, TContext>, request?: SecondParameter<typeof customFetchPhoto>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof lookupPhotos>>,
        TError,
        {data: LookupPhotosRequest},
        TContext
      > => {
      return useMutation(getLookupPhotosMutationOptions(options), queryClient);
    }

export const getGetPhotoStatsUrl = () => {




  return `/photos/stats`
}

/**
 * @summary Library totals and counts by kind, status, geotag source and month.
 */
export const getPhotoStats = async ( options?: Parameters<typeof customFetchPhoto>[1]): Promise<PhotoStats> => {

  return customFetchPhoto<PhotoStats>(getGetPhotoStatsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPhotoStatsQueryKey = () => {
    return [
    `/photos/stats`
    ] as const;
    }


export const getGetPhotoStatsQueryOptions = <TData = Awaited<ReturnType<typeof getPhotoStats>>, TError = ProblemDetails>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPhotoStats>>, TError, TData>>, request?: SecondParameter<typeof customFetchPhoto>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPhotoStatsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPhotoStats>>> = ({ signal }) => getPhotoStats({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPhotoStats>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPhotoStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getPhotoStats>>>
export type GetPhotoStatsQueryError = ProblemDetails


export function useGetPhotoStats<TData = Awaited<ReturnType<typeof getPhotoStats>>, TError = ProblemDetails>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPhotoStats>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPhotoStats>>,
          TError,
          Awaited<ReturnType<typeof getPhotoStats>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchPhoto>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPhotoStats<TData = Awaited<ReturnType<typeof getPhotoStats>>, TError = ProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPhotoStats>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPhotoStats>>,
          TError,
          Awaited<ReturnType<typeof getPhotoStats>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchPhoto>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPhotoStats<TData = Awaited<ReturnType<typeof getPhotoStats>>, TError = ProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPhotoStats>>, TError, TData>>, request?: SecondParameter<typeof customFetchPhoto>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Library totals and counts by kind, status, geotag source and month.
 */

export function useGetPhotoStats<TData = Awaited<ReturnType<typeof getPhotoStats>>, TError = ProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPhotoStats>>, TError, TData>>, request?: SecondParameter<typeof customFetchPhoto>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPhotoStatsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getGetPhotoMapUrl = (params: GetPhotoMapParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/photos/map?${stringifiedParams}` : `/photos/map`
}

/**
 * @summary Geotagged Ready assets in a viewport as a GeoJSON FeatureCollection.
 */
export const getPhotoMap = async (params: GetPhotoMapParams, options?: Parameters<typeof customFetchPhoto>[1]): Promise<PhotoMapResponse> => {

  return customFetchPhoto<PhotoMapResponse>(getGetPhotoMapUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPhotoMapQueryKey = (params?: GetPhotoMapParams,) => {
    return [
    `/photos/map`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetPhotoMapQueryOptions = <TData = Awaited<ReturnType<typeof getPhotoMap>>, TError = ProblemDetails>(params: GetPhotoMapParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPhotoMap>>, TError, TData>>, request?: SecondParameter<typeof customFetchPhoto>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPhotoMapQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPhotoMap>>> = ({ signal }) => getPhotoMap(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPhotoMap>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPhotoMapQueryResult = NonNullable<Awaited<ReturnType<typeof getPhotoMap>>>
export type GetPhotoMapQueryError = ProblemDetails


export function useGetPhotoMap<TData = Awaited<ReturnType<typeof getPhotoMap>>, TError = ProblemDetails>(
 params: GetPhotoMapParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPhotoMap>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPhotoMap>>,
          TError,
          Awaited<ReturnType<typeof getPhotoMap>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchPhoto>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPhotoMap<TData = Awaited<ReturnType<typeof getPhotoMap>>, TError = ProblemDetails>(
 params: GetPhotoMapParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPhotoMap>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPhotoMap>>,
          TError,
          Awaited<ReturnType<typeof getPhotoMap>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchPhoto>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPhotoMap<TData = Awaited<ReturnType<typeof getPhotoMap>>, TError = ProblemDetails>(
 params: GetPhotoMapParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPhotoMap>>, TError, TData>>, request?: SecondParameter<typeof customFetchPhoto>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Geotagged Ready assets in a viewport as a GeoJSON FeatureCollection.
 */

export function useGetPhotoMap<TData = Awaited<ReturnType<typeof getPhotoMap>>, TError = ProblemDetails>(
 params: GetPhotoMapParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPhotoMap>>, TError, TData>>, request?: SecondParameter<typeof customFetchPhoto>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPhotoMapQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getGetPhotoUrl = (id: string,) => {




  return `/photos/${id}`
}

/**
 * @summary One asset with presigned original + thumbnail URLs.
 */
export const getPhoto = async (id: string, options?: Parameters<typeof customFetchPhoto>[1]): Promise<PhotoAssetDto> => {

  return customFetchPhoto<PhotoAssetDto>(getGetPhotoUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPhotoQueryKey = (id: string,) => {
    return [
    `/photos/${id}`
    ] as const;
    }


export const getGetPhotoQueryOptions = <TData = Awaited<ReturnType<typeof getPhoto>>, TError = ProblemDetails>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPhoto>>, TError, TData>>, request?: SecondParameter<typeof customFetchPhoto>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPhotoQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPhoto>>> = ({ signal }) => getPhoto(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPhoto>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPhotoQueryResult = NonNullable<Awaited<ReturnType<typeof getPhoto>>>
export type GetPhotoQueryError = ProblemDetails


export function useGetPhoto<TData = Awaited<ReturnType<typeof getPhoto>>, TError = ProblemDetails>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPhoto>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPhoto>>,
          TError,
          Awaited<ReturnType<typeof getPhoto>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchPhoto>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPhoto<TData = Awaited<ReturnType<typeof getPhoto>>, TError = ProblemDetails>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPhoto>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPhoto>>,
          TError,
          Awaited<ReturnType<typeof getPhoto>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetchPhoto>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPhoto<TData = Awaited<ReturnType<typeof getPhoto>>, TError = ProblemDetails>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPhoto>>, TError, TData>>, request?: SecondParameter<typeof customFetchPhoto>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary One asset with presigned original + thumbnail URLs.
 */

export function useGetPhoto<TData = Awaited<ReturnType<typeof getPhoto>>, TError = ProblemDetails>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPhoto>>, TError, TData>>, request?: SecondParameter<typeof customFetchPhoto>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPhotoQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getDeletePhotoUrl = (id: string,) => {




  return `/photos/${id}`
}

/**
 * @summary Delete an asset: objects first, then the document.
 */
export const deletePhoto = async (id: string, options?: Parameters<typeof customFetchPhoto>[1]): Promise<void> => {

  return customFetchPhoto<void>(getDeletePhotoUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeletePhotoMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePhoto>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetchPhoto>}
): UseMutationOptions<Awaited<ReturnType<typeof deletePhoto>>, TError,{id: string}, TContext> => {

const mutationKey = ['deletePhoto'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePhoto>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deletePhoto(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeletePhotoMutationResult = NonNullable<Awaited<ReturnType<typeof deletePhoto>>>

    export type DeletePhotoMutationError = ProblemDetails

    /**
 * @summary Delete an asset: objects first, then the document.
 */
export const useDeletePhoto = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePhoto>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetchPhoto>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deletePhoto>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeletePhotoMutationOptions(options), queryClient);
    }
