/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Lupira Cal API
 * Calendar backend for Lupira (contacts live in LupiraContactApi; the DAV protocol surface in LupiraDavApi). Authenticate with a Bearer token issued by the OIDC provider (Authentik).
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CalendarItemDto,
  CalendarItemOccurrenceDto,
  ContainerDto,
  CreateCalendarItemRequest,
  CreateCalendarRequest,
  CreateRelationRequest,
  FileItemToCalendarParams,
  FindRelatedItemsParams,
  GrantOwnerRequest,
  InviteParticipantParams,
  JsonNode,
  MeDto,
  OwnerGrantDto,
  ProblemDetails,
  RelationDto,
  RespondToInvitationParams,
  RevokeCalendarOwnerParams,
  SearchItemsParams,
  SetItemActionRequest,
  SetItemPromptRequest,
  UpdateCalendarItemRequest
} from './models';

import { customFetch } from '../fetcher';
type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetMeUrl = () => {




  return `/me`
}

/**
 * @summary The caller's resolved local identity (JIT-provisioned on first login).
 */
export const getMe = async ( options?: RequestInit): Promise<MeDto> => {

  return customFetch<MeDto>(getGetMeUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetMeQueryKey = () => {
    return [
    `/me`
    ] as const;
    }


export const getGetMeQueryOptions = <TData = Awaited<ReturnType<typeof getMe>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMe>>> = ({ signal }) => getMe({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMeQueryResult = NonNullable<Awaited<ReturnType<typeof getMe>>>
export type GetMeQueryError = void


export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMe>>,
          TError,
          Awaited<ReturnType<typeof getMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMe>>,
          TError,
          Awaited<ReturnType<typeof getMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary The caller's resolved local identity (JIT-provisioned on first login).
 */

export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getBootstrapMeUrl = () => {




  return `/me/bootstrap`
}

/**
 * @summary Idempotently ensure the caller has the standard calendar set; returns it.
 */
export const bootstrapMe = async ( options?: RequestInit): Promise<ContainerDto[]> => {

  return customFetch<ContainerDto[]>(getBootstrapMeUrl(),
  {
    ...options,
    method: 'POST'


  }
);}





export const getBootstrapMeMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof bootstrapMe>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof bootstrapMe>>, TError,void, TContext> => {

const mutationKey = ['bootstrapMe'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof bootstrapMe>>, void> = () => {


          return  bootstrapMe(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BootstrapMeMutationResult = NonNullable<Awaited<ReturnType<typeof bootstrapMe>>>

    export type BootstrapMeMutationError = void

    /**
 * @summary Idempotently ensure the caller has the standard calendar set; returns it.
 */
export const useBootstrapMe = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof bootstrapMe>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof bootstrapMe>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getBootstrapMeMutationOptions(options), queryClient);
    }

export const getListContainersUrl = () => {




  return `/calendars`
}

/**
 * @summary List the calendars and address books the caller can access.
 */
export const listContainers = async ( options?: RequestInit): Promise<ContainerDto[]> => {

  return customFetch<ContainerDto[]>(getListContainersUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListContainersQueryKey = () => {
    return [
    `/calendars`
    ] as const;
    }


export const getListContainersQueryOptions = <TData = Awaited<ReturnType<typeof listContainers>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listContainers>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListContainersQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listContainers>>> = ({ signal }) => listContainers({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listContainers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListContainersQueryResult = NonNullable<Awaited<ReturnType<typeof listContainers>>>
export type ListContainersQueryError = void


export function useListContainers<TData = Awaited<ReturnType<typeof listContainers>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listContainers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listContainers>>,
          TError,
          Awaited<ReturnType<typeof listContainers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListContainers<TData = Awaited<ReturnType<typeof listContainers>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listContainers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listContainers>>,
          TError,
          Awaited<ReturnType<typeof listContainers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListContainers<TData = Awaited<ReturnType<typeof listContainers>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listContainers>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List the calendars and address books the caller can access.
 */

export function useListContainers<TData = Awaited<ReturnType<typeof listContainers>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listContainers>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListContainersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getCreateCalendarUrl = () => {




  return `/calendars`
}

/**
 * @summary Create a calendar or address book (kind = 'calendar' | 'addressbook').
 */
export const createCalendar = async (createCalendarRequest: CreateCalendarRequest, options?: RequestInit): Promise<ContainerDto> => {

  return customFetch<ContainerDto>(getCreateCalendarUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createCalendarRequest)
  }
);}





export const getCreateCalendarMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCalendar>>, TError,{data: CreateCalendarRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createCalendar>>, TError,{data: CreateCalendarRequest}, TContext> => {

const mutationKey = ['createCalendar'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCalendar>>, {data: CreateCalendarRequest}> = (props) => {
          const {data} = props ?? {};

          return  createCalendar(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateCalendarMutationResult = NonNullable<Awaited<ReturnType<typeof createCalendar>>>
    export type CreateCalendarMutationBody = CreateCalendarRequest
    export type CreateCalendarMutationError = void

    /**
 * @summary Create a calendar or address book (kind = 'calendar' | 'addressbook').
 */
export const useCreateCalendar = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCalendar>>, TError,{data: CreateCalendarRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createCalendar>>,
        TError,
        {data: CreateCalendarRequest},
        TContext
      > => {
      return useMutation(getCreateCalendarMutationOptions(options), queryClient);
    }

export const getGrantCalendarOwnerUrl = (calendarId: string,) => {




  return `/calendars/${calendarId}/owners`
}

/**
 * @summary Grant a member access to a calendar (access = owner|read-write|read; default owner).
 */
export const grantCalendarOwner = async (calendarId: string,
    grantOwnerRequest: GrantOwnerRequest, options?: RequestInit): Promise<OwnerGrantDto> => {

  return customFetch<OwnerGrantDto>(getGrantCalendarOwnerUrl(calendarId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(grantOwnerRequest)
  }
);}





export const getGrantCalendarOwnerMutationOptions = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof grantCalendarOwner>>, TError,{calendarId: string;data: GrantOwnerRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof grantCalendarOwner>>, TError,{calendarId: string;data: GrantOwnerRequest}, TContext> => {

const mutationKey = ['grantCalendarOwner'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof grantCalendarOwner>>, {calendarId: string;data: GrantOwnerRequest}> = (props) => {
          const {calendarId,data} = props ?? {};

          return  grantCalendarOwner(calendarId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GrantCalendarOwnerMutationResult = NonNullable<Awaited<ReturnType<typeof grantCalendarOwner>>>
    export type GrantCalendarOwnerMutationBody = GrantOwnerRequest
    export type GrantCalendarOwnerMutationError = ProblemDetails | void

    /**
 * @summary Grant a member access to a calendar (access = owner|read-write|read; default owner).
 */
export const useGrantCalendarOwner = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof grantCalendarOwner>>, TError,{calendarId: string;data: GrantOwnerRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof grantCalendarOwner>>,
        TError,
        {calendarId: string;data: GrantOwnerRequest},
        TContext
      > => {
      return useMutation(getGrantCalendarOwnerMutationOptions(options), queryClient);
    }

export const getRevokeCalendarOwnerUrl = (calendarId: string,
    params: RevokeCalendarOwnerParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/calendars/${calendarId}/owners?${stringifiedParams}` : `/calendars/${calendarId}/owners`
}

/**
 * @summary Revoke a member's access to a calendar (by email). 409 if it would remove the last owner.
 */
export const revokeCalendarOwner = async (calendarId: string,
    params: RevokeCalendarOwnerParams, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getRevokeCalendarOwnerUrl(calendarId,params),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getRevokeCalendarOwnerMutationOptions = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof revokeCalendarOwner>>, TError,{calendarId: string;params: RevokeCalendarOwnerParams}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof revokeCalendarOwner>>, TError,{calendarId: string;params: RevokeCalendarOwnerParams}, TContext> => {

const mutationKey = ['revokeCalendarOwner'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof revokeCalendarOwner>>, {calendarId: string;params: RevokeCalendarOwnerParams}> = (props) => {
          const {calendarId,params} = props ?? {};

          return  revokeCalendarOwner(calendarId,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RevokeCalendarOwnerMutationResult = NonNullable<Awaited<ReturnType<typeof revokeCalendarOwner>>>

    export type RevokeCalendarOwnerMutationError = ProblemDetails | void

    /**
 * @summary Revoke a member's access to a calendar (by email). 409 if it would remove the last owner.
 */
export const useRevokeCalendarOwner = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof revokeCalendarOwner>>, TError,{calendarId: string;params: RevokeCalendarOwnerParams}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof revokeCalendarOwner>>,
        TError,
        {calendarId: string;params: RevokeCalendarOwnerParams},
        TContext
      > => {
      return useMutation(getRevokeCalendarOwnerMutationOptions(options), queryClient);
    }

export const getSearchItemsUrl = (params?: SearchItemsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/items?${stringifiedParams}` : `/items`
}

/**
 * @summary Search calendar items (text + tag filter; recurrence expanded in-window). Only items accepted into a calendar you can read.
 */
export const searchItems = async (params?: SearchItemsParams, options?: RequestInit): Promise<CalendarItemOccurrenceDto[]> => {

  return customFetch<CalendarItemOccurrenceDto[]>(getSearchItemsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getSearchItemsQueryKey = (params?: SearchItemsParams,) => {
    return [
    `/items`, ...(params ? [params] : [])
    ] as const;
    }


export const getSearchItemsQueryOptions = <TData = Awaited<ReturnType<typeof searchItems>>, TError = void | ProblemDetails>(params?: SearchItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchItems>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchItemsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchItems>>> = ({ signal }) => searchItems(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchItems>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchItemsQueryResult = NonNullable<Awaited<ReturnType<typeof searchItems>>>
export type SearchItemsQueryError = void | ProblemDetails


export function useSearchItems<TData = Awaited<ReturnType<typeof searchItems>>, TError = void | ProblemDetails>(
 params: undefined |  SearchItemsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchItems>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchItems>>,
          TError,
          Awaited<ReturnType<typeof searchItems>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchItems<TData = Awaited<ReturnType<typeof searchItems>>, TError = void | ProblemDetails>(
 params?: SearchItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchItems>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchItems>>,
          TError,
          Awaited<ReturnType<typeof searchItems>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchItems<TData = Awaited<ReturnType<typeof searchItems>>, TError = void | ProblemDetails>(
 params?: SearchItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchItems>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Search calendar items (text + tag filter; recurrence expanded in-window). Only items accepted into a calendar you can read.
 */

export function useSearchItems<TData = Awaited<ReturnType<typeof searchItems>>, TError = void | ProblemDetails>(
 params?: SearchItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchItems>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchItemsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getCreateItemUrl = () => {




  return `/items`
}

/**
 * @summary Create a calendar item (filed into CalendarId if given, else unfiled for later curation).
 */
export const createItem = async (createCalendarItemRequest: CreateCalendarItemRequest, options?: RequestInit): Promise<CalendarItemDto> => {

  return customFetch<CalendarItemDto>(getCreateItemUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createCalendarItemRequest)
  }
);}





export const getCreateItemMutationOptions = <TError = void | ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createItem>>, TError,{data: CreateCalendarItemRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createItem>>, TError,{data: CreateCalendarItemRequest}, TContext> => {

const mutationKey = ['createItem'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createItem>>, {data: CreateCalendarItemRequest}> = (props) => {
          const {data} = props ?? {};

          return  createItem(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateItemMutationResult = NonNullable<Awaited<ReturnType<typeof createItem>>>
    export type CreateItemMutationBody = CreateCalendarItemRequest
    export type CreateItemMutationError = void | ProblemDetails

    /**
 * @summary Create a calendar item (filed into CalendarId if given, else unfiled for later curation).
 */
export const useCreateItem = <TError = void | ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createItem>>, TError,{data: CreateCalendarItemRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createItem>>,
        TError,
        {data: CreateCalendarItemRequest},
        TContext
      > => {
      return useMutation(getCreateItemMutationOptions(options), queryClient);
    }

export const getGetItemUrl = (id: string,) => {




  return `/items/${id}`
}

/**
 * @summary Get a single calendar item.
 */
export const getItem = async (id: string, options?: RequestInit): Promise<CalendarItemDto> => {

  return customFetch<CalendarItemDto>(getGetItemUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetItemQueryKey = (id: string,) => {
    return [
    `/items/${id}`
    ] as const;
    }


export const getGetItemQueryOptions = <TData = Awaited<ReturnType<typeof getItem>>, TError = void>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItem>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetItemQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getItem>>> = ({ signal }) => getItem(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getItem>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetItemQueryResult = NonNullable<Awaited<ReturnType<typeof getItem>>>
export type GetItemQueryError = void


export function useGetItem<TData = Awaited<ReturnType<typeof getItem>>, TError = void>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItem>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getItem>>,
          TError,
          Awaited<ReturnType<typeof getItem>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetItem<TData = Awaited<ReturnType<typeof getItem>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItem>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getItem>>,
          TError,
          Awaited<ReturnType<typeof getItem>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetItem<TData = Awaited<ReturnType<typeof getItem>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItem>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a single calendar item.
 */

export function useGetItem<TData = Awaited<ReturnType<typeof getItem>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItem>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetItemQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getUpdateItemUrl = (id: string,) => {




  return `/items/${id}`
}

/**
 * @summary Update a calendar item (only provided fields change).
 */
export const updateItem = async (id: string,
    updateCalendarItemRequest: UpdateCalendarItemRequest, options?: RequestInit): Promise<CalendarItemDto> => {

  return customFetch<CalendarItemDto>(getUpdateItemUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateCalendarItemRequest)
  }
);}





export const getUpdateItemMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateItem>>, TError,{id: string;data: UpdateCalendarItemRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateItem>>, TError,{id: string;data: UpdateCalendarItemRequest}, TContext> => {

const mutationKey = ['updateItem'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateItem>>, {id: string;data: UpdateCalendarItemRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateItem(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateItemMutationResult = NonNullable<Awaited<ReturnType<typeof updateItem>>>
    export type UpdateItemMutationBody = UpdateCalendarItemRequest
    export type UpdateItemMutationError = void

    /**
 * @summary Update a calendar item (only provided fields change).
 */
export const useUpdateItem = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateItem>>, TError,{id: string;data: UpdateCalendarItemRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateItem>>,
        TError,
        {id: string;data: UpdateCalendarItemRequest},
        TContext
      > => {
      return useMutation(getUpdateItemMutationOptions(options), queryClient);
    }

export const getDeleteItemUrl = (id: string,) => {




  return `/items/${id}`
}

/**
 * @summary Delete a calendar item (soft delete + tombstone).
 */
export const deleteItem = async (id: string, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getDeleteItemUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteItemMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteItem>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteItem>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteItem'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteItem>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteItem(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteItemMutationResult = NonNullable<Awaited<ReturnType<typeof deleteItem>>>

    export type DeleteItemMutationError = void

    /**
 * @summary Delete a calendar item (soft delete + tombstone).
 */
export const useDeleteItem = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteItem>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteItem>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteItemMutationOptions(options), queryClient);
    }

export const getGetItemsByPlaceUrl = (placeId: string,) => {




  return `/items/by-place/${placeId}`
}

/**
 * @summary Calendar items anchored to a LupiraGeoApi place (its location, or a travel endpoint). Only items in a calendar you can read.
 */
export const getItemsByPlace = async (placeId: string, options?: RequestInit): Promise<CalendarItemDto[]> => {

  return customFetch<CalendarItemDto[]>(getGetItemsByPlaceUrl(placeId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetItemsByPlaceQueryKey = (placeId: string,) => {
    return [
    `/items/by-place/${placeId}`
    ] as const;
    }


export const getGetItemsByPlaceQueryOptions = <TData = Awaited<ReturnType<typeof getItemsByPlace>>, TError = void>(placeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItemsByPlace>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetItemsByPlaceQueryKey(placeId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getItemsByPlace>>> = ({ signal }) => getItemsByPlace(placeId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: placeId !== null && placeId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getItemsByPlace>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetItemsByPlaceQueryResult = NonNullable<Awaited<ReturnType<typeof getItemsByPlace>>>
export type GetItemsByPlaceQueryError = void


export function useGetItemsByPlace<TData = Awaited<ReturnType<typeof getItemsByPlace>>, TError = void>(
 placeId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItemsByPlace>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getItemsByPlace>>,
          TError,
          Awaited<ReturnType<typeof getItemsByPlace>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetItemsByPlace<TData = Awaited<ReturnType<typeof getItemsByPlace>>, TError = void>(
 placeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItemsByPlace>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getItemsByPlace>>,
          TError,
          Awaited<ReturnType<typeof getItemsByPlace>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetItemsByPlace<TData = Awaited<ReturnType<typeof getItemsByPlace>>, TError = void>(
 placeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItemsByPlace>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Calendar items anchored to a LupiraGeoApi place (its location, or a travel endpoint). Only items in a calendar you can read.
 */

export function useGetItemsByPlace<TData = Awaited<ReturnType<typeof getItemsByPlace>>, TError = void>(
 placeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItemsByPlace>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetItemsByPlaceQueryOptions(placeId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getMergeItemMetadataUrl = (id: string,) => {




  return `/items/${id}/metadata`
}

/**
 * @summary Merge arbitrary JSON metadata into a calendar item.
 */
export const mergeItemMetadata = async (id: string,
    jsonNode: JsonNode, options?: RequestInit): Promise<CalendarItemDto> => {

  return customFetch<CalendarItemDto>(getMergeItemMetadataUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(jsonNode)
  }
);}





export const getMergeItemMetadataMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof mergeItemMetadata>>, TError,{id: string;data: JsonNode}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof mergeItemMetadata>>, TError,{id: string;data: JsonNode}, TContext> => {

const mutationKey = ['mergeItemMetadata'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof mergeItemMetadata>>, {id: string;data: JsonNode}> = (props) => {
          const {id,data} = props ?? {};

          return  mergeItemMetadata(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type MergeItemMetadataMutationResult = NonNullable<Awaited<ReturnType<typeof mergeItemMetadata>>>
    export type MergeItemMetadataMutationBody = JsonNode
    export type MergeItemMetadataMutationError = void

    /**
 * @summary Merge arbitrary JSON metadata into a calendar item.
 */
export const useMergeItemMetadata = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof mergeItemMetadata>>, TError,{id: string;data: JsonNode}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof mergeItemMetadata>>,
        TError,
        {id: string;data: JsonNode},
        TContext
      > => {
      return useMutation(getMergeItemMetadataMutationOptions(options), queryClient);
    }

export const getSetItemPromptUrl = (id: string,) => {




  return `/items/${id}/prompt`
}

/**
 * @summary Set the LLM-interpreted payload on an item (server-side only; never in ICS). 409 if the item carries an action.
 */
export const setItemPrompt = async (id: string,
    setItemPromptRequest: SetItemPromptRequest, options?: RequestInit): Promise<CalendarItemDto> => {

  return customFetch<CalendarItemDto>(getSetItemPromptUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(setItemPromptRequest)
  }
);}





export const getSetItemPromptMutationOptions = <TError = void | ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setItemPrompt>>, TError,{id: string;data: SetItemPromptRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof setItemPrompt>>, TError,{id: string;data: SetItemPromptRequest}, TContext> => {

const mutationKey = ['setItemPrompt'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof setItemPrompt>>, {id: string;data: SetItemPromptRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  setItemPrompt(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SetItemPromptMutationResult = NonNullable<Awaited<ReturnType<typeof setItemPrompt>>>
    export type SetItemPromptMutationBody = SetItemPromptRequest
    export type SetItemPromptMutationError = void | ProblemDetails

    /**
 * @summary Set the LLM-interpreted payload on an item (server-side only; never in ICS). 409 if the item carries an action.
 */
export const useSetItemPrompt = <TError = void | ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setItemPrompt>>, TError,{id: string;data: SetItemPromptRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof setItemPrompt>>,
        TError,
        {id: string;data: SetItemPromptRequest},
        TContext
      > => {
      return useMutation(getSetItemPromptMutationOptions(options), queryClient);
    }

export const getClearItemPromptUrl = (id: string,) => {




  return `/items/${id}/prompt`
}

/**
 * @summary Clear the item's LLM payload.
 */
export const clearItemPrompt = async (id: string, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getClearItemPromptUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getClearItemPromptMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof clearItemPrompt>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof clearItemPrompt>>, TError,{id: string}, TContext> => {

const mutationKey = ['clearItemPrompt'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof clearItemPrompt>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  clearItemPrompt(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ClearItemPromptMutationResult = NonNullable<Awaited<ReturnType<typeof clearItemPrompt>>>

    export type ClearItemPromptMutationError = void

    /**
 * @summary Clear the item's LLM payload.
 */
export const useClearItemPrompt = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof clearItemPrompt>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof clearItemPrompt>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getClearItemPromptMutationOptions(options), queryClient);
    }

export const getSetItemActionUrl = (id: string,) => {




  return `/items/${id}/action`
}

/**
 * @summary Set the deterministic payload on an item (server-side only; never in ICS). 409 if the item carries a prompt.
 */
export const setItemAction = async (id: string,
    setItemActionRequest: SetItemActionRequest, options?: RequestInit): Promise<CalendarItemDto> => {

  return customFetch<CalendarItemDto>(getSetItemActionUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(setItemActionRequest)
  }
);}





export const getSetItemActionMutationOptions = <TError = void | ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setItemAction>>, TError,{id: string;data: SetItemActionRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof setItemAction>>, TError,{id: string;data: SetItemActionRequest}, TContext> => {

const mutationKey = ['setItemAction'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof setItemAction>>, {id: string;data: SetItemActionRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  setItemAction(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SetItemActionMutationResult = NonNullable<Awaited<ReturnType<typeof setItemAction>>>
    export type SetItemActionMutationBody = SetItemActionRequest
    export type SetItemActionMutationError = void | ProblemDetails

    /**
 * @summary Set the deterministic payload on an item (server-side only; never in ICS). 409 if the item carries a prompt.
 */
export const useSetItemAction = <TError = void | ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setItemAction>>, TError,{id: string;data: SetItemActionRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof setItemAction>>,
        TError,
        {id: string;data: SetItemActionRequest},
        TContext
      > => {
      return useMutation(getSetItemActionMutationOptions(options), queryClient);
    }

export const getClearItemActionUrl = (id: string,) => {




  return `/items/${id}/action`
}

/**
 * @summary Clear the item's deterministic payload.
 */
export const clearItemAction = async (id: string, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getClearItemActionUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getClearItemActionMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof clearItemAction>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof clearItemAction>>, TError,{id: string}, TContext> => {

const mutationKey = ['clearItemAction'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof clearItemAction>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  clearItemAction(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ClearItemActionMutationResult = NonNullable<Awaited<ReturnType<typeof clearItemAction>>>

    export type ClearItemActionMutationError = void

    /**
 * @summary Clear the item's deterministic payload.
 */
export const useClearItemAction = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof clearItemAction>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof clearItemAction>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getClearItemActionMutationOptions(options), queryClient);
    }

export const getCreateItemRelationUrl = (id: string,) => {




  return `/items/${id}/relations`
}

/**
 * @summary Link a calendar item to an external reference (e.g. a LupiraTasks item, or an Activity-API engagement/project).
 */
export const createItemRelation = async (id: string,
    createRelationRequest: CreateRelationRequest, options?: RequestInit): Promise<RelationDto> => {

  return customFetch<RelationDto>(getCreateItemRelationUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createRelationRequest)
  }
);}





export const getCreateItemRelationMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createItemRelation>>, TError,{id: string;data: CreateRelationRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createItemRelation>>, TError,{id: string;data: CreateRelationRequest}, TContext> => {

const mutationKey = ['createItemRelation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createItemRelation>>, {id: string;data: CreateRelationRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  createItemRelation(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateItemRelationMutationResult = NonNullable<Awaited<ReturnType<typeof createItemRelation>>>
    export type CreateItemRelationMutationBody = CreateRelationRequest
    export type CreateItemRelationMutationError = void

    /**
 * @summary Link a calendar item to an external reference (e.g. a LupiraTasks item, or an Activity-API engagement/project).
 */
export const useCreateItemRelation = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createItemRelation>>, TError,{id: string;data: CreateRelationRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createItemRelation>>,
        TError,
        {id: string;data: CreateRelationRequest},
        TContext
      > => {
      return useMutation(getCreateItemRelationMutationOptions(options), queryClient);
    }

export const getListItemRelationsUrl = (id: string,) => {




  return `/items/${id}/relations`
}

/**
 * @summary List a calendar item's relations.
 */
export const listItemRelations = async (id: string, options?: RequestInit): Promise<RelationDto[]> => {

  return customFetch<RelationDto[]>(getListItemRelationsUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListItemRelationsQueryKey = (id: string,) => {
    return [
    `/items/${id}/relations`
    ] as const;
    }


export const getListItemRelationsQueryOptions = <TData = Awaited<ReturnType<typeof listItemRelations>>, TError = void>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listItemRelations>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListItemRelationsQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listItemRelations>>> = ({ signal }) => listItemRelations(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listItemRelations>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListItemRelationsQueryResult = NonNullable<Awaited<ReturnType<typeof listItemRelations>>>
export type ListItemRelationsQueryError = void


export function useListItemRelations<TData = Awaited<ReturnType<typeof listItemRelations>>, TError = void>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listItemRelations>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listItemRelations>>,
          TError,
          Awaited<ReturnType<typeof listItemRelations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListItemRelations<TData = Awaited<ReturnType<typeof listItemRelations>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listItemRelations>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listItemRelations>>,
          TError,
          Awaited<ReturnType<typeof listItemRelations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListItemRelations<TData = Awaited<ReturnType<typeof listItemRelations>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listItemRelations>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List a calendar item's relations.
 */

export function useListItemRelations<TData = Awaited<ReturnType<typeof listItemRelations>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listItemRelations>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListItemRelationsQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getFindRelatedItemsUrl = (params: FindRelatedItemsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/relations?${stringifiedParams}` : `/relations`
}

/**
 * @summary Reverse lookup: calendar items linked to a given external reference.
 */
export const findRelatedItems = async (params: FindRelatedItemsParams, options?: RequestInit): Promise<CalendarItemDto[]> => {

  return customFetch<CalendarItemDto[]>(getFindRelatedItemsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getFindRelatedItemsQueryKey = (params?: FindRelatedItemsParams,) => {
    return [
    `/relations`, ...(params ? [params] : [])
    ] as const;
    }


export const getFindRelatedItemsQueryOptions = <TData = Awaited<ReturnType<typeof findRelatedItems>>, TError = void>(params: FindRelatedItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findRelatedItems>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFindRelatedItemsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof findRelatedItems>>> = ({ signal }) => findRelatedItems(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof findRelatedItems>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FindRelatedItemsQueryResult = NonNullable<Awaited<ReturnType<typeof findRelatedItems>>>
export type FindRelatedItemsQueryError = void


export function useFindRelatedItems<TData = Awaited<ReturnType<typeof findRelatedItems>>, TError = void>(
 params: FindRelatedItemsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof findRelatedItems>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findRelatedItems>>,
          TError,
          Awaited<ReturnType<typeof findRelatedItems>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindRelatedItems<TData = Awaited<ReturnType<typeof findRelatedItems>>, TError = void>(
 params: FindRelatedItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findRelatedItems>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findRelatedItems>>,
          TError,
          Awaited<ReturnType<typeof findRelatedItems>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindRelatedItems<TData = Awaited<ReturnType<typeof findRelatedItems>>, TError = void>(
 params: FindRelatedItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findRelatedItems>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Reverse lookup: calendar items linked to a given external reference.
 */

export function useFindRelatedItems<TData = Awaited<ReturnType<typeof findRelatedItems>>, TError = void>(
 params: FindRelatedItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findRelatedItems>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFindRelatedItemsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getListProposedItemsUrl = (calendarId: string,) => {




  return `/calendars/${calendarId}/proposed`
}

/**
 * @summary List items proposed into a calendar (awaiting accept/reject).
 */
export const listProposedItems = async (calendarId: string, options?: RequestInit): Promise<CalendarItemDto[]> => {

  return customFetch<CalendarItemDto[]>(getListProposedItemsUrl(calendarId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListProposedItemsQueryKey = (calendarId: string,) => {
    return [
    `/calendars/${calendarId}/proposed`
    ] as const;
    }


export const getListProposedItemsQueryOptions = <TData = Awaited<ReturnType<typeof listProposedItems>>, TError = ProblemDetails>(calendarId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProposedItems>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListProposedItemsQueryKey(calendarId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listProposedItems>>> = ({ signal }) => listProposedItems(calendarId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: calendarId !== null && calendarId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listProposedItems>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListProposedItemsQueryResult = NonNullable<Awaited<ReturnType<typeof listProposedItems>>>
export type ListProposedItemsQueryError = ProblemDetails


export function useListProposedItems<TData = Awaited<ReturnType<typeof listProposedItems>>, TError = ProblemDetails>(
 calendarId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProposedItems>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listProposedItems>>,
          TError,
          Awaited<ReturnType<typeof listProposedItems>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListProposedItems<TData = Awaited<ReturnType<typeof listProposedItems>>, TError = ProblemDetails>(
 calendarId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProposedItems>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listProposedItems>>,
          TError,
          Awaited<ReturnType<typeof listProposedItems>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListProposedItems<TData = Awaited<ReturnType<typeof listProposedItems>>, TError = ProblemDetails>(
 calendarId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProposedItems>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List items proposed into a calendar (awaiting accept/reject).
 */

export function useListProposedItems<TData = Awaited<ReturnType<typeof listProposedItems>>, TError = ProblemDetails>(
 calendarId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProposedItems>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListProposedItemsQueryOptions(calendarId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getAcceptItemIntoCalendarUrl = (itemId: string,
    calendarId: string,) => {




  return `/items/${itemId}/calendars/${calendarId}/accept`
}

/**
 * @summary Accept a proposed item into a calendar (then visible over DAV).
 */
export const acceptItemIntoCalendar = async (itemId: string,
    calendarId: string, options?: RequestInit): Promise<CalendarItemDto> => {

  return customFetch<CalendarItemDto>(getAcceptItemIntoCalendarUrl(itemId,calendarId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getAcceptItemIntoCalendarMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof acceptItemIntoCalendar>>, TError,{itemId: string;calendarId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof acceptItemIntoCalendar>>, TError,{itemId: string;calendarId: string}, TContext> => {

const mutationKey = ['acceptItemIntoCalendar'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof acceptItemIntoCalendar>>, {itemId: string;calendarId: string}> = (props) => {
          const {itemId,calendarId} = props ?? {};

          return  acceptItemIntoCalendar(itemId,calendarId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AcceptItemIntoCalendarMutationResult = NonNullable<Awaited<ReturnType<typeof acceptItemIntoCalendar>>>

    export type AcceptItemIntoCalendarMutationError = void

    /**
 * @summary Accept a proposed item into a calendar (then visible over DAV).
 */
export const useAcceptItemIntoCalendar = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof acceptItemIntoCalendar>>, TError,{itemId: string;calendarId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof acceptItemIntoCalendar>>,
        TError,
        {itemId: string;calendarId: string},
        TContext
      > => {
      return useMutation(getAcceptItemIntoCalendarMutationOptions(options), queryClient);
    }

export const getFileItemToCalendarUrl = (itemId: string,
    calendarId: string,
    params?: FileItemToCalendarParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/items/${itemId}/calendars/${calendarId}?${stringifiedParams}` : `/items/${itemId}/calendars/${calendarId}`
}

/**
 * @summary File an existing item into a calendar (status=proposed|accepted, default proposed).
 */
export const fileItemToCalendar = async (itemId: string,
    calendarId: string,
    params?: FileItemToCalendarParams, options?: RequestInit): Promise<CalendarItemDto> => {

  return customFetch<CalendarItemDto>(getFileItemToCalendarUrl(itemId,calendarId,params),
  {
    ...options,
    method: 'POST'


  }
);}





export const getFileItemToCalendarMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof fileItemToCalendar>>, TError,{itemId: string;calendarId: string;params?: FileItemToCalendarParams}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof fileItemToCalendar>>, TError,{itemId: string;calendarId: string;params?: FileItemToCalendarParams}, TContext> => {

const mutationKey = ['fileItemToCalendar'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof fileItemToCalendar>>, {itemId: string;calendarId: string;params?: FileItemToCalendarParams}> = (props) => {
          const {itemId,calendarId,params} = props ?? {};

          return  fileItemToCalendar(itemId,calendarId,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type FileItemToCalendarMutationResult = NonNullable<Awaited<ReturnType<typeof fileItemToCalendar>>>

    export type FileItemToCalendarMutationError = void

    /**
 * @summary File an existing item into a calendar (status=proposed|accepted, default proposed).
 */
export const useFileItemToCalendar = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof fileItemToCalendar>>, TError,{itemId: string;calendarId: string;params?: FileItemToCalendarParams}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof fileItemToCalendar>>,
        TError,
        {itemId: string;calendarId: string;params?: FileItemToCalendarParams},
        TContext
      > => {
      return useMutation(getFileItemToCalendarMutationOptions(options), queryClient);
    }

export const getRemoveItemFromCalendarUrl = (itemId: string,
    calendarId: string,) => {




  return `/items/${itemId}/calendars/${calendarId}`
}

/**
 * @summary Remove an item from a calendar (reject / unfile).
 */
export const removeItemFromCalendar = async (itemId: string,
    calendarId: string, options?: RequestInit): Promise<CalendarItemDto> => {

  return customFetch<CalendarItemDto>(getRemoveItemFromCalendarUrl(itemId,calendarId),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getRemoveItemFromCalendarMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeItemFromCalendar>>, TError,{itemId: string;calendarId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof removeItemFromCalendar>>, TError,{itemId: string;calendarId: string}, TContext> => {

const mutationKey = ['removeItemFromCalendar'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeItemFromCalendar>>, {itemId: string;calendarId: string}> = (props) => {
          const {itemId,calendarId} = props ?? {};

          return  removeItemFromCalendar(itemId,calendarId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RemoveItemFromCalendarMutationResult = NonNullable<Awaited<ReturnType<typeof removeItemFromCalendar>>>

    export type RemoveItemFromCalendarMutationError = void

    /**
 * @summary Remove an item from a calendar (reject / unfile).
 */
export const useRemoveItemFromCalendar = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeItemFromCalendar>>, TError,{itemId: string;calendarId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof removeItemFromCalendar>>,
        TError,
        {itemId: string;calendarId: string},
        TContext
      > => {
      return useMutation(getRemoveItemFromCalendarMutationOptions(options), queryClient);
    }

export const getInviteParticipantUrl = (id: string,
    params: InviteParticipantParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/items/${id}/participants?${stringifiedParams}` : `/items/${id}/participants`
}

/**
 * @summary Invite a contact (must be a Contact id). role = chair|req-participant|opt-participant|non-participant.
 */
export const inviteParticipant = async (id: string,
    params: InviteParticipantParams, options?: RequestInit): Promise<CalendarItemDto> => {

  return customFetch<CalendarItemDto>(getInviteParticipantUrl(id,params),
  {
    ...options,
    method: 'POST'


  }
);}





export const getInviteParticipantMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inviteParticipant>>, TError,{id: string;params: InviteParticipantParams}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof inviteParticipant>>, TError,{id: string;params: InviteParticipantParams}, TContext> => {

const mutationKey = ['inviteParticipant'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof inviteParticipant>>, {id: string;params: InviteParticipantParams}> = (props) => {
          const {id,params} = props ?? {};

          return  inviteParticipant(id,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type InviteParticipantMutationResult = NonNullable<Awaited<ReturnType<typeof inviteParticipant>>>

    export type InviteParticipantMutationError = void

    /**
 * @summary Invite a contact (must be a Contact id). role = chair|req-participant|opt-participant|non-participant.
 */
export const useInviteParticipant = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inviteParticipant>>, TError,{id: string;params: InviteParticipantParams}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof inviteParticipant>>,
        TError,
        {id: string;params: InviteParticipantParams},
        TContext
      > => {
      return useMutation(getInviteParticipantMutationOptions(options), queryClient);
    }

export const getRespondToInvitationUrl = (id: string,
    participationId: string,
    params?: RespondToInvitationParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/items/${id}/participants/${participationId}/respond?${stringifiedParams}` : `/items/${id}/participants/${participationId}/respond`
}

/**
 * @summary Record an RSVP. status = needs-action|accepted|declined|tentative|delegated.
 */
export const respondToInvitation = async (id: string,
    participationId: string,
    params?: RespondToInvitationParams, options?: RequestInit): Promise<CalendarItemDto> => {

  return customFetch<CalendarItemDto>(getRespondToInvitationUrl(id,participationId,params),
  {
    ...options,
    method: 'POST'


  }
);}





export const getRespondToInvitationMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof respondToInvitation>>, TError,{id: string;participationId: string;params?: RespondToInvitationParams}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof respondToInvitation>>, TError,{id: string;participationId: string;params?: RespondToInvitationParams}, TContext> => {

const mutationKey = ['respondToInvitation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof respondToInvitation>>, {id: string;participationId: string;params?: RespondToInvitationParams}> = (props) => {
          const {id,participationId,params} = props ?? {};

          return  respondToInvitation(id,participationId,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RespondToInvitationMutationResult = NonNullable<Awaited<ReturnType<typeof respondToInvitation>>>

    export type RespondToInvitationMutationError = void

    /**
 * @summary Record an RSVP. status = needs-action|accepted|declined|tentative|delegated.
 */
export const useRespondToInvitation = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof respondToInvitation>>, TError,{id: string;participationId: string;params?: RespondToInvitationParams}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof respondToInvitation>>,
        TError,
        {id: string;participationId: string;params?: RespondToInvitationParams},
        TContext
      > => {
      return useMutation(getRespondToInvitationMutationOptions(options), queryClient);
    }

export const getConfirmAttendanceUrl = (id: string,
    participationId: string,) => {




  return `/items/${id}/participants/${participationId}/attend`
}

/**
 * @summary Confirm attendance.
 */
export const confirmAttendance = async (id: string,
    participationId: string, options?: RequestInit): Promise<CalendarItemDto> => {

  return customFetch<CalendarItemDto>(getConfirmAttendanceUrl(id,participationId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getConfirmAttendanceMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof confirmAttendance>>, TError,{id: string;participationId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof confirmAttendance>>, TError,{id: string;participationId: string}, TContext> => {

const mutationKey = ['confirmAttendance'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof confirmAttendance>>, {id: string;participationId: string}> = (props) => {
          const {id,participationId} = props ?? {};

          return  confirmAttendance(id,participationId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ConfirmAttendanceMutationResult = NonNullable<Awaited<ReturnType<typeof confirmAttendance>>>

    export type ConfirmAttendanceMutationError = void

    /**
 * @summary Confirm attendance.
 */
export const useConfirmAttendance = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof confirmAttendance>>, TError,{id: string;participationId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof confirmAttendance>>,
        TError,
        {id: string;participationId: string},
        TContext
      > => {
      return useMutation(getConfirmAttendanceMutationOptions(options), queryClient);
    }

export const getLeaveItemUrl = (id: string,
    participationId: string,) => {




  return `/items/${id}/participants/${participationId}/leave`
}

/**
 * @summary Record that the participant left.
 */
export const leaveItem = async (id: string,
    participationId: string, options?: RequestInit): Promise<CalendarItemDto> => {

  return customFetch<CalendarItemDto>(getLeaveItemUrl(id,participationId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getLeaveItemMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof leaveItem>>, TError,{id: string;participationId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof leaveItem>>, TError,{id: string;participationId: string}, TContext> => {

const mutationKey = ['leaveItem'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof leaveItem>>, {id: string;participationId: string}> = (props) => {
          const {id,participationId} = props ?? {};

          return  leaveItem(id,participationId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LeaveItemMutationResult = NonNullable<Awaited<ReturnType<typeof leaveItem>>>

    export type LeaveItemMutationError = void

    /**
 * @summary Record that the participant left.
 */
export const useLeaveItem = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof leaveItem>>, TError,{id: string;participationId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof leaveItem>>,
        TError,
        {id: string;participationId: string},
        TContext
      > => {
      return useMutation(getLeaveItemMutationOptions(options), queryClient);
    }

export const getRemoveParticipantUrl = (id: string,
    participationId: string,) => {




  return `/items/${id}/participants/${participationId}`
}

/**
 * @summary Remove an attendee.
 */
export const removeParticipant = async (id: string,
    participationId: string, options?: RequestInit): Promise<CalendarItemDto> => {

  return customFetch<CalendarItemDto>(getRemoveParticipantUrl(id,participationId),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getRemoveParticipantMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeParticipant>>, TError,{id: string;participationId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof removeParticipant>>, TError,{id: string;participationId: string}, TContext> => {

const mutationKey = ['removeParticipant'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeParticipant>>, {id: string;participationId: string}> = (props) => {
          const {id,participationId} = props ?? {};

          return  removeParticipant(id,participationId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RemoveParticipantMutationResult = NonNullable<Awaited<ReturnType<typeof removeParticipant>>>

    export type RemoveParticipantMutationError = void

    /**
 * @summary Remove an attendee.
 */
export const useRemoveParticipant = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeParticipant>>, TError,{id: string;participationId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof removeParticipant>>,
        TError,
        {id: string;participationId: string},
        TContext
      > => {
      return useMutation(getRemoveParticipantMutationOptions(options), queryClient);
    }
