/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lupira Comms API
 * The comms substrate for Lupira: message ingestion, a per-user corpus, semantic topic segmentation, and closed-topic delivery to the assistant. Authenticate with a Bearer token issued by Authentik (owner surface) or service auth (internal hops).
 * OpenAPI spec version: v1
 */
import type { TopicStatus } from './topicStatus';

/**
 * A topic in a list response (the poll alternative — `GET /topics`).
 */
export interface TopicSummaryDto {
  id: string;
  label: string;
  /** @nullable */
  summary?: string | null;
  /** False while string TopicSummaryDto.Label is still the provisional first-few-words placeholder. */
  titled: boolean;
  status: TopicStatus;
  lastActivity: string;
  messageCount: number;
  /** @nullable */
  releasedAt?: string | null;
}
