/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lupira Comms API
 * The comms substrate for Lupira: message ingestion, a per-user corpus, semantic topic segmentation, and closed-topic delivery to the assistant. Authenticate with a Bearer token issued by Authentik (owner surface) or service auth (internal hops).
 * OpenAPI spec version: v1
 */

/**
 * The Topic lifecycle. `Open` accrues messages; the closer moves an idle topic to
 * `Closed` then `Released` (handed to the assistant). A high-similarity hit on a
 * recently-released topic may reopen it (back to `Open`) rather than start a new one.
 */
export type TopicStatus = typeof TopicStatus[keyof typeof TopicStatus];


export const TopicStatus = {
  Open: 'Open',
  Closed: 'Closed',
  Released: 'Released',
} as const;
