// <auto-generated/>
#pragma warning disable CS0618
using LupiraCalBff.Upstream.Contact.Contacts.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace LupiraCalBff.Upstream.Contact.Contacts
{
    /// <summary>
    /// Builds and executes requests for operations under \contacts
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ContactsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the LupiraCalBff.Upstream.Contact.contacts.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::LupiraCalBff.Upstream.Contact.Contacts.Item.ContactsItemRequestBuilder"/></returns>
        public global::LupiraCalBff.Upstream.Contact.Contacts.Item.ContactsItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::LupiraCalBff.Upstream.Contact.Contacts.Item.ContactsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the LupiraCalBff.Upstream.Contact.contacts.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::LupiraCalBff.Upstream.Contact.Contacts.Item.ContactsItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::LupiraCalBff.Upstream.Contact.Contacts.Item.ContactsItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("id", position);
                return new global::LupiraCalBff.Upstream.Contact.Contacts.Item.ContactsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LupiraCalBff.Upstream.Contact.Contacts.ContactsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ContactsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/contacts", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LupiraCalBff.Upstream.Contact.Contacts.ContactsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ContactsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/contacts", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
