// <auto-generated/>
#pragma warning disable CS0618
using LupiraCalBff.Upstream.Contact.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace LupiraCalBff.Upstream.Contact.Contacts.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \contacts\{id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ContactsItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::LupiraCalBff.Upstream.Contact.Contacts.Item.ContactsItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ContactsItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/contacts/{id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LupiraCalBff.Upstream.Contact.Contacts.Item.ContactsItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ContactsItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/contacts/{id}", rawUrl)
        {
        }
        /// <summary>
        /// Delete a contact (soft delete + tombstone).
        /// </summary>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::LupiraCalBff.Upstream.Contact.Models.ProblemDetails">When receiving a 401 status code</exception>
        /// <exception cref="global::LupiraCalBff.Upstream.Contact.Models.ProblemDetails">When receiving a 404 status code</exception>
        /// <exception cref="global::LupiraCalBff.Upstream.Contact.Models.ProblemDetails">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::LupiraCalBff.Upstream.Contact.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "404", global::LupiraCalBff.Upstream.Contact.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "500", global::LupiraCalBff.Upstream.Contact.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            await RequestAdapter.SendNoContentAsync(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get a single contact.
        /// </summary>
        /// <returns>A <see cref="global::LupiraCalBff.Upstream.Contact.Models.ContactDto"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::LupiraCalBff.Upstream.Contact.Models.ProblemDetails">When receiving a 401 status code</exception>
        /// <exception cref="global::LupiraCalBff.Upstream.Contact.Models.ProblemDetails">When receiving a 404 status code</exception>
        /// <exception cref="global::LupiraCalBff.Upstream.Contact.Models.ProblemDetails">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::LupiraCalBff.Upstream.Contact.Models.ContactDto?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::LupiraCalBff.Upstream.Contact.Models.ContactDto> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::LupiraCalBff.Upstream.Contact.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "404", global::LupiraCalBff.Upstream.Contact.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "500", global::LupiraCalBff.Upstream.Contact.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::LupiraCalBff.Upstream.Contact.Models.ContactDto>(requestInfo, global::LupiraCalBff.Upstream.Contact.Models.ContactDto.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Update a contact (merge — provided fields overwrite/append, unmentioned fields are kept).
        /// </summary>
        /// <returns>A <see cref="global::LupiraCalBff.Upstream.Contact.Models.ContactDto"/></returns>
        /// <param name="body">Update an existing contact by &lt;b&gt;merge&lt;/b&gt;: a provided scalar overwrites, provided reach channels/tags            are unioned onto the existing values (deduped), and any field left null keeps its current value. Enrichment never            wipes what it didn&apos;t mention. Use `PUT /contacts/{id}/channels` to remove channels. The address book isn&apos;t changeable here.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::LupiraCalBff.Upstream.Contact.Models.ProblemDetails">When receiving a 401 status code</exception>
        /// <exception cref="global::LupiraCalBff.Upstream.Contact.Models.ProblemDetails">When receiving a 403 status code</exception>
        /// <exception cref="global::LupiraCalBff.Upstream.Contact.Models.ProblemDetails">When receiving a 404 status code</exception>
        /// <exception cref="global::LupiraCalBff.Upstream.Contact.Models.ProblemDetails">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::LupiraCalBff.Upstream.Contact.Models.ContactDto?> PutAsync(global::LupiraCalBff.Upstream.Contact.Models.ReviseContactRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::LupiraCalBff.Upstream.Contact.Models.ContactDto> PutAsync(global::LupiraCalBff.Upstream.Contact.Models.ReviseContactRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::LupiraCalBff.Upstream.Contact.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "403", global::LupiraCalBff.Upstream.Contact.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "404", global::LupiraCalBff.Upstream.Contact.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "500", global::LupiraCalBff.Upstream.Contact.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::LupiraCalBff.Upstream.Contact.Models.ContactDto>(requestInfo, global::LupiraCalBff.Upstream.Contact.Models.ContactDto.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Delete a contact (soft delete + tombstone).
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/problem+json");
            return requestInfo;
        }
        /// <summary>
        /// Get a single contact.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Update a contact (merge — provided fields overwrite/append, unmentioned fields are kept).
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Update an existing contact by &lt;b&gt;merge&lt;/b&gt;: a provided scalar overwrites, provided reach channels/tags            are unioned onto the existing values (deduped), and any field left null keeps its current value. Enrichment never            wipes what it didn&apos;t mention. Use `PUT /contacts/{id}/channels` to remove channels. The address book isn&apos;t changeable here.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::LupiraCalBff.Upstream.Contact.Models.ReviseContactRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::LupiraCalBff.Upstream.Contact.Models.ReviseContactRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::LupiraCalBff.Upstream.Contact.Contacts.Item.ContactsItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::LupiraCalBff.Upstream.Contact.Contacts.Item.ContactsItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::LupiraCalBff.Upstream.Contact.Contacts.Item.ContactsItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ContactsItemRequestBuilderDeleteRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ContactsItemRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ContactsItemRequestBuilderPutRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
