// <auto-generated/>
#pragma warning disable CS0618
using LupiraCalBff.Upstream.Contact.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace LupiraCalBff.Upstream.Contact.AddressBooks.Item.Groups
{
    /// <summary>
    /// Builds and executes requests for operations under \address-books\{addressBookId}\groups
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GroupsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::LupiraCalBff.Upstream.Contact.AddressBooks.Item.Groups.GroupsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GroupsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/address-books/{addressBookId}/groups{?kind*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LupiraCalBff.Upstream.Contact.AddressBooks.Item.Groups.GroupsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GroupsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/address-books/{addressBookId}/groups{?kind*}", rawUrl)
        {
        }
        /// <summary>
        /// List groups (personal groupings + organizations) in an address book.
        /// </summary>
        /// <returns>A List&lt;global::LupiraCalBff.Upstream.Contact.Models.ContactGroupDto&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::LupiraCalBff.Upstream.Contact.Models.ProblemDetails">When receiving a 401 status code</exception>
        /// <exception cref="global::LupiraCalBff.Upstream.Contact.Models.ProblemDetails">When receiving a 403 status code</exception>
        /// <exception cref="global::LupiraCalBff.Upstream.Contact.Models.ProblemDetails">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::LupiraCalBff.Upstream.Contact.Models.ContactGroupDto>?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::LupiraCalBff.Upstream.Contact.Models.ContactGroupDto>> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::LupiraCalBff.Upstream.Contact.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "403", global::LupiraCalBff.Upstream.Contact.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "500", global::LupiraCalBff.Upstream.Contact.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::LupiraCalBff.Upstream.Contact.Models.ContactGroupDto>(requestInfo, global::LupiraCalBff.Upstream.Contact.Models.ContactGroupDto.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Create a group. kind = group|organization (an employer is an organization-kind group).
        /// </summary>
        /// <returns>A <see cref="global::LupiraCalBff.Upstream.Contact.Models.ContactGroupDto"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::LupiraCalBff.Upstream.Contact.Models.ProblemDetails">When receiving a 401 status code</exception>
        /// <exception cref="global::LupiraCalBff.Upstream.Contact.Models.ProblemDetails">When receiving a 403 status code</exception>
        /// <exception cref="global::LupiraCalBff.Upstream.Contact.Models.ProblemDetails">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::LupiraCalBff.Upstream.Contact.Models.ContactGroupDto?> PostAsync(Action<RequestConfiguration<global::LupiraCalBff.Upstream.Contact.AddressBooks.Item.Groups.GroupsRequestBuilder.GroupsRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::LupiraCalBff.Upstream.Contact.Models.ContactGroupDto> PostAsync(Action<RequestConfiguration<global::LupiraCalBff.Upstream.Contact.AddressBooks.Item.Groups.GroupsRequestBuilder.GroupsRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::LupiraCalBff.Upstream.Contact.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "403", global::LupiraCalBff.Upstream.Contact.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "500", global::LupiraCalBff.Upstream.Contact.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::LupiraCalBff.Upstream.Contact.Models.ContactGroupDto>(requestInfo, global::LupiraCalBff.Upstream.Contact.Models.ContactGroupDto.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List groups (personal groupings + organizations) in an address book.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Create a group. kind = group|organization (an employer is an organization-kind group).
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::LupiraCalBff.Upstream.Contact.AddressBooks.Item.Groups.GroupsRequestBuilder.GroupsRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::LupiraCalBff.Upstream.Contact.AddressBooks.Item.Groups.GroupsRequestBuilder.GroupsRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, "{+baseurl}/address-books/{addressBookId}/groups?name={name}{&kind*}", PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::LupiraCalBff.Upstream.Contact.AddressBooks.Item.Groups.GroupsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::LupiraCalBff.Upstream.Contact.AddressBooks.Item.Groups.GroupsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::LupiraCalBff.Upstream.Contact.AddressBooks.Item.Groups.GroupsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GroupsRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Create a group. kind = group|organization (an employer is an organization-kind group).
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GroupsRequestBuilderPostQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("kind")]
            public string? Kind { get; set; }
#nullable restore
#else
            [QueryParameter("kind")]
            public string Kind { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("name")]
            public string? Name { get; set; }
#nullable restore
#else
            [QueryParameter("name")]
            public string Name { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GroupsRequestBuilderPostRequestConfiguration : RequestConfiguration<global::LupiraCalBff.Upstream.Contact.AddressBooks.Item.Groups.GroupsRequestBuilder.GroupsRequestBuilderPostQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
